// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Analog to Digital Converter instance 1
pub const ADC = extern struct {
    /// ADC interrupt and status register
    /// offset: 0x00
    ADC_ISR: mmio.Mmio(packed struct(u32) {
        /// ADC ready This bit is set by hardware after the ADC has been enabled (ADENÂ =Â 1) and when the ADC reaches a state where it is ready to accept conversion requests. It is cleared by software writing 1 to it.
        ADRDY: enum(u1) {
            /// ADC not yet ready to start conversion (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// ADC is ready to start conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of sampling flag This bit is set by hardware during the conversion, at the end of the sampling phase.It is cleared by software by programming it to '1â.
        EOSMP: enum(u1) {
            /// Not at the end of the sampling phase (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// End of sampling phase reached
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of conversion flag This bit is set by hardware at the end of each conversion of a channel when a new data result is available in the ADC_DR register. It is cleared by software writing 1 to it or by reading the ADC_DR register.
        EOC: enum(u1) {
            /// Channel conversion not complete (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Channel conversion complete
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of sequence flag This bit is set by hardware at the end of the conversion of a sequence of channels selected by the CHSEL bits. It is cleared by software writing 1 to it.
        EOS: enum(u1) {
            /// Conversion sequence not complete (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Conversion sequence complete
            B_0x1 = 0x1,
        } = .B_0x0,
        /// ADC overrun This bit is set by hardware when an overrun occurs, meaning that a new conversion has complete while the EOC flag was already set. It is cleared by software writing 1 to it.
        OVR: enum(u1) {
            /// No overrun occurred (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Overrun has occurred
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved7: u2 = 0,
        /// Analog watchdog 1 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_TR1 and ADC_HR1 registers. It is cleared by software by programming it to 1.
        AWD1: enum(u1) {
            /// No analog watchdog event occurred (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Analog watchdog event occurred
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog 2 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_AWD2TR and ADC_AWD2TR registers. It is cleared by software programming it it.
        AWD2: enum(u1) {
            /// No analog watchdog event occurred (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Analog watchdog event occurred
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog 3 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_AWD3TR and ADC_AWD3TR registers. It is cleared by software by programming it to 1.
        AWD3: enum(u1) {
            /// No analog watchdog event occurred (or the flag event was already acknowledged and cleared by software)
            B_0x0 = 0x0,
            /// Analog watchdog event occurred
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved11: u1 = 0,
        /// End Of Calibration flag This bit is set by hardware when calibration is complete. It is cleared by software writing 1 to it.
        EOCAL: enum(u1) {
            /// Calibration is not complete
            B_0x0 = 0x0,
            /// Calibration is complete
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved13: u1 = 0,
        /// Channel Configuration Ready flag This flag bit is set by hardware when the channel configuration is applied after programming to ADC_CHSELR register or changing CHSELRMOD or SCANDIR. It is cleared by software by programming it to it. Note: When the software configures the channels (by programming ADC_CHSELR or changing CHSELRMOD or SCANDIR), it must wait until the CCRDY flag rises before configuring again or starting conversions, otherwise the new configuration (or the START bit) is ignored. Once the flag is asserted, if the software needs to configure again the channels, it must clear the CCRDY flag before proceeding with a new configuration.
        CCRDY: enum(u1) {
            /// Channel configuration update not applied.
            B_0x0 = 0x0,
            /// Channel configuration update is applied.
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u18 = 0,
    }),
    /// ADC interrupt enable register
    /// offset: 0x04
    ADC_IER: mmio.Mmio(packed struct(u32) {
        /// ADC ready interrupt enable This bit is set and cleared by software to enable/disable the ADC Ready interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        ADRDYIE: enum(u1) {
            /// ADRDY interrupt disabled.
            B_0x0 = 0x0,
            /// ADRDY interrupt enabled. An interrupt is generated when the ADRDY bit is set.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of sampling flag interrupt enable This bit is set and cleared by software to enable/disable the end of the sampling phase interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EOSMPIE: enum(u1) {
            /// EOSMP interrupt disabled.
            B_0x0 = 0x0,
            /// EOSMP interrupt enabled. An interrupt is generated when the EOSMP bit is set.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of conversion interrupt enable This bit is set and cleared by software to enable/disable the end of conversion interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EOCIE: enum(u1) {
            /// EOC interrupt disabled
            B_0x0 = 0x0,
            /// EOC interrupt enabled. An interrupt is generated when the EOC bit is set.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// End of conversion sequence interrupt enable This bit is set and cleared by software to enable/disable the end of sequence of conversions interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EOSIE: enum(u1) {
            /// EOS interrupt disabled
            B_0x0 = 0x0,
            /// EOS interrupt enabled. An interrupt is generated when the EOS bit is set.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Overrun interrupt enable This bit is set and cleared by software to enable/disable the overrun interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        OVRIE: enum(u1) {
            /// Overrun interrupt disabled
            B_0x0 = 0x0,
            /// Overrun interrupt enabled. An interrupt is generated when the OVR bit is set.
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved7: u2 = 0,
        /// Analog watchdog 1 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD1IE: enum(u1) {
            /// Analog watchdog interrupt disabled
            B_0x0 = 0x0,
            /// Analog watchdog interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog 2 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD2IE: enum(u1) {
            /// Analog watchdog interrupt disabled
            B_0x0 = 0x0,
            /// Analog watchdog interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog 3 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD3IE: enum(u1) {
            /// Analog watchdog interrupt disabled
            B_0x0 = 0x0,
            /// Analog watchdog interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved11: u1 = 0,
        /// End of calibration interrupt enable This bit is set and cleared by software to enable/disable the end of calibration interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EOCALIE: enum(u1) {
            /// End of calibration interrupt disabled
            B_0x0 = 0x0,
            /// End of calibration interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved13: u1 = 0,
        /// Channel Configuration Ready Interrupt enable This bit is set and cleared by software to enable/disable the channel configuration ready interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        CCRDYIE: enum(u1) {
            /// Channel configuration ready interrupt disabled
            B_0x0 = 0x0,
            /// Channel configuration ready interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u18 = 0,
    }),
    /// ADC control register
    /// offset: 0x08
    ADC_CR: mmio.Mmio(packed struct(u32) {
        /// ADC enable command This bit is set by software to enable the ADC. The ADC is effectively ready to operate once the ADRDY flag has been set. It is cleared by hardware when the ADC is disabled, after the execution of the ADDIS command. Note: The software is allowed to set ADEN only when all bits of ADC_CR registers are 0 (ADCALÂ =Â 0, ADSTPÂ =Â 0, ADSTARTÂ =Â 0, ADDISÂ =Â 0 and ADENÂ =Â 0)
        ADEN: enum(u1) {
            /// ADC is disabled (OFF state)
            B_0x0 = 0x0,
            /// Write 1 to enable the ADC.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// ADC disable command This bit is set by software to disable the ADC (ADDIS command) and put it into power-down state (OFF state). It is cleared by hardware once the ADC is effectively disabled (ADEN is also cleared by hardware at this time). Note: Setting ADDIS to '1â is only effective when ADENÂ =Â 1 and ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing)
        ADDIS: enum(u1) {
            /// No ADDIS command ongoing
            B_0x0 = 0x0,
            /// Write 1 to disable the ADC. Read 1 means that an ADDIS command is in progress.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// ADC start conversion command This bit is set by software to start ADC conversion. Depending on the EXTEN [1:0] configuration bits, a conversion either starts immediately (software trigger configuration) or once a hardware trigger event occurs (hardware trigger configuration). It is cleared by hardware: In single conversion mode (CONTÂ =Â 0, DISCENÂ =Â 0), when software trigger is selected (EXTENÂ =Â 00): at the assertion of the end of Conversion Sequence (EOS) flag. In discontinuous conversion mode(CONTÂ =Â 0, DISCENÂ =Â 1), when the software trigger is selected (EXTENÂ =Â 00): at the assertion of the end of Conversion (EOC) flag. In all other cases: after the execution of the ADSTP command, at the same time as the ADSTP bit is cleared by hardware. Note: The software is allowed to set ADSTART only when ADENÂ =Â 1 and ADDISÂ =Â 0 (ADC is enabled and there is no pending request to disable the ADC). After writing to ADC_CHSELR register or changing CHSELRMOD or SCANDIRW, it is mandatory to wait until CCRDY flag is asserted before setting ADSTART, otherwise, the value written to ADSTART is ignored.
        ADSTART: enum(u1) {
            /// No ADC conversion is ongoing.
            B_0x0 = 0x0,
            /// Write 1 to start the ADC. Read 1 means that the ADC is operating and may be converting.
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved4: u1 = 0,
        /// ADC stop conversion command This bit is set by software to stop and discard an ongoing conversion (ADSTP Command). It is cleared by hardware when the conversion is effectively discarded and the ADC is ready to accept a new start conversion command. Note: Setting ADSTP to '1â is only effective when ADSTARTÂ =Â 1 and ADDISÂ =Â 0 (ADC is enabled and may be converting and there is no pending request to disable the ADC)
        ADSTP: enum(u1) {
            /// No ADC stop conversion command ongoing
            B_0x0 = 0x0,
            /// Write 1 to stop the ADC. Read 1 means that an ADSTP command is in progress.
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved28: u23 = 0,
        /// ADC Voltage Regulator Enable This bit is set by software, to enable the ADC internal voltage regulator. The voltage regulator output is available after tADCVREG_SETUP. It is cleared by software to disable the voltage regulator. It can be cleared only if ADEN is et to 0. Note: The software is allowed to program this bit field only when the ADC is disabled (ADCALÂ =Â 0, ADSTARTÂ =Â 0, ADSTPÂ =Â 0, ADDISÂ =Â 0 and ADENÂ =Â 0).
        ADVREGEN: enum(u1) {
            /// ADC voltage regulator disabled
            B_0x0 = 0x0,
            /// ADC voltage regulator enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved31: u2 = 0,
        /// ADC calibration This bit is set by software to start the calibration of the ADC. It is cleared by hardware after calibration is complete. Note: The software is allowed to set ADCAL only when the ADC is disabled (ADCALÂ =Â 0, ADSTARTÂ =Â 0, ADSTPÂ =Â 0, ADDISÂ =Â 0 and ADENÂ =Â 0). The software is allowed to update the calibration factor by writing ADC_CALFACT only when ADENÂ =Â 1 and ADSTARTÂ =Â 0 (ADC enabled and no conversion is ongoing).
        ADCAL: enum(u1) {
            /// Calibration complete
            B_0x0 = 0x0,
            /// Write 1 to calibrate the ADC. Read at 1 means that a calibration is in progress.
            B_0x1 = 0x1,
        } = .B_0x0,
    }),
    /// ADC configuration register 1
    /// offset: 0x0c
    ADC_CFGR1: mmio.Mmio(packed struct(u32) {
        /// Direct memory access enable This bit is set and cleared by software to enable the generation of DMA requests. This allows the DMA controller to be used to manage automatically the converted data. For more details, refer to . Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        DMAEN: enum(u1) {
            /// DMA disabled
            B_0x0 = 0x0,
            /// DMA enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Direct memory access configuration This bit is set and cleared by software to select between two DMA modes of operation and is effective only when DMAENÂ =Â 1. For more details, refer to pageÂ 391 Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        DMACFG: enum(u1) {
            /// DMA one shot mode selected
            B_0x0 = 0x0,
            /// DMA circular mode selected
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Scan sequence direction This bit is set and cleared by software to select the direction in which the channels is scanned in the sequence. It is effective only if CHSELMOD bit is cleared to 0. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        SCANDIR: enum(u1) {
            /// Upward scan (from CHSEL0 to CHSEL18)
            B_0x0 = 0x0,
            /// Backward scan (from CHSEL18 to CHSEL0)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Data resolution These bits are written by software to select the resolution of the conversion. Note: The software is allowed to write these bits only when ADENÂ =Â 0.
        RES: enum(u2) {
            /// 12 bits
            B_0x0 = 0x0,
            /// 10 bits
            B_0x1 = 0x1,
            /// 8 bits
            B_0x2 = 0x2,
            /// 6 bits
            B_0x3 = 0x3,
        } = .B_0x0,
        /// Data alignment This bit is set and cleared by software to select right or left alignment. Refer to Data alignment and resolution (oversampling disabled: OVSE = 0) on pageÂ 389 Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        ALIGN: enum(u1) {
            /// Right alignment
            B_0x0 = 0x0,
            /// Left alignment
            B_0x1 = 0x1,
        } = .B_0x0,
        /// External trigger selection These bits select the external event used to trigger the start of conversion (refer to External triggers for details): Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EXTSEL: enum(u3) {
            /// TRG0
            B_0x0 = 0x0,
            /// TRG1
            B_0x1 = 0x1,
            /// TRG2
            B_0x2 = 0x2,
            /// TRG3
            B_0x3 = 0x3,
            /// TRG4
            B_0x4 = 0x4,
            /// TRG5
            B_0x5 = 0x5,
            /// TRG6
            B_0x6 = 0x6,
            /// TRG7
            B_0x7 = 0x7,
        } = .B_0x0,
        reserved10: u1 = 0,
        /// External trigger enable and polarity selection These bits are set and cleared by software to select the external trigger polarity and enable the trigger. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        EXTEN: enum(u2) {
            /// Hardware trigger detection disabled (conversions can be started by software)
            B_0x0 = 0x0,
            /// Hardware trigger detection on the rising edge
            B_0x1 = 0x1,
            /// Hardware trigger detection on the falling edge
            B_0x2 = 0x2,
            /// Hardware trigger detection on both the rising and falling edges
            B_0x3 = 0x3,
        } = .B_0x0,
        /// Overrun management mode This bit is set and cleared by software and configure the way data overruns are managed. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        OVRMOD: enum(u1) {
            /// ADC_DR register is preserved with the old data when an overrun is detected.
            B_0x0 = 0x0,
            /// ADC_DR register is overwritten with the last conversion result when an overrun is detected.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Single / continuous conversion mode This bit is set and cleared by software. If it is set, conversion takes place continuously until it is cleared. Note: It is not possible to have both discontinuous mode and continuous mode enabled: it is forbidden to set both bits DISCENÂ =Â 1 and CONTÂ =Â 1. The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        CONT: enum(u1) {
            /// Single conversion mode
            B_0x0 = 0x0,
            /// Continuous conversion mode
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Wait conversion mode This bit is set and cleared by software to enable/disable wait conversion mode.. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        WAIT: enum(u1) {
            /// Wait conversion mode off
            B_0x0 = 0x0,
            /// Wait conversion mode on
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Auto-off mode This bit is set and cleared by software to enable/disable auto-off mode.. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AUTOFF: enum(u1) {
            /// Auto-off mode disabled
            B_0x0 = 0x0,
            /// Auto-off mode enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Discontinuous mode This bit is set and cleared by software to enable/disable discontinuous mode. Note: It is not possible to have both discontinuous mode and continuous mode enabled: it is forbidden to set both bits DISCENÂ =Â 1 and CONTÂ =Â 1. The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        DISCEN: enum(u1) {
            /// Discontinuous mode disabled
            B_0x0 = 0x0,
            /// Discontinuous mode enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved21: u4 = 0,
        /// Mode selection of the ADC_CHSELR register This bit is set and cleared by software to control the ADC_CHSELR feature: Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSELRMOD: enum(u1) {
            /// Each bit of the ADC_CHSELR register enables an input
            B_0x0 = 0x0,
            /// ADC_CHSELR register is able to sequence up to 8 channels
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Enable the watchdog on a single channel or on all channels This bit is set and cleared by software to enable the analog watchdog on the channel identified by the AWDCH[4:0] bits or on all the channels Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD1SGL: enum(u1) {
            /// Analog watchdog 1 enabled on all channels
            B_0x0 = 0x0,
            /// Analog watchdog 1 enabled on a single channel
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog enable This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD1EN: enum(u1) {
            /// Analog watchdog 1 disabled
            B_0x0 = 0x0,
            /// Analog watchdog 1 enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved26: u2 = 0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They select the input channel to be guarded by the analog watchdog. ..... Others: Reserved Note: The channel selected by the AWDCH[4:0] bits must be also set into the CHSELR register. The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        AWD1CH: enum(u5) {
            /// ADC analog input Channel 0 monitored by AWD
            B_0x0 = 0x0,
            /// ADC analog input Channel 1 monitored by AWD
            B_0x1 = 0x1,
            /// ADC analog input Channel 17 monitored by AWD
            B_0x11 = 0x11,
            /// ADC analog input Channel 18 monitored by AWD
            B_0x12 = 0x12,
            _,
        } = .B_0x0,
        padding: u1 = 0,
    }),
    /// ADC configuration register 2
    /// offset: 0x10
    ADC_CFGR2: mmio.Mmio(packed struct(u32) {
        /// Oversampler Enable This bit is set and cleared by software. Note: Software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        OVSE: enum(u1) {
            /// Oversampler disabled
            B_0x0 = 0x0,
            /// Oversampler enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved2: u1 = 0,
        /// Oversampling ratio This bit filed defines the number of oversampling ratio. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        OVSR: enum(u3) {
            /// 2x
            B_0x0 = 0x0,
            /// 4x
            B_0x1 = 0x1,
            /// 8x
            B_0x2 = 0x2,
            /// 16x
            B_0x3 = 0x3,
            /// 32x
            B_0x4 = 0x4,
            /// 64x
            B_0x5 = 0x5,
            /// 128x
            B_0x6 = 0x6,
            /// 256x
            B_0x7 = 0x7,
        } = .B_0x0,
        /// Oversampling shift This bit is set and cleared by software. Others: Reserved Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        OVSS: enum(u4) {
            /// No shift
            B_0x0 = 0x0,
            /// Shift 1-bit
            B_0x1 = 0x1,
            /// Shift 2-bits
            B_0x2 = 0x2,
            /// Shift 3-bits
            B_0x3 = 0x3,
            /// Shift 4-bits
            B_0x4 = 0x4,
            /// Shift 5-bits
            B_0x5 = 0x5,
            /// Shift 6-bits
            B_0x6 = 0x6,
            /// Shift 7-bits
            B_0x7 = 0x7,
            /// Shift 8-bits
            B_0x8 = 0x8,
            _,
        } = .B_0x0,
        /// Triggered Oversampling This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        TOVS: enum(u1) {
            /// All oversampled conversions for a channel are done consecutively after a trigger
            B_0x0 = 0x0,
            /// Each oversampled conversion for a channel needs a trigger
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved29: u19 = 0,
        /// Low frequency trigger mode enable This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADSTART bit is cleared to 0 (this ensures that no conversion is ongoing).
        LFTRIG: enum(u1) {
            /// Low Frequency Trigger Mode disabled
            B_0x0 = 0x0,
            /// Low Frequency Trigger Mode enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// ADC clock mode These bits are set and cleared by software to define how the analog ADC is clocked: In all synchronous clock modes, there is no jitter in the delay from a timer trigger to the start of a conversion. Note: The software is allowed to write these bits only when the ADC is disabled (ADCALÂ =Â 0, ADSTARTÂ =Â 0, ADSTPÂ =Â 0, ADDISÂ =Â 0 and ADENÂ =Â 0).
        CKMODE: enum(u2) {
            /// ADCCLK (Asynchronous clock mode), generated at product level (refer to RCC section)
            B_0x0 = 0x0,
            /// PCLK/2 (Synchronous clock mode)
            B_0x1 = 0x1,
            /// PCLK/4 (Synchronous clock mode)
            B_0x2 = 0x2,
            /// PCLK (Synchronous clock mode). This configuration must be enabled only if PCLK has a 50% duty clock cycle (APB prescaler configured inside the RCC must be bypassed and the system clock must by 50% duty cycle)
            B_0x3 = 0x3,
        } = .B_0x0,
    }),
    /// ADC sampling time register
    /// offset: 0x14
    ADC_SMPR: mmio.Mmio(packed struct(u32) {
        /// Sampling time selection 1 These bits are written by software to select the sampling time that applies to all channels. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMP1: enum(u3) {
            /// 1.5 ADC clock cycles
            B_0x0 = 0x0,
            /// 3.5 ADC clock cycles
            B_0x1 = 0x1,
            /// 7.5 ADC clock cycles
            B_0x2 = 0x2,
            /// 12.5 ADC clock cycles
            B_0x3 = 0x3,
            /// 19.5 ADC clock cycles
            B_0x4 = 0x4,
            /// 39.5 ADC clock cycles
            B_0x5 = 0x5,
            /// 79.5 ADC clock cycles
            B_0x6 = 0x6,
            /// 160.5 ADC clock cycles
            B_0x7 = 0x7,
        } = .B_0x0,
        reserved4: u1 = 0,
        /// Sampling time selection 2 These bits are written by software to select the sampling time that applies to all channels. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMP2: enum(u3) {
            /// 1.5 ADC clock cycles
            B_0x0 = 0x0,
            /// 3.5 ADC clock cycles
            B_0x1 = 0x1,
            /// 7.5 ADC clock cycles
            B_0x2 = 0x2,
            /// 12.5 ADC clock cycles
            B_0x3 = 0x3,
            /// 19.5 ADC clock cycles
            B_0x4 = 0x4,
            /// 39.5 ADC clock cycles
            B_0x5 = 0x5,
            /// 79.5 ADC clock cycles
            B_0x6 = 0x6,
            /// 160.5 ADC clock cycles
            B_0x7 = 0x7,
        } = .B_0x0,
        reserved8: u1 = 0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL0: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL1: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL2: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL3: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL4: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL5: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL6: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL7: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL8: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL9: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL10: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL11: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL12: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL13: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL14: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL15: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL16: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL17: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x sampling time selection These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        SMPSEL18: enum(u1) {
            /// Sampling time of CHANNELx use the setting of SMP1[2:0] register.
            B_0x0 = 0x0,
            /// Sampling time of CHANNELx use the setting of SMP2[2:0] register.
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u5 = 0,
    }),
    /// offset: 0x18
    reserved24: [8]u8,
    /// ADC watchdog threshold register
    /// offset: 0x20
    ADC_AWD1TR: mmio.Mmio(packed struct(u32) {
        /// Analog watchdog 1 lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        LT1: u12 = 0x0,
        reserved16: u4 = 0,
        /// Analog watchdog 1 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        HT1: u12 = 0xFFF,
        padding: u4 = 0,
    }),
    /// ADC watchdog threshold register
    /// offset: 0x24
    ADC_AWD2TR: mmio.Mmio(packed struct(u32) {
        /// Analog watchdog 2 lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        LT2: u12 = 0x0,
        reserved16: u4 = 0,
        /// Analog watchdog 2 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        HT2: u12 = 0xFFF,
        padding: u4 = 0,
    }),
    /// ADC channel selection register
    /// offset: 0x28
    ADC_CHSELRMOD0: mmio.Mmio(packed struct(u32) {
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL0: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL1: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL2: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL3: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL4: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL5: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL6: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL7: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL8: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL9: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL10: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL11: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL12: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL13: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL14: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL15: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL16: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL17: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing). If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
        CHSEL18: enum(u1) {
            /// Input Channel-x is not selected for conversion
            B_0x0 = 0x0,
            /// Input Channel-x is selected for conversion
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u13 = 0,
    }),
    /// ADC watchdog threshold register
    /// offset: 0x2c
    ADC_AWD3TR: mmio.Mmio(packed struct(u32) {
        /// Analog watchdog 3lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        LT3: u12 = 0x0,
        reserved16: u4 = 0,
        /// Analog watchdog 3 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to ADC_AWDxTR) on pageÂ 395.
        HT3: u12 = 0xFFF,
        padding: u4 = 0,
    }),
    /// offset: 0x30
    reserved48: [16]u8,
    /// ADC data register
    /// offset: 0x40
    ADC_DR: mmio.Mmio(packed struct(u32) {
        /// Converted data These bits are read-only. They contain the conversion result from the last converted channel. The data are left- or right-aligned as shown in OVSE = 0) on pageÂ 389. Just after a calibration is complete, DATA[6:0] contains the calibration factor.
        DATA: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x44
    reserved68: [92]u8,
    /// ADC Analog Watchdog 2 Configuration register
    /// offset: 0xa0
    ADC_AWD2CR: mmio.Mmio(packed struct(u32) {
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH0: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH1: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH2: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH3: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH4: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH5: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH6: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH7: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH8: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH9: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH10: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH11: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH12: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH13: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH14: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH15: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH16: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH17: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        AWD2CH18: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD2
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD2
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u13 = 0,
    }),
    /// ADC Analog Watchdog 3 Configuration register
    /// offset: 0xa4
    ADC_AWD3CR: mmio.Mmio(packed struct(u32) {
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH0: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH1: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH2: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH3: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH4: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH5: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH6: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH7: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH8: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH9: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH10: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH11: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH12: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH13: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH14: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH15: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH16: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH17: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. Refer to SQ8[3:0] for a definition of channel selection. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
        AWD3CH18: enum(u1) {
            /// ADC analog channel-x is not monitored by AWD3
            B_0x0 = 0x0,
            /// ADC analog channel-x is monitored by AWD3
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u13 = 0,
    }),
    /// offset: 0xa8
    reserved168: [12]u8,
    /// ADC Calibration factor
    /// offset: 0xb4
    ADC_CALFACT: mmio.Mmio(packed struct(u32) {
        /// Calibration factor These bits are written by hardware or by software. Once a calibration is complete,Â they are updated by hardware with the calibration factors. Software can write these bits with a new calibration factor. If the new calibration factor is different from the current one stored into the analog ADC, it is then applied once a new calibration is launched. Just after a calibration is complete, DATA[6:0] contains the calibration factor. Note: Software can write these bits only when ADEN=1 (ADC is enabled and no calibration is ongoing and no conversion is ongoing). Refer to SQ8[3:0] for a definition of channel selection.
        CALFACT: u7 = 0x0,
        padding: u25 = 0,
    }),
    /// offset: 0xb8
    reserved184: [592]u8,
    /// ADC common configuration register
    /// offset: 0x308
    ADC_CCR: mmio.Mmio(packed struct(u32) {
        reserved18: u18 = 0,
        /// ADC prescaler Set and cleared by software to select the frequency of the clock to the ADC. Other: Reserved Note: Software is allowed to write these bits only when the ADC is disabled (ADCALÂ =Â 0, ADSTARTÂ =Â 0, ADSTPÂ =Â 0, ADDISÂ =Â 0 and ADENÂ =Â 0).
        PRESC: enum(u4) {
            /// input ADC clock not divided
            B_0x0 = 0x0,
            /// input ADC clock divided by 2
            B_0x1 = 0x1,
            /// input ADC clock divided by 4
            B_0x2 = 0x2,
            /// input ADC clock divided by 6
            B_0x3 = 0x3,
            /// input ADC clock divided by 8
            B_0x4 = 0x4,
            /// input ADC clock divided by 10
            B_0x5 = 0x5,
            /// input ADC clock divided by 12
            B_0x6 = 0x6,
            /// input ADC clock divided by 16
            B_0x7 = 0x7,
            /// input ADC clock divided by 32
            B_0x8 = 0x8,
            /// input ADC clock divided by 64
            B_0x9 = 0x9,
            /// input ADC clock divided by 128
            B_0xA = 0xa,
            /// input ADC clock divided by 256
            B_0xB = 0xb,
            _,
        } = .B_0x0,
        /// VREFINT enable This bit is set and cleared by software to enable/disable the VREFINT. Note: Software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        VREFEN: enum(u1) {
            /// VREFINT disabled
            B_0x0 = 0x0,
            /// VREFINT enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Temperature sensor enable This bit is set and cleared by software to enable/disable the temperature sensor. Note: Software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing).
        TSEN: enum(u1) {
            /// Temperature sensor disabled, DAC_OUT1 connected to ADC channel 12
            B_0x0 = 0x0,
            /// Temperature sensor enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// VBAT enable This bit is set and cleared by software to enable/disable the VBAT channel. Note: The software is allowed to write this bit only when ADSTARTÂ =Â 0 (which ensures that no conversion is ongoing)
        VBATEN: enum(u1) {
            /// VBAT channel disabled, DAC_OUT2 connected to ADC channel 14
            B_0x0 = 0x0,
            /// VBAT channel enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u7 = 0,
    }),
};
