// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// COMP1
pub const COMP = extern struct {
    /// Comparator 1 control and status register
    /// offset: 0x00
    COMP1_CSR: mmio.Mmio(packed struct(u32) {
        /// COMP channel 1 enable bit
        EN: u1 = 0x0,
        reserved4: u3 = 0,
        /// Comparator 2 signal selector for inverting input INM
        INMSEL: u4 = 0x0,
        /// Comparator 2 signal selector for non-inverting input
        INPSEL: u2 = 0x0,
        reserved11: u1 = 0,
        /// Comparator 2 non-inverting input selector for window mode
        WINMODE: u1 = 0x0,
        reserved14: u2 = 0,
        /// Comparator 2 output selector
        WINOUT: u1 = 0x0,
        /// Comparator 2 polarity selector
        POLARITY: u1 = 0x0,
        /// Comparator 2 hysteresis selector
        HYST: u2 = 0x0,
        /// Comparator 2 power mode selector
        PWRMODE: u2 = 0x0,
        /// Comparator 2 blanking source selector
        BLANKSEL: u5 = 0x0,
        reserved30: u5 = 0,
        /// Comparator 2 output status
        VALUE: u1 = 0x0,
        /// COMP2_CSR register lock
        LOCK: u1 = 0x0,
    }),
    /// Comparator 2 control and status register
    /// offset: 0x04
    COMP2_CSR: mmio.Mmio(packed struct(u32) {
        /// COMP channel 1 enable bit
        EN: u1 = 0x0,
        reserved4: u3 = 0,
        /// Comparator 2 signal selector for inverting input INM
        INMSEL: u4 = 0x0,
        /// Comparator 2 signal selector for non-inverting input
        INPSEL: u2 = 0x0,
        reserved11: u1 = 0,
        /// Comparator 2 non-inverting input selector for window mode
        WINMODE: u1 = 0x0,
        reserved14: u2 = 0,
        /// Comparator 2 output selector
        WINOUT: u1 = 0x0,
        /// Comparator 2 polarity selector
        POLARITY: u1 = 0x0,
        /// Comparator 2 hysteresis selector
        HYST: u2 = 0x0,
        /// Comparator 2 power mode selector
        PWRMODE: u2 = 0x0,
        /// Comparator 2 blanking source selector
        BLANKSEL: u5 = 0x0,
        reserved30: u5 = 0,
        /// Comparator 2 output status
        VALUE: u1 = 0x0,
        /// COMP2_CSR register lock
        LOCK: u1 = 0x0,
    }),
};
