// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Cyclic redundancy check calculation unit
pub const CRC = extern struct {
    /// Data register
    /// offset: 0x00
    DR: mmio.Mmio(packed struct(u32) {
        /// Data register bits
        DR: u32 = 0xFFFFFFFF,
    }),
    /// Independent data register
    /// offset: 0x04
    IDR: mmio.Mmio(packed struct(u32) {
        /// General-purpose 32-bit data register bits
        IDR: u32 = 0x0,
    }),
    /// Control register
    /// offset: 0x08
    CR: mmio.Mmio(packed struct(u32) {
        /// RESET bit
        RESET: u1 = 0x0,
        reserved3: u2 = 0,
        /// Polynomial size
        POLYSIZE: u2 = 0x0,
        /// Reverse input data
        REV_IN: u2 = 0x0,
        /// Reverse output data
        REV_OUT: u1 = 0x0,
        padding: u24 = 0,
    }),
    /// offset: 0x0c
    reserved12: [4]u8,
    /// Initial CRC value
    /// offset: 0x10
    INIT: mmio.Mmio(packed struct(u32) {
        /// Programmable initial CRC value
        CRC_INIT: u32 = 0xFFFFFFFF,
    }),
    /// polynomial
    /// offset: 0x14
    POL: mmio.Mmio(packed struct(u32) {
        /// Programmable polynomial
        POL: u32 = 0x4C11DB7,
    }),
};
