// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Debug support
pub const DBG = extern struct {
    /// MCU Device ID Code Register
    /// offset: 0x00
    IDCODE: mmio.Mmio(packed struct(u32) {
        /// Device Identifier
        DEV_ID: u16 = 0x0,
        /// Revision Identifier
        REV_ID: u16 = 0x0,
    }),
    /// Debug MCU Configuration Register
    /// offset: 0x04
    CR: mmio.Mmio(packed struct(u32) {
        reserved1: u1 = 0,
        /// Debug Stop Mode
        DBG_STOP: u1 = 0x0,
        /// Debug Standby Mode
        DBG_STANDBY: u1 = 0x0,
        padding: u29 = 0,
    }),
    /// DBG APB freeze register 1
    /// offset: 0x08
    APB_FZ1: mmio.Mmio(packed struct(u32) {
        /// Debug Timer 2 stopped when Core is halted
        DBG_TIMER2_STOP: u1 = 0x0,
        /// TIM3 counter stopped when core is halted
        DBG_TIM3_STOP: u1 = 0x0,
        reserved4: u2 = 0,
        /// Debug Timer 6 stopped when Core is halted
        DBG_TIMER6_STOP: u1 = 0x0,
        /// TIM7 counter stopped when core is halted
        DBG_TIM7_STOP: u1 = 0x0,
        reserved10: u4 = 0,
        /// Debug RTC stopped when Core is halted
        DBG_RTC_STOP: u1 = 0x0,
        /// Debug Window Wachdog stopped when Core is halted
        DBG_WWDG_STOP: u1 = 0x0,
        /// Debug Independent Wachdog stopped when Core is halted
        DBG_IWDG_STOP: u1 = 0x0,
        reserved21: u8 = 0,
        /// I2C1 SMBUS timeout mode stopped when core is halted
        DBG_I2C1_STOP: u1 = 0x0,
        reserved30: u8 = 0,
        /// Clocking of LPTIMER2 counter when the core is halted
        DBG_LPTIM2_STOP: u1 = 0x0,
        /// Clocking of LPTIMER1 counter when the core is halted
        DBG_LPTIM1_STOP: u1 = 0x0,
    }),
    /// DBG APB freeze register 2
    /// offset: 0x0c
    APB_FZ2: mmio.Mmio(packed struct(u32) {
        reserved11: u11 = 0,
        /// DBG_TIM1_STOP
        DBG_TIM1_STOP: u1 = 0x0,
        reserved15: u3 = 0,
        /// DBG_TIM14_STOP
        DBG_TIM14_STOP: u1 = 0x0,
        /// DBG_TIM15_STOP
        DBG_TIM15_STOP: u1 = 0x0,
        /// DBG_TIM16_STOP
        DBG_TIM16_STOP: u1 = 0x0,
        /// DBG_TIM17_STOP
        DBG_TIM17_STOP: u1 = 0x0,
        padding: u13 = 0,
    }),
};
