// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// DMA controller
pub const DMA = extern struct {
    /// low interrupt status register
    /// offset: 0x00
    ISR: mmio.Mmio(packed struct(u32) {
        /// global interrupt flag for channel 1
        GIF1: u1 = 0x0,
        /// transfer complete (TC) flag for channel 1
        TCIF1: u1 = 0x0,
        /// half transfer (HT) flag for channel 1
        HTIF1: u1 = 0x0,
        /// transfer error (TE) flag for channel 1
        TEIF1: u1 = 0x0,
        /// global interrupt flag for channel 2
        GIF2: u1 = 0x0,
        /// transfer complete (TC) flag for channel 2
        TCIF2: u1 = 0x0,
        /// half transfer (HT) flag for channel 2
        HTIF2: u1 = 0x0,
        /// transfer error (TE) flag for channel 2
        TEIF2: u1 = 0x0,
        /// global interrupt flag for channel 3
        GIF3: u1 = 0x0,
        /// transfer complete (TC) flag for channel 3
        TCIF3: u1 = 0x0,
        /// half transfer (HT) flag for channel 3
        HTIF3: u1 = 0x0,
        /// transfer error (TE) flag for channel 3
        TEIF3: u1 = 0x0,
        /// global interrupt flag for channel 4
        GIF4: u1 = 0x0,
        /// transfer complete (TC) flag for channel 4
        TCIF4: u1 = 0x0,
        /// half transfer (HT) flag for channel 4
        HTIF4: u1 = 0x0,
        /// transfer error (TE) flag for channel 4
        TEIF4: u1 = 0x0,
        /// global interrupt flag for channel 5
        GIF5: u1 = 0x0,
        /// transfer complete (TC) flag for channel 5
        TCIF5: u1 = 0x0,
        /// half transfer (HT) flag for channel 5
        HTIF5: u1 = 0x0,
        /// transfer error (TE) flag for channel 5
        TEIF5: u1 = 0x0,
        /// global interrupt flag for channel 6
        GIF6: u1 = 0x0,
        /// transfer complete (TC) flag for channel 6
        TCIF6: u1 = 0x0,
        /// half transfer (HT) flag for channel 6
        HTIF6: u1 = 0x0,
        /// transfer error (TE) flag for channel 6
        TEIF6: u1 = 0x0,
        /// global interrupt flag for channel 7
        GIF7: u1 = 0x0,
        /// transfer complete (TC) flag for channel 7
        TCIF7: u1 = 0x0,
        /// half transfer (HT) flag for channel 7
        HTIF7: u1 = 0x0,
        /// transfer error (TE) flag for channel 7
        TEIF7: u1 = 0x0,
        padding: u4 = 0,
    }),
    /// high interrupt status register
    /// offset: 0x04
    IFCR: mmio.Mmio(packed struct(u32) {
        /// Channel global interrupt flag
        CGIF0: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF1: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF2: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF3: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF4: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF5: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF6: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF7: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF8: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF9: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF10: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF11: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF12: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF13: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF14: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF15: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF16: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF17: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF18: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF19: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF20: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF21: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF22: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF23: u1 = 0x0,
        /// Channel global interrupt flag
        CGIF24: u1 = 0x0,
        /// Channel transfer complete flag
        CTCIF25: u1 = 0x0,
        /// Channel half transfer flag
        CHTIF26: u1 = 0x0,
        /// Channel transfer error flag
        CTEIF27: u1 = 0x0,
        padding: u4 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x08
    CCR1: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x number of data register
    /// offset: 0x0c
    CNDTR1: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x10
    CPAR1: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x14
    CMAR1: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x18
    reserved24: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x1c
    CCR2: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x number of data register
    /// offset: 0x20
    CNDTR2: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x24
    CPAR2: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x28
    CMAR2: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x2c
    reserved44: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x30
    CCR3: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x34
    CNDTR3: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x38
    CPAR3: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x3c
    CMAR3: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x40
    reserved64: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x44
    CCR4: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x48
    CNDTR4: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x4c
    CPAR4: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x50
    CMAR4: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x54
    reserved84: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x58
    CCR5: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x5c
    CNDTR5: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x60
    CPAR5: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x64
    CMAR5: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x68
    reserved104: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x6c
    CCR6: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x70
    CNDTR6: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x74
    CPAR6: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x78
    CMAR6: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
    /// offset: 0x7c
    reserved124: [4]u8,
    /// DMA channel x configuration register
    /// offset: 0x80
    CCR7: mmio.Mmio(packed struct(u32) {
        /// Channel enable
        EN: u1 = 0x0,
        /// Transfer complete interrupt enable
        TCIE: u1 = 0x0,
        /// Half transfer interrupt enable
        HTIE: u1 = 0x0,
        /// Transfer error interrupt enable
        TEIE: u1 = 0x0,
        /// Data transfer direction
        DIR: u1 = 0x0,
        /// Circular mode
        CIRC: u1 = 0x0,
        /// Peripheral increment mode
        PINC: u1 = 0x0,
        /// Memory increment mode
        MINC: u1 = 0x0,
        /// Peripheral size
        PSIZE: u2 = 0x0,
        /// Memory size
        MSIZE: u2 = 0x0,
        /// Channel priority level
        PL: u2 = 0x0,
        /// Memory to memory mode
        MEM2MEM: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// DMA channel x configuration register
    /// offset: 0x84
    CNDTR7: mmio.Mmio(packed struct(u32) {
        /// Number of data to transfer
        NDT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA channel x peripheral address register
    /// offset: 0x88
    CPAR7: mmio.Mmio(packed struct(u32) {
        /// Peripheral address
        PA: u32 = 0x0,
    }),
    /// DMA channel x memory address register
    /// offset: 0x8c
    CMAR7: mmio.Mmio(packed struct(u32) {
        /// Memory address
        MA: u32 = 0x0,
    }),
};
