// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// DMAMUX
pub const DMAMUX = extern struct {
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x00
    DMAMUX_C0CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x04
    DMAMUX_C1CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x08
    DMAMUX_C2CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x0c
    DMAMUX_C3CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x10
    DMAMUX_C4CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x14
    DMAMUX_C5CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// DMAMux - DMA request line multiplexer channel x control register
    /// offset: 0x18
    DMAMUX_C6CR: mmio.Mmio(packed struct(u32) {
        /// Input DMA request line selected
        DMAREQ_ID: u8 = 0x0,
        /// Interrupt enable at synchronization event overrun
        SOIE: u1 = 0x0,
        /// Event generation enable/disable
        EGE: u1 = 0x0,
        reserved16: u6 = 0,
        /// Synchronous operating mode enable/disable
        SE: u1 = 0x0,
        /// Synchronization event type selector Defines the synchronization event on the selected synchronization input:
        SPOL: u2 = 0x0,
        /// Number of DMA requests to forward Defines the number of DMA requests forwarded before output event is generated. In synchronous mode, it also defines the number of DMA requests to forward after a synchronization event, then stop forwarding. The actual number of DMA requests forwarded is NBREQ+1. Note: This field can only be written when both SE and EGE bits are reset.
        NBREQ: u5 = 0x0,
        /// Synchronization input selected
        SYNC_ID: u5 = 0x0,
        padding: u3 = 0,
    }),
    /// offset: 0x1c
    reserved28: [100]u8,
    /// DMAMUX request line multiplexer interrupt channel status register
    /// offset: 0x80
    DMAMUX_CSR: mmio.Mmio(packed struct(u32) {
        /// Synchronization overrun event flag
        SOF: u7 = 0x0,
        padding: u25 = 0,
    }),
    /// DMAMUX request line multiplexer interrupt clear flag register
    /// offset: 0x84
    DMAMUX_CFR: mmio.Mmio(packed struct(u32) {
        /// Clear synchronization overrun event flag
        CSOF: u7 = 0x0,
        padding: u25 = 0,
    }),
    /// offset: 0x88
    reserved136: [120]u8,
    /// DMAMux - DMA request generator channel x control register
    /// offset: 0x100
    DMAMUX_RG0CR: mmio.Mmio(packed struct(u32) {
        /// DMA request trigger input selected
        SIG_ID: u5 = 0x0,
        reserved8: u3 = 0,
        /// Interrupt enable at trigger event overrun
        OIE: u1 = 0x0,
        reserved16: u7 = 0,
        /// DMA request generator channel enable/disable
        GE: u1 = 0x0,
        /// DMA request generator trigger event type selection Defines the trigger event on the selected DMA request trigger input
        GPOL: u2 = 0x0,
        /// Number of DMA requests to generate Defines the number of DMA requests generated after a trigger event, then stop generating. The actual number of generated DMA requests is GNBREQ+1. Note: This field can only be written when GE bit is reset.
        GNBREQ: u5 = 0x0,
        padding: u8 = 0,
    }),
    /// DMAMux - DMA request generator channel x control register
    /// offset: 0x104
    DMAMUX_RG1CR: mmio.Mmio(packed struct(u32) {
        /// DMA request trigger input selected
        SIG_ID: u5 = 0x0,
        reserved8: u3 = 0,
        /// Interrupt enable at trigger event overrun
        OIE: u1 = 0x0,
        reserved16: u7 = 0,
        /// DMA request generator channel enable/disable
        GE: u1 = 0x0,
        /// DMA request generator trigger event type selection Defines the trigger event on the selected DMA request trigger input
        GPOL: u2 = 0x0,
        /// Number of DMA requests to generate Defines the number of DMA requests generated after a trigger event, then stop generating. The actual number of generated DMA requests is GNBREQ+1. Note: This field can only be written when GE bit is reset.
        GNBREQ: u5 = 0x0,
        padding: u8 = 0,
    }),
    /// DMAMux - DMA request generator channel x control register
    /// offset: 0x108
    DMAMUX_RG2CR: mmio.Mmio(packed struct(u32) {
        /// DMA request trigger input selected
        SIG_ID: u5 = 0x0,
        reserved8: u3 = 0,
        /// Interrupt enable at trigger event overrun
        OIE: u1 = 0x0,
        reserved16: u7 = 0,
        /// DMA request generator channel enable/disable
        GE: u1 = 0x0,
        /// DMA request generator trigger event type selection Defines the trigger event on the selected DMA request trigger input
        GPOL: u2 = 0x0,
        /// Number of DMA requests to generate Defines the number of DMA requests generated after a trigger event, then stop generating. The actual number of generated DMA requests is GNBREQ+1. Note: This field can only be written when GE bit is reset.
        GNBREQ: u5 = 0x0,
        padding: u8 = 0,
    }),
    /// DMAMux - DMA request generator channel x control register
    /// offset: 0x10c
    DMAMUX_RG3CR: mmio.Mmio(packed struct(u32) {
        /// DMA request trigger input selected
        SIG_ID: u5 = 0x0,
        reserved8: u3 = 0,
        /// Interrupt enable at trigger event overrun
        OIE: u1 = 0x0,
        reserved16: u7 = 0,
        /// DMA request generator channel enable/disable
        GE: u1 = 0x0,
        /// DMA request generator trigger event type selection Defines the trigger event on the selected DMA request trigger input
        GPOL: u2 = 0x0,
        /// Number of DMA requests to generate Defines the number of DMA requests generated after a trigger event, then stop generating. The actual number of generated DMA requests is GNBREQ+1. Note: This field can only be written when GE bit is reset.
        GNBREQ: u5 = 0x0,
        padding: u8 = 0,
    }),
    /// offset: 0x110
    reserved272: [48]u8,
    /// DMAMux - DMA request generator status register
    /// offset: 0x140
    DMAMUX_RGSR: mmio.Mmio(packed struct(u32) {
        /// Trigger event overrun flag The flag is set when a trigger event occurs on DMA request generator channel x, while the DMA request generator counter value is lower than GNBREQ. The flag is cleared by writing 1 to the corresponding COFx bit in DMAMUX_RGCFR register.
        OF: u4 = 0x0,
        padding: u28 = 0,
    }),
    /// DMAMux - DMA request generator clear flag register
    /// offset: 0x144
    DMAMUX_RGCFR: mmio.Mmio(packed struct(u32) {
        /// Clear trigger event overrun flag Upon setting, this bit clears the corresponding overrun flag OFx in the DMAMUX_RGCSR register.
        COF: u4 = 0x0,
        padding: u28 = 0,
    }),
    /// offset: 0x148
    reserved328: [676]u8,
    /// DMAMUX hardware configuration 2 register
    /// offset: 0x3ec
    DMAMUX_HWCFGR2: mmio.Mmio(packed struct(u32) {
        /// Number of DMA request trigger inputs
        NUM_DMA_EXT_REQ: u8 = 0x17,
        padding: u24 = 0,
    }),
    /// DMAMUX hardware configuration 1 register
    /// offset: 0x3f0
    DMAMUX_HWCFGR1: mmio.Mmio(packed struct(u32) {
        /// number of DMA request line multiplexer (output) channels
        NUM_DMA_STREAMS: u8 = 0x7,
        /// number of DMA request lines from peripherals
        NUM_DMA_PERIPH_REQ: u8 = 0x39,
        /// number of synchronization inputs
        NUM_DMA_TRIG: u8 = 0x17,
        /// number of DMA request generator channels
        NUM_DMA_REQGEN: u8 = 0x4,
    }),
    /// DMAMUX version register
    /// offset: 0x3f4
    DMAMUX_VERR: mmio.Mmio(packed struct(u32) {
        /// Minor IP revision
        MINREV: u4 = 0x1,
        /// Major IP revision
        MAJREV: u4 = 0x1,
        padding: u24 = 0,
    }),
    /// DMAMUX IP identification register
    /// offset: 0x3f8
    DMAMUX_IPIDR: mmio.Mmio(packed struct(u32) {
        /// IP identification
        ID: u32 = 0x100011,
    }),
    /// DMAMUX size identification register
    /// offset: 0x3fc
    DMAMUX_SIDR: mmio.Mmio(packed struct(u32) {
        /// Size identification
        SID: u32 = 0xA3C5DD01,
    }),
};
