// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// External interrupt/event controller
pub const EXTI = extern struct {
    /// EXTI rising trigger selection register
    /// offset: 0x00
    RTSR1: mmio.Mmio(packed struct(u32) {
        /// Rising trigger event configuration bit of Configurable Event input
        TR0: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR1: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR2: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR3: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR4: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR5: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR6: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR7: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR8: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR9: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR10: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR11: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR12: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR13: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR14: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR15: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR16: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR17: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR18: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// EXTI falling trigger selection register
    /// offset: 0x04
    FTSR1: mmio.Mmio(packed struct(u32) {
        /// Rising trigger event configuration bit of Configurable Event input
        TR0: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR1: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR2: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR3: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR4: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR5: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR6: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR7: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR8: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR9: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR10: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR11: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR12: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR13: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR14: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR15: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR16: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR17: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        TR18: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// EXTI software interrupt event register
    /// offset: 0x08
    SWIER1: mmio.Mmio(packed struct(u32) {
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER0: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER1: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER2: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER3: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER4: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER5: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER6: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER7: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER8: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER9: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER10: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER11: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER12: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER13: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER14: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER15: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER16: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER17: u1 = 0x0,
        /// Rising trigger event configuration bit of Configurable Event input
        SWIER18: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// EXTI rising edge pending register
    /// offset: 0x0c
    RPR1: mmio.Mmio(packed struct(u32) {
        /// configurable event inputs x rising edge Pending bit.
        RPIF0: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF1: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF2: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF3: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF4: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit
        RPIF5: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF6: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF7: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF8: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF9: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF10: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF11: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF12: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF13: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF14: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF15: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF16: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF17: u1 = 0x0,
        /// configurable event inputs x rising edge Pending bit.
        RPIF18: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// EXTI falling edge pending register
    /// offset: 0x10
    FPR1: mmio.Mmio(packed struct(u32) {
        /// configurable event inputs x falling edge pending bit.
        FPIF0: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF1: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF2: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF3: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF4: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF5: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF6: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF7: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF8: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF9: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF10: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF11: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF12: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF13: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF14: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF15: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF16: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF17: u1 = 0x0,
        /// configurable event inputs x falling edge pending bit.
        FPIF18: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// offset: 0x14
    reserved20: [76]u8,
    /// EXTI external interrupt selection register
    /// offset: 0x60
    EXTICR1: mmio.Mmio(packed struct(u32) {
        /// GPIO port selection
        EXTI0_7: u8 = 0x0,
        /// GPIO port selection
        EXTI8_15: u8 = 0x0,
        /// GPIO port selection
        EXTI16_23: u8 = 0x0,
        /// GPIO port selection
        EXTI24_31: u8 = 0x0,
    }),
    /// EXTI external interrupt selection register
    /// offset: 0x64
    EXTICR2: mmio.Mmio(packed struct(u32) {
        /// GPIO port selection
        EXTI0_7: u8 = 0x0,
        /// GPIO port selection
        EXTI8_15: u8 = 0x0,
        /// GPIO port selection
        EXTI16_23: u8 = 0x0,
        /// GPIO port selection
        EXTI24_31: u8 = 0x0,
    }),
    /// EXTI external interrupt selection register
    /// offset: 0x68
    EXTICR3: mmio.Mmio(packed struct(u32) {
        /// GPIO port selection
        EXTI0_7: u8 = 0x0,
        /// GPIO port selection
        EXTI8_15: u8 = 0x0,
        /// GPIO port selection
        EXTI16_23: u8 = 0x0,
        /// GPIO port selection
        EXTI24_31: u8 = 0x0,
    }),
    /// EXTI external interrupt selection register
    /// offset: 0x6c
    EXTICR4: mmio.Mmio(packed struct(u32) {
        /// GPIO port selection
        EXTI0_7: u8 = 0x0,
        /// GPIO port selection
        EXTI8_15: u8 = 0x0,
        /// GPIO port selection
        EXTI16_23: u8 = 0x0,
        /// GPIO port selection
        EXTI24_31: u8 = 0x0,
    }),
    /// offset: 0x70
    reserved112: [16]u8,
    /// EXTI CPU wakeup with interrupt mask register
    /// offset: 0x80
    IMR1: mmio.Mmio(packed struct(u32) {
        /// CPU wakeup with interrupt mask on event input
        IM0: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM1: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM2: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM3: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM4: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM5: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM6: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM7: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM8: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM9: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM10: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM11: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM12: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM13: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM14: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM15: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM16: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM17: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM18: u1 = 0x0,
        /// CPU wakeup with interrupt mask on event input
        IM19: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM20: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM21: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM22: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM23: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM24: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM25: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM26: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM27: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM28: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM29: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM30: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM31: u1 = 0x1,
    }),
    /// offset: 0x84
    reserved132: [12]u8,
    /// EXTI CPU wakeup with interrupt mask register
    /// offset: 0x90
    IMR2: mmio.Mmio(packed struct(u32) {
        /// CPU wakeup with interrupt mask on event input
        IM32: u1 = 0x1,
        /// CPU wakeup with interrupt mask on event input
        IM33: u1 = 0x1,
        padding: u30 = 0,
    }),
    /// EXTI CPU wakeup with event mask register
    /// offset: 0x94
    EMR2: mmio.Mmio(packed struct(u32) {
        /// CPU wakeup with event mask on event input
        EM32: u1 = 0x0,
        /// CPU wakeup with event mask on event input
        EM33: u1 = 0x0,
        padding: u30 = 0,
    }),
    /// offset: 0x98
    reserved152: [832]u8,
    /// Hardware configuration registers
    /// offset: 0x3d8
    HWCFGR7: mmio.Mmio(packed struct(u32) {
        /// HW configuration CPU event generation
        CPUEVENT: u32 = 0x0,
    }),
    /// Hardware configuration registers
    /// offset: 0x3dc
    HWCFGR6: mmio.Mmio(packed struct(u32) {
        /// HW configuration CPU event generation
        CPUEVENT: u32 = 0x3,
    }),
    /// Hardware configuration registers
    /// offset: 0x3e0
    HWCFGR5: mmio.Mmio(packed struct(u32) {
        /// HW configuration CPU event generation
        CPUEVENT: u32 = 0xFEAFFFFF,
    }),
    /// Hardware configuration registers
    /// offset: 0x3e4
    HWCFGR4: mmio.Mmio(packed struct(u32) {
        /// HW configuration event trigger type
        EVENT_TRG: u32 = 0x0,
    }),
    /// Hardware configuration registers
    /// offset: 0x3e8
    HWCFGR3: mmio.Mmio(packed struct(u32) {
        /// HW configuration event trigger type
        EVENT_TRG: u32 = 0x0,
    }),
    /// Hardware configuration registers
    /// offset: 0x3ec
    HWCFGR2: mmio.Mmio(packed struct(u32) {
        /// HW configuration event trigger type
        EVENT_TRG: u32 = 0x7FFFF,
    }),
    /// Hardware configuration registers
    /// offset: 0x3f0
    HWCFGR1: mmio.Mmio(packed struct(u32) {
        /// configuration number of event
        NBEVENTS: u8 = 0x21,
        /// configuration number of CPUs
        NBCPUS: u4 = 0x0,
        /// HW configuration of CPU event output enable
        CPUEVTEN: u4 = 0x1,
        /// HW configuration of number of IO ports
        NBIOPORT: u8 = 0x5,
        padding: u8 = 0,
    }),
    /// AES version register
    /// offset: 0x3f4
    VERR: mmio.Mmio(packed struct(u32) {
        /// Minor revision
        MINREV: u4 = 0x0,
        /// Major revision
        MAJREV: u4 = 0x3,
        padding: u24 = 0,
    }),
    /// AES identification register
    /// offset: 0x3f8
    IPIDR: mmio.Mmio(packed struct(u32) {
        /// Identification code
        ID: u32 = 0xE0001,
    }),
    /// AES size ID register
    /// offset: 0x3fc
    SIDR: mmio.Mmio(packed struct(u32) {
        /// Size Identification code
        ID: u32 = 0xA3C5DD01,
    }),
};
