// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Flash
pub const FLASH = extern struct {
    /// Access control register
    /// offset: 0x00
    ACR: mmio.Mmio(packed struct(u32) {
        /// Latency
        LATENCY: u3 = 0x0,
        reserved8: u5 = 0,
        /// Prefetch enable
        PRFTEN: u1 = 0x0,
        /// Instruction cache enable
        ICEN: u1 = 0x1,
        reserved11: u1 = 0,
        /// Instruction cache reset
        ICRST: u1 = 0x0,
        reserved16: u4 = 0,
        /// Flash User area empty
        EMPTY: u1 = 0x0,
        reserved18: u1 = 0,
        /// Debug access software enable
        DBG_SWEN: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// offset: 0x04
    reserved4: [4]u8,
    /// Flash key register
    /// offset: 0x08
    KEYR: mmio.Mmio(packed struct(u32) {
        /// KEYR
        KEYR: u32 = 0x0,
    }),
    /// Option byte key register
    /// offset: 0x0c
    OPTKEYR: mmio.Mmio(packed struct(u32) {
        /// Option byte key
        OPTKEYR: u32 = 0x0,
    }),
    /// Status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// End of operation
        EOP: u1 = 0x0,
        /// Operation error
        OPERR: u1 = 0x0,
        reserved3: u1 = 0,
        /// Programming error
        PROGERR: u1 = 0x0,
        /// Write protected error
        WRPERR: u1 = 0x0,
        /// Programming alignment error
        PGAERR: u1 = 0x0,
        /// Size error
        SIZERR: u1 = 0x0,
        /// Programming sequence error
        PGSERR: u1 = 0x0,
        /// Fast programming data miss error
        MISERR: u1 = 0x0,
        /// Fast programming error
        FASTERR: u1 = 0x0,
        reserved14: u4 = 0,
        /// PCROP read error
        RDERR: u1 = 0x0,
        /// Option and Engineering bits loading validity error
        OPTVERR: u1 = 0x0,
        /// Busy
        BSY: u1 = 0x0,
        reserved18: u1 = 0,
        /// Programming or erase configuration busy.
        CFGBSY: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// Flash control register
    /// offset: 0x14
    CR: mmio.Mmio(packed struct(u32) {
        /// Programming
        PG: u1 = 0x0,
        /// Page erase
        PER: u1 = 0x0,
        /// Mass erase
        MER: u1 = 0x0,
        /// Page number
        PNB: u6 = 0x0,
        reserved16: u7 = 0,
        /// Start
        STRT: u1 = 0x0,
        /// Options modification start
        OPTSTRT: u1 = 0x0,
        /// Fast programming
        FSTPG: u1 = 0x0,
        reserved24: u5 = 0,
        /// End of operation interrupt enable
        EOPIE: u1 = 0x0,
        /// Error interrupt enable
        ERRIE: u1 = 0x0,
        /// PCROP read error interrupt enable
        RDERRIE: u1 = 0x0,
        /// Force the option byte loading
        OBL_LAUNCH: u1 = 0x0,
        /// Securable memory area protection enable
        SEC_PROT: u1 = 0x0,
        reserved30: u1 = 0,
        /// Options Lock
        OPTLOCK: u1 = 0x1,
        /// FLASH_CR Lock
        LOCK: u1 = 0x1,
    }),
    /// Flash ECC register
    /// offset: 0x18
    ECCR: mmio.Mmio(packed struct(u32) {
        /// ECC fail address
        ADDR_ECC: u14 = 0x0,
        reserved20: u6 = 0,
        /// ECC fail for Corrected ECC Error or Double ECC Error in info block
        SYSF_ECC: u1 = 0x0,
        reserved24: u3 = 0,
        /// ECC correction interrupt enable
        ECCIE: u1 = 0x0,
        reserved30: u5 = 0,
        /// ECC correction
        ECCC: u1 = 0x0,
        /// ECC detection
        ECCD: u1 = 0x0,
    }),
    /// offset: 0x1c
    reserved28: [4]u8,
    /// Flash option register
    /// offset: 0x20
    OPTR: mmio.Mmio(packed struct(u32) {
        /// Read protection level
        RDP: u8 = 0x0,
        /// BOR reset Level
        BOREN: u1 = 0x0,
        /// These bits contain the VDD supply level threshold that activates the reset
        BORF_LEV: u2 = 0x0,
        /// These bits contain the VDD supply level threshold that releases the reset.
        BORR_LEV: u2 = 0x0,
        /// nRST_STOP
        nRST_STOP: u1 = 0x0,
        /// nRST_STDBY
        nRST_STDBY: u1 = 0x0,
        /// nRSTS_HDW
        nRSTS_HDW: u1 = 0x0,
        /// Independent watchdog selection
        IDWG_SW: u1 = 0x0,
        /// Independent watchdog counter freeze in Stop mode
        IWDG_STOP: u1 = 0x0,
        /// Independent watchdog counter freeze in Standby mode
        IWDG_STDBY: u1 = 0x0,
        /// Window watchdog selection
        WWDG_SW: u1 = 0x0,
        reserved22: u2 = 0,
        /// SRAM parity check control
        RAM_PARITY_CHECK: u1 = 0x0,
        reserved24: u1 = 0,
        /// nBOOT_SEL
        nBOOT_SEL: u1 = 0x0,
        /// Boot configuration
        nBOOT1: u1 = 0x0,
        /// nBOOT0 option bit
        nBOOT0: u1 = 0x0,
        /// NRST_MODE
        NRST_MODE: u2 = 0x2,
        /// Internal reset holder enable bit
        IRHEN: u1 = 0x1,
        padding: u2 = 0,
    }),
    /// Flash PCROP zone A Start address register
    /// offset: 0x24
    PCROP1ASR: mmio.Mmio(packed struct(u32) {
        /// PCROP1A area start offset
        PCROP1A_STRT: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// Flash PCROP zone A End address register
    /// offset: 0x28
    PCROP1AER: mmio.Mmio(packed struct(u32) {
        /// PCROP1A area end offset
        PCROP1A_END: u8 = 0x0,
        reserved31: u23 = 0,
        /// PCROP area preserved when RDP level decreased
        PCROP_RDP: u1 = 0x1,
    }),
    /// Flash WRP area A address register
    /// offset: 0x2c
    WRP1AR: mmio.Mmio(packed struct(u32) {
        /// WRP area A start offset
        WRP1A_STRT: u6 = 0x0,
        reserved16: u10 = 0,
        /// WRP area A end offset
        WRP1A_END: u6 = 0x0,
        padding: u10 = 0,
    }),
    /// Flash WRP area B address register
    /// offset: 0x30
    WRP1BR: mmio.Mmio(packed struct(u32) {
        /// WRP area B start offset
        WRP1B_STRT: u6 = 0x0,
        reserved16: u10 = 0,
        /// WRP area B end offset
        WRP1B_END: u6 = 0x0,
        padding: u10 = 0,
    }),
    /// Flash PCROP zone B Start address register
    /// offset: 0x34
    PCROP1BSR: mmio.Mmio(packed struct(u32) {
        /// PCROP1B area start offset
        PCROP1B_STRT: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// Flash PCROP zone B End address register
    /// offset: 0x38
    PCROP1BER: mmio.Mmio(packed struct(u32) {
        /// PCROP1B area end offset
        PCROP1B_END: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// offset: 0x3c
    reserved60: [68]u8,
    /// Flash Security register
    /// offset: 0x80
    SECR: mmio.Mmio(packed struct(u32) {
        /// Securable memory area size
        SEC_SIZE: u7 = 0x0,
        reserved16: u9 = 0,
        /// used to force boot from user area
        BOOT_LOCK: u1 = 0x0,
        padding: u15 = 0,
    }),
};
