// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Inter-integrated circuit
pub const I2C1 = extern struct {
    /// Control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Peripheral enable
        PE: u1 = 0x0,
        /// TX Interrupt enable
        TXIE: u1 = 0x0,
        /// RX Interrupt enable
        RXIE: u1 = 0x0,
        /// Address match interrupt enable (slave only)
        ADDRIE: u1 = 0x0,
        /// Not acknowledge received interrupt enable
        NACKIE: u1 = 0x0,
        /// STOP detection Interrupt enable
        STOPIE: u1 = 0x0,
        /// Transfer Complete interrupt enable
        TCIE: u1 = 0x0,
        /// Error interrupts enable
        ERRIE: u1 = 0x0,
        /// Digital noise filter
        DNF: u4 = 0x0,
        /// Analog noise filter OFF
        ANFOFF: u1 = 0x0,
        reserved14: u1 = 0,
        /// DMA transmission requests enable
        TXDMAEN: u1 = 0x0,
        /// DMA reception requests enable
        RXDMAEN: u1 = 0x0,
        /// Slave byte control
        SBC: u1 = 0x0,
        /// Clock stretching disable
        NOSTRETCH: u1 = 0x0,
        /// Wakeup from STOP enable
        WUPEN: u1 = 0x0,
        /// General call enable
        GCEN: u1 = 0x0,
        /// SMBus Host address enable
        SMBHEN: u1 = 0x0,
        /// SMBus Device Default address enable
        SMBDEN: u1 = 0x0,
        /// SMBUS alert enable
        ALERTEN: u1 = 0x0,
        /// PEC enable
        PECEN: u1 = 0x0,
        padding: u8 = 0,
    }),
    /// Control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Slave address bit (master mode)
        SADD: u10 = 0x0,
        /// Transfer direction (master mode)
        RD_WRN: u1 = 0x0,
        /// 10-bit addressing mode (master mode)
        ADD10: u1 = 0x0,
        /// 10-bit address header only read direction (master receiver mode)
        HEAD10R: u1 = 0x0,
        /// Start generation
        START: u1 = 0x0,
        /// Stop generation (master mode)
        STOP: u1 = 0x0,
        /// NACK generation (slave mode)
        NACK: u1 = 0x0,
        /// Number of bytes
        NBYTES: u8 = 0x0,
        /// NBYTES reload mode
        RELOAD: u1 = 0x0,
        /// Automatic end mode (master mode)
        AUTOEND: u1 = 0x0,
        /// Packet error checking byte
        PECBYTE: u1 = 0x0,
        padding: u5 = 0,
    }),
    /// Own address register 1
    /// offset: 0x08
    OAR1: mmio.Mmio(packed struct(u32) {
        /// Interface address
        OA1_0: u1 = 0x0,
        /// Interface address
        OA1_7_1: u7 = 0x0,
        /// Interface address
        OA1_8_9: u2 = 0x0,
        /// Own Address 1 10-bit mode
        OA1MODE: u1 = 0x0,
        reserved15: u4 = 0,
        /// Own Address 1 enable
        OA1EN: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Own address register 2
    /// offset: 0x0c
    OAR2: mmio.Mmio(packed struct(u32) {
        reserved1: u1 = 0,
        /// Interface address
        OA2: u7 = 0x0,
        /// Own Address 2 masks
        OA2MSK: u3 = 0x0,
        reserved15: u4 = 0,
        /// Own Address 2 enable
        OA2EN: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Timing register
    /// offset: 0x10
    TIMINGR: mmio.Mmio(packed struct(u32) {
        /// SCL low period (master mode)
        SCLL: u8 = 0x0,
        /// SCL high period (master mode)
        SCLH: u8 = 0x0,
        /// Data hold time
        SDADEL: u4 = 0x0,
        /// Data setup time
        SCLDEL: u4 = 0x0,
        reserved28: u4 = 0,
        /// Timing prescaler
        PRESC: u4 = 0x0,
    }),
    /// Status register 1
    /// offset: 0x14
    TIMEOUTR: mmio.Mmio(packed struct(u32) {
        /// Bus timeout A
        TIMEOUTA: u12 = 0x0,
        /// Idle clock timeout detection
        TIDLE: u1 = 0x0,
        reserved15: u2 = 0,
        /// Clock timeout enable
        TIMOUTEN: u1 = 0x0,
        /// Bus timeout B
        TIMEOUTB: u12 = 0x0,
        reserved31: u3 = 0,
        /// Extended clock timeout enable
        TEXTEN: u1 = 0x0,
    }),
    /// Interrupt and Status register
    /// offset: 0x18
    ISR: mmio.Mmio(packed struct(u32) {
        /// Transmit data register empty (transmitters)
        TXE: u1 = 0x1,
        /// Transmit interrupt status (transmitters)
        TXIS: u1 = 0x0,
        /// Receive data register not empty (receivers)
        RXNE: u1 = 0x0,
        /// Address matched (slave mode)
        ADDR: u1 = 0x0,
        /// Not acknowledge received flag
        NACKF: u1 = 0x0,
        /// Stop detection flag
        STOPF: u1 = 0x0,
        /// Transfer Complete (master mode)
        TC: u1 = 0x0,
        /// Transfer Complete Reload
        TCR: u1 = 0x0,
        /// Bus error
        BERR: u1 = 0x0,
        /// Arbitration lost
        ARLO: u1 = 0x0,
        /// Overrun/Underrun (slave mode)
        OVR: u1 = 0x0,
        /// PEC Error in reception
        PECERR: u1 = 0x0,
        /// Timeout or t_low detection flag
        TIMEOUT: u1 = 0x0,
        /// SMBus alert
        ALERT: u1 = 0x0,
        reserved15: u1 = 0,
        /// Bus busy
        BUSY: u1 = 0x0,
        /// Transfer direction (Slave mode)
        DIR: u1 = 0x0,
        /// Address match code (Slave mode)
        ADDCODE: u7 = 0x0,
        padding: u8 = 0,
    }),
    /// Interrupt clear register
    /// offset: 0x1c
    ICR: mmio.Mmio(packed struct(u32) {
        reserved3: u3 = 0,
        /// Address Matched flag clear
        ADDRCF: u1 = 0x0,
        /// Not Acknowledge flag clear
        NACKCF: u1 = 0x0,
        /// Stop detection flag clear
        STOPCF: u1 = 0x0,
        reserved8: u2 = 0,
        /// Bus error flag clear
        BERRCF: u1 = 0x0,
        /// Arbitration lost flag clear
        ARLOCF: u1 = 0x0,
        /// Overrun/Underrun flag clear
        OVRCF: u1 = 0x0,
        /// PEC Error flag clear
        PECCF: u1 = 0x0,
        /// Timeout detection flag clear
        TIMOUTCF: u1 = 0x0,
        /// Alert flag clear
        ALERTCF: u1 = 0x0,
        padding: u18 = 0,
    }),
    /// PEC register
    /// offset: 0x20
    PECR: mmio.Mmio(packed struct(u32) {
        /// Packet error checking register
        PEC: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// Receive data register
    /// offset: 0x24
    RXDR: mmio.Mmio(packed struct(u32) {
        /// 8-bit receive data
        RXDATA: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// Transmit data register
    /// offset: 0x28
    TXDR: mmio.Mmio(packed struct(u32) {
        /// 8-bit transmit data
        TXDATA: u8 = 0x0,
        padding: u24 = 0,
    }),
};
