// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Independent watchdog
pub const IWDG = extern struct {
    /// Key register
    /// offset: 0x00
    KR: mmio.Mmio(packed struct(u32) {
        /// Key value (write only, read 0x0000)
        KEY: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// Prescaler register
    /// offset: 0x04
    PR: mmio.Mmio(packed struct(u32) {
        /// Prescaler divider
        PR: u3 = 0x0,
        padding: u29 = 0,
    }),
    /// Reload register
    /// offset: 0x08
    RLR: mmio.Mmio(packed struct(u32) {
        /// Watchdog counter reload value
        RL: u12 = 0xFFF,
        padding: u20 = 0,
    }),
    /// Status register
    /// offset: 0x0c
    SR: mmio.Mmio(packed struct(u32) {
        /// Watchdog prescaler value update
        PVU: u1 = 0x0,
        /// Watchdog counter reload value update
        RVU: u1 = 0x0,
        /// Watchdog counter window value update
        WVU: u1 = 0x0,
        padding: u29 = 0,
    }),
    /// Window register
    /// offset: 0x10
    WINR: mmio.Mmio(packed struct(u32) {
        /// Watchdog counter window value
        WIN: u12 = 0xFFF,
        padding: u20 = 0,
    }),
    /// offset: 0x14
    reserved20: [988]u8,
    /// hardware configuration register
    /// offset: 0x3f0
    HWCFGR: mmio.Mmio(packed struct(u32) {
        /// Support of Window function
        WINDOW: u4 = 0x1,
        /// Prescaler default value
        PR_DEFAULT: u4 = 0x7,
        padding: u24 = 0,
    }),
    /// EXTI IP Version register
    /// offset: 0x3f4
    VERR: mmio.Mmio(packed struct(u32) {
        /// Minor Revision number
        MINREV: u4 = 0x3,
        /// Major Revision number
        MAJREV: u4 = 0x2,
        padding: u24 = 0,
    }),
    /// EXTI Identification register
    /// offset: 0x3f8
    IPIDR: mmio.Mmio(packed struct(u32) {
        /// IP Identification
        IPID: u32 = 0x120041,
    }),
    /// EXTI Size ID register
    /// offset: 0x3fc
    SIDR: mmio.Mmio(packed struct(u32) {
        /// Size Identification
        SID: u32 = 0xA3C5DD01,
    }),
};
