// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Low power timer
pub const LPTIM1 = extern struct {
    /// Interrupt and Status Register
    /// offset: 0x00
    ISR: mmio.Mmio(packed struct(u32) {
        /// Compare match
        CMPM: u1 = 0x0,
        /// Autoreload match
        ARRM: u1 = 0x0,
        /// External trigger edge event
        EXTTRIG: u1 = 0x0,
        /// Compare register update OK
        CMPOK: u1 = 0x0,
        /// Autoreload register update OK
        ARROK: u1 = 0x0,
        /// Counter direction change down to up
        UP: u1 = 0x0,
        /// Counter direction change up to down
        DOWN: u1 = 0x0,
        padding: u25 = 0,
    }),
    /// Interrupt Clear Register
    /// offset: 0x04
    ICR: mmio.Mmio(packed struct(u32) {
        /// compare match Clear Flag
        CMPMCF: u1 = 0x0,
        /// Autoreload match Clear Flag
        ARRMCF: u1 = 0x0,
        /// External trigger valid edge Clear Flag
        EXTTRIGCF: u1 = 0x0,
        /// Compare register update OK Clear Flag
        CMPOKCF: u1 = 0x0,
        /// Autoreload register update OK Clear Flag
        ARROKCF: u1 = 0x0,
        /// Direction change to UP Clear Flag
        UPCF: u1 = 0x0,
        /// Direction change to down Clear Flag
        DOWNCF: u1 = 0x0,
        padding: u25 = 0,
    }),
    /// Interrupt Enable Register
    /// offset: 0x08
    IER: mmio.Mmio(packed struct(u32) {
        /// Compare match Interrupt Enable
        CMPMIE: u1 = 0x0,
        /// Autoreload match Interrupt Enable
        ARRMIE: u1 = 0x0,
        /// External trigger valid edge Interrupt Enable
        EXTTRIGIE: u1 = 0x0,
        /// Compare register update OK Interrupt Enable
        CMPOKIE: u1 = 0x0,
        /// Autoreload register update OK Interrupt Enable
        ARROKIE: u1 = 0x0,
        /// Direction change to UP Interrupt Enable
        UPIE: u1 = 0x0,
        /// Direction change to down Interrupt Enable
        DOWNIE: u1 = 0x0,
        padding: u25 = 0,
    }),
    /// Configuration Register
    /// offset: 0x0c
    CFGR: mmio.Mmio(packed struct(u32) {
        /// Clock selector
        CKSEL: u1 = 0x0,
        /// Clock Polarity
        CKPOL: u2 = 0x0,
        /// Configurable digital filter for external clock
        CKFLT: u2 = 0x0,
        reserved6: u1 = 0,
        /// Configurable digital filter for trigger
        TRGFLT: u2 = 0x0,
        reserved9: u1 = 0,
        /// Clock prescaler
        PRESC: u3 = 0x0,
        reserved13: u1 = 0,
        /// Trigger selector
        TRIGSEL: u3 = 0x0,
        reserved17: u1 = 0,
        /// Trigger enable and polarity
        TRIGEN: u2 = 0x0,
        /// Timeout enable
        TIMOUT: u1 = 0x0,
        /// Waveform shape
        WAVE: u1 = 0x0,
        /// Waveform shape polarity
        WAVPOL: u1 = 0x0,
        /// Registers update mode
        PRELOAD: u1 = 0x0,
        /// counter mode enabled
        COUNTMODE: u1 = 0x0,
        /// Encoder mode enable
        ENC: u1 = 0x0,
        padding: u7 = 0,
    }),
    /// Control Register
    /// offset: 0x10
    CR: mmio.Mmio(packed struct(u32) {
        /// LPTIM Enable
        ENABLE: u1 = 0x0,
        /// LPTIM start in single mode
        SNGSTRT: u1 = 0x0,
        /// Timer start in continuous mode
        CNTSTRT: u1 = 0x0,
        /// Counter reset
        COUNTRST: u1 = 0x0,
        /// Reset after read enable
        RSTARE: u1 = 0x0,
        padding: u27 = 0,
    }),
    /// Compare Register
    /// offset: 0x14
    CMP: mmio.Mmio(packed struct(u32) {
        /// Compare value
        CMP: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// Autoreload Register
    /// offset: 0x18
    ARR: mmio.Mmio(packed struct(u32) {
        /// Auto reload value
        ARR: u16 = 0x1,
        padding: u16 = 0,
    }),
    /// Counter Register
    /// offset: 0x1c
    CNT: mmio.Mmio(packed struct(u32) {
        /// Counter value
        CNT: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x20
    reserved32: [4]u8,
    /// LPTIM configuration register 2
    /// offset: 0x24
    CFGR2: mmio.Mmio(packed struct(u32) {
        /// LPTIMx Input 1 selection
        IN1SEL: u2 = 0x0,
        reserved4: u2 = 0,
        /// LPTIM1 Input 2 selection
        IN2SEL: u2 = 0x0,
        padding: u26 = 0,
    }),
};
