// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Universal synchronous asynchronous receiver transmitter
pub const LPUART = extern struct {
    /// Control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// USART enable
        UE: u1 = 0x0,
        /// USART enable in Stop mode
        UESM: u1 = 0x0,
        /// Receiver enable
        RE: u1 = 0x0,
        /// Transmitter enable
        TE: u1 = 0x0,
        /// IDLE interrupt enable
        IDLEIE: u1 = 0x0,
        /// RXNE interrupt enable
        RXNEIE: u1 = 0x0,
        /// Transmission complete interrupt enable
        TCIE: u1 = 0x0,
        /// interrupt enable
        TXEIE: u1 = 0x0,
        /// PE interrupt enable
        PEIE: u1 = 0x0,
        /// Parity selection
        PS: u1 = 0x0,
        /// Parity control enable
        PCE: u1 = 0x0,
        /// Receiver wakeup method
        WAKE: u1 = 0x0,
        /// Word length
        M0: u1 = 0x0,
        /// Mute mode enable
        MME: u1 = 0x0,
        /// Character match interrupt enable
        CMIE: u1 = 0x0,
        reserved16: u1 = 0,
        /// DEDT0
        DEDT0: u5 = 0x0,
        /// DEAT0
        DEAT: u5 = 0x0,
        reserved28: u2 = 0,
        /// Word length
        M1: u1 = 0x0,
        /// FIFO mode enable
        FIFOEN: u1 = 0x0,
        /// TXFIFO empty interrupt enable
        TXFEIE: u1 = 0x0,
        /// RXFIFO Full interrupt enable
        RXFFIE: u1 = 0x0,
    }),
    /// Control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        reserved4: u4 = 0,
        /// 7-bit Address Detection/4-bit Address Detection
        ADDM7: u1 = 0x0,
        reserved12: u7 = 0,
        /// STOP bits
        STOP: u2 = 0x0,
        reserved15: u1 = 0,
        /// Swap TX/RX pins
        SWAP: u1 = 0x0,
        /// RX pin active level inversion
        RXINV: u1 = 0x0,
        /// TX pin active level inversion
        TXINV: u1 = 0x0,
        /// Binary data inversion
        TAINV: u1 = 0x0,
        /// Most significant bit first
        MSBFIRST: u1 = 0x0,
        reserved24: u4 = 0,
        /// Address of the USART node
        ADD0_3: u4 = 0x0,
        /// Address of the USART node
        ADD4_7: u4 = 0x0,
    }),
    /// Control register 3
    /// offset: 0x08
    CR3: mmio.Mmio(packed struct(u32) {
        /// Error interrupt enable
        EIE: u1 = 0x0,
        reserved3: u2 = 0,
        /// Half-duplex selection
        HDSEL: u1 = 0x0,
        reserved6: u2 = 0,
        /// DMA enable receiver
        DMAR: u1 = 0x0,
        /// DMA enable transmitter
        DMAT: u1 = 0x0,
        /// RTS enable
        RTSE: u1 = 0x0,
        /// CTS enable
        CTSE: u1 = 0x0,
        /// CTS interrupt enable
        CTSIE: u1 = 0x0,
        reserved12: u1 = 0,
        /// Overrun Disable
        OVRDIS: u1 = 0x0,
        /// DMA Disable on Reception Error
        DDRE: u1 = 0x0,
        /// Driver enable mode
        DEM: u1 = 0x0,
        /// Driver enable polarity selection
        DEP: u1 = 0x0,
        reserved20: u4 = 0,
        /// Wakeup from Stop mode interrupt flag selection
        WUS: u2 = 0x0,
        /// Wakeup from Stop mode interrupt enable
        WUFIE: u1 = 0x0,
        /// threshold interrupt enable
        TXFTIE: u1 = 0x0,
        reserved25: u1 = 0,
        /// Receive FIFO threshold configuration
        RXFTCFG: u3 = 0x0,
        /// RXFIFO threshold interrupt enable
        RXFTIE: u1 = 0x0,
        /// TXFIFO threshold configuration
        TXFTCFG: u3 = 0x0,
    }),
    /// Baud rate register
    /// offset: 0x0c
    BRR: mmio.Mmio(packed struct(u32) {
        /// BRR
        BRR: u20 = 0x0,
        padding: u12 = 0,
    }),
    /// offset: 0x10
    reserved16: [8]u8,
    /// Request register
    /// offset: 0x18
    RQR: mmio.Mmio(packed struct(u32) {
        /// Auto baud rate request
        ABRRQ: u1 = 0x0,
        /// Send break request
        SBKRQ: u1 = 0x0,
        /// Mute mode request
        MMRQ: u1 = 0x0,
        /// Receive data flush request
        RXFRQ: u1 = 0x0,
        /// Transmit data flush request
        TXFRQ: u1 = 0x0,
        padding: u27 = 0,
    }),
    /// Interrupt & status register
    /// offset: 0x1c
    ISR: mmio.Mmio(packed struct(u32) {
        /// PE
        PE: u1 = 0x0,
        /// FE
        FE: u1 = 0x0,
        /// NF
        NF: u1 = 0x0,
        /// ORE
        ORE: u1 = 0x0,
        /// IDLE
        IDLE: u1 = 0x0,
        /// RXNE
        RXNE: u1 = 0x0,
        /// TC
        TC: u1 = 0x1,
        /// TXE
        TXE: u1 = 0x1,
        reserved9: u1 = 0,
        /// CTSIF
        CTSIF: u1 = 0x0,
        /// CTS
        CTS: u1 = 0x0,
        reserved16: u5 = 0,
        /// BUSY
        BUSY: u1 = 0x0,
        /// CMF
        CMF: u1 = 0x0,
        /// SBKF
        SBKF: u1 = 0x0,
        /// RWU
        RWU: u1 = 0x0,
        /// WUF
        WUF: u1 = 0x0,
        /// TEACK
        TEACK: u1 = 0x0,
        /// REACK
        REACK: u1 = 0x0,
        /// TXFIFO Empty
        TXFE: u1 = 0x0,
        /// RXFIFO Full
        RXFF: u1 = 0x0,
        reserved26: u1 = 0,
        /// RXFIFO threshold flag
        RXFT: u1 = 0x0,
        /// TXFIFO threshold flag
        TXFT: u1 = 0x0,
        padding: u4 = 0,
    }),
    /// Interrupt flag clear register
    /// offset: 0x20
    ICR: mmio.Mmio(packed struct(u32) {
        /// Parity error clear flag
        PECF: u1 = 0x0,
        /// Framing error clear flag
        FECF: u1 = 0x0,
        /// Noise detected clear flag
        NCF: u1 = 0x0,
        /// Overrun error clear flag
        ORECF: u1 = 0x0,
        /// Idle line detected clear flag
        IDLECF: u1 = 0x0,
        reserved6: u1 = 0,
        /// Transmission complete clear flag
        TCCF: u1 = 0x0,
        reserved9: u2 = 0,
        /// CTS clear flag
        CTSCF: u1 = 0x0,
        reserved17: u7 = 0,
        /// Character match clear flag
        CMCF: u1 = 0x0,
        reserved20: u2 = 0,
        /// Wakeup from Stop mode clear flag
        WUCF: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// Receive data register
    /// offset: 0x24
    RDR: mmio.Mmio(packed struct(u32) {
        /// Receive data value
        RDR: u9 = 0x0,
        padding: u23 = 0,
    }),
    /// Transmit data register
    /// offset: 0x28
    TDR: mmio.Mmio(packed struct(u32) {
        /// Transmit data value
        TDR: u9 = 0x0,
        padding: u23 = 0,
    }),
    /// Prescaler register
    /// offset: 0x2c
    PRESC: mmio.Mmio(packed struct(u32) {
        /// Clock prescaler
        PRESCALER: u4 = 0x0,
        padding: u28 = 0,
    }),
    /// offset: 0x30
    reserved48: [956]u8,
    /// LPUART Hardware Configuration register 2
    /// offset: 0x3ec
    HWCFGR2: mmio.Mmio(packed struct(u32) {
        /// LUART hardware configuration 1
        CFG1: u4 = 0x3,
        /// LUART hardware configuration 2
        CFG2: u4 = 0x1,
        padding: u24 = 0,
    }),
    /// LPUART Hardware Configuration register 1
    /// offset: 0x3f0
    HWCFGR1: mmio.Mmio(packed struct(u32) {
        /// LUART hardware configuration 1
        CFG1: u4 = 0x0,
        /// LUART hardware configuration 2
        CFG2: u4 = 0x0,
        /// LUART hardware configuration 1
        CFG3: u4 = 0x0,
        /// LUART hardware configuration 2
        CFG4: u4 = 0x0,
        /// LUART hardware configuration 2
        CFG5: u4 = 0x0,
        /// LUART hardware configuration 2
        CFG6: u4 = 0x1,
        /// LUART hardware configuration 2
        CFG7: u4 = 0x1,
        /// LUART hardware configuration 2
        CFG8: u4 = 0x3,
    }),
    /// EXTI IP Version register
    /// offset: 0x3f4
    VERR: mmio.Mmio(packed struct(u32) {
        /// Minor Revision number
        MINREV: u4 = 0x3,
        /// Major Revision number
        MAJREV: u4 = 0x2,
        padding: u24 = 0,
    }),
    /// EXTI Identification register
    /// offset: 0x3f8
    IPIDR: mmio.Mmio(packed struct(u32) {
        /// IP Identification
        IPID: u32 = 0x130003,
    }),
    /// EXTI Size ID register
    /// offset: 0x3fc
    SIDR: mmio.Mmio(packed struct(u32) {
        /// Size Identification
        SID: u32 = 0xA3C5DD01,
    }),
};
