// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Power control
pub const PWR = extern struct {
    /// Power control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Low-power mode selection
        LPMS: u3 = 0x0,
        /// Flash memory powered down during Stop mode
        FPD_STOP: u1 = 0x0,
        /// Flash memory powered down during Low-power run mode
        FPD_LPRUN: u1 = 0x0,
        /// Flash memory powered down during Low-power sleep mode
        FPD_LPSLP: u1 = 0x0,
        reserved8: u2 = 0,
        /// Disable backup domain write protection
        DBP: u1 = 0x0,
        /// Voltage scaling range selection
        VOS: u2 = 0x1,
        reserved14: u3 = 0,
        /// Low-power run
        LPR: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// Power control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Power voltage detector enable
        PVDE: u1 = 0x0,
        /// Power voltage detector falling threshold selection
        PVDFT: u3 = 0x0,
        /// Power voltage detector rising threshold selection
        PVDRT: u3 = 0x0,
        padding: u25 = 0,
    }),
    /// Power control register 3
    /// offset: 0x08
    CR3: mmio.Mmio(packed struct(u32) {
        /// Enable Wakeup pin WKUP1
        EWUP1: u1 = 0x0,
        /// Enable Wakeup pin WKUP2
        EWUP2: u1 = 0x0,
        reserved3: u1 = 0,
        /// Enable Wakeup pin WKUP4
        EWUP4: u1 = 0x0,
        /// Enable WKUP5 wakeup pin
        EWUP5: u1 = 0x0,
        /// Enable WKUP6 wakeup pin
        EWUP6: u1 = 0x0,
        reserved8: u2 = 0,
        /// SRAM retention in Standby mode
        RRS: u1 = 0x0,
        /// Enable the periodical sampling mode for PDR detection
        ULPEN: u1 = 0x0,
        /// Apply pull-up and pull-down configuration
        APC: u1 = 0x0,
        reserved15: u4 = 0,
        /// Enable internal wakeup line
        EIWUL: u1 = 0x1,
        padding: u16 = 0,
    }),
    /// Power control register 4
    /// offset: 0x0c
    CR4: mmio.Mmio(packed struct(u32) {
        /// Wakeup pin WKUP1 polarity
        WP1: u1 = 0x0,
        /// Wakeup pin WKUP2 polarity
        WP2: u1 = 0x0,
        reserved3: u1 = 0,
        /// Wakeup pin WKUP4 polarity
        WP4: u1 = 0x0,
        /// Wakeup pin WKUP5 polarity
        WP5: u1 = 0x0,
        /// WKUP6 wakeup pin polarity
        WP6: u1 = 0x0,
        reserved8: u2 = 0,
        /// VBAT battery charging enable
        VBE: u1 = 0x0,
        /// VBAT battery charging resistor selection
        VBRS: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// Power status register 1
    /// offset: 0x10
    SR1: mmio.Mmio(packed struct(u32) {
        /// Wakeup flag 1
        WUF1: u1 = 0x0,
        /// Wakeup flag 2
        WUF2: u1 = 0x0,
        reserved3: u1 = 0,
        /// Wakeup flag 4
        WUF4: u1 = 0x0,
        /// Wakeup flag 5
        WUF5: u1 = 0x0,
        /// Wakeup flag 6
        WUF6: u1 = 0x0,
        reserved8: u2 = 0,
        /// Standby flag
        SBF: u1 = 0x0,
        reserved15: u6 = 0,
        /// Wakeup flag internal
        WUFI: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power status register 2
    /// offset: 0x14
    SR2: mmio.Mmio(packed struct(u32) {
        reserved7: u7 = 0,
        /// Flash ready flag
        FLASH_RDY: u1 = 0x0,
        /// Low-power regulator started
        REGLPS: u1 = 0x0,
        /// Low-power regulator flag
        REGLPF: u1 = 0x0,
        /// Voltage scaling flag
        VOSF: u1 = 0x0,
        /// Power voltage detector output
        PVDO: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// Power status clear register
    /// offset: 0x18
    SCR: mmio.Mmio(packed struct(u32) {
        /// Clear wakeup flag 1
        CWUF1: u1 = 0x0,
        /// Clear wakeup flag 2
        CWUF2: u1 = 0x0,
        reserved3: u1 = 0,
        /// Clear wakeup flag 4
        CWUF4: u1 = 0x0,
        /// Clear wakeup flag 5
        CWUF5: u1 = 0x0,
        /// Clear wakeup flag 6
        CWUF6: u1 = 0x0,
        reserved8: u2 = 0,
        /// Clear standby flag
        CSBF: u1 = 0x0,
        padding: u23 = 0,
    }),
    /// offset: 0x1c
    reserved28: [4]u8,
    /// Power Port A pull-up control register
    /// offset: 0x20
    PUCRA: mmio.Mmio(packed struct(u32) {
        /// Port A pull-up bit y (y=0..15)
        PU0: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU1: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU2: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU3: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU4: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU5: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU6: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU7: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU8: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU9: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU10: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU11: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU12: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU13: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU14: u1 = 0x0,
        /// Port A pull-up bit y (y=0..15)
        PU15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port A pull-down control register
    /// offset: 0x24
    PDCRA: mmio.Mmio(packed struct(u32) {
        /// Port A pull-down bit y (y=0..15)
        PD0: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD1: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD2: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD3: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD4: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD5: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD6: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD7: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD8: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD9: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD10: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD11: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD12: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD13: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD14: u1 = 0x0,
        /// Port A pull-down bit y (y=0..15)
        PD15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port B pull-up control register
    /// offset: 0x28
    PUCRB: mmio.Mmio(packed struct(u32) {
        /// Port B pull-up bit y (y=0..15)
        PU0: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU1: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU2: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU3: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU4: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU5: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU6: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU7: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU8: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU9: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU10: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU11: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU12: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU13: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU14: u1 = 0x0,
        /// Port B pull-up bit y (y=0..15)
        PU15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port B pull-down control register
    /// offset: 0x2c
    PDCRB: mmio.Mmio(packed struct(u32) {
        /// Port B pull-down bit y (y=0..15)
        PD0: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD1: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD2: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD3: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD4: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD5: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD6: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD7: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD8: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD9: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD10: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD11: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD12: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD13: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD14: u1 = 0x0,
        /// Port B pull-down bit y (y=0..15)
        PD15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port C pull-up control register
    /// offset: 0x30
    PUCRC: mmio.Mmio(packed struct(u32) {
        /// Port C pull-up bit y (y=0..15)
        PU0: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU1: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU2: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU3: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU4: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU5: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU6: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU7: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU8: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU9: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU10: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU11: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU12: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU13: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU14: u1 = 0x0,
        /// Port C pull-up bit y (y=0..15)
        PU15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port C pull-down control register
    /// offset: 0x34
    PDCRC: mmio.Mmio(packed struct(u32) {
        /// Port C pull-down bit y (y=0..15)
        PD0: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD1: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD2: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD3: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD4: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD5: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD6: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD7: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD8: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD9: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD10: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD11: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD12: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD13: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD14: u1 = 0x0,
        /// Port C pull-down bit y (y=0..15)
        PD15: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// Power Port D pull-up control register
    /// offset: 0x38
    PUCRD: mmio.Mmio(packed struct(u32) {
        /// Port D pull-up bit y (y=0..15)
        PU0: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU1: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU2: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU3: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU4: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU5: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU6: u1 = 0x0,
        reserved8: u1 = 0,
        /// Port D pull-up bit y (y=0..15)
        PU8: u1 = 0x0,
        /// Port D pull-up bit y (y=0..15)
        PU9: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// Power Port D pull-down control register
    /// offset: 0x3c
    PDCRD: mmio.Mmio(packed struct(u32) {
        /// Port D pull-down bit y (y=0..15)
        PD0: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD1: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD2: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD3: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD4: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD5: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD6: u1 = 0x0,
        reserved8: u1 = 0,
        /// Port D pull-down bit y (y=0..15)
        PD8: u1 = 0x0,
        /// Port D pull-down bit y (y=0..15)
        PD9: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// offset: 0x40
    reserved64: [8]u8,
    /// Power Port F pull-up control register
    /// offset: 0x48
    PUCRF: mmio.Mmio(packed struct(u32) {
        /// Port F pull-up bit y (y=0..15)
        PU0: u1 = 0x0,
        /// Port F pull-up bit y (y=0..15)
        PU1: u1 = 0x0,
        /// Port F pull-up bit y (y=0..15)
        PU2: u1 = 0x0,
        padding: u29 = 0,
    }),
    /// Power Port F pull-down control register
    /// offset: 0x4c
    PDCRF: mmio.Mmio(packed struct(u32) {
        /// Port F pull-down bit y (y=0..15)
        PD0: u1 = 0x0,
        /// Port F pull-down bit y (y=0..15)
        PD1: u1 = 0x0,
        /// Port F pull-down bit y (y=0..15)
        PD2: u1 = 0x0,
        padding: u29 = 0,
    }),
};
