// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Reset and clock control
pub const RCC = extern struct {
    /// Clock control register
    /// offset: 0x00
    CR: mmio.Mmio(packed struct(u32) {
        reserved8: u8 = 0,
        /// HSI16 clock enable
        HSION: u1 = 0x0,
        /// HSI16 always enable for peripheral kernels
        HSIKERON: u1 = 0x0,
        /// HSI16 clock ready flag
        HSIRDY: u1 = 0x0,
        /// HSI16 clock division factor
        HSIDIV: u3 = 0x0,
        reserved16: u2 = 0,
        /// HSE clock enable
        HSEON: u1 = 0x0,
        /// HSE clock ready flag
        HSERDY: u1 = 0x0,
        /// HSE crystal oscillator bypass
        HSEBYP: u1 = 0x0,
        /// Clock security system enable
        CSSON: u1 = 0x0,
        reserved24: u4 = 0,
        /// PLL enable
        PLLON: u1 = 0x0,
        /// PLL clock ready flag
        PLLRDY: u1 = 0x0,
        padding: u6 = 0,
    }),
    /// Internal clock sources calibration register
    /// offset: 0x04
    ICSCR: mmio.Mmio(packed struct(u32) {
        /// HSI16 clock calibration
        HSICAL: u8 = 0x0,
        /// HSI16 clock trimming
        HSITRIM: u7 = 0x0,
        padding: u17 = 0,
    }),
    /// Clock configuration register
    /// offset: 0x08
    CFGR: mmio.Mmio(packed struct(u32) {
        /// System clock switch
        SW: u3 = 0x0,
        /// System clock switch status
        SWS: u3 = 0x0,
        reserved8: u2 = 0,
        /// AHB prescaler
        HPRE: u4 = 0x0,
        /// APB prescaler
        PPRE: u3 = 0x0,
        reserved24: u9 = 0,
        /// Microcontroller clock output
        MCOSEL: u3 = 0x0,
        reserved28: u1 = 0,
        /// Microcontroller clock output prescaler
        MCOPRE: u3 = 0x0,
        padding: u1 = 0,
    }),
    /// PLL configuration register
    /// offset: 0x0c
    PLLSYSCFGR: mmio.Mmio(packed struct(u32) {
        /// PLL input clock source
        PLLSRC: u2 = 0x0,
        reserved4: u2 = 0,
        /// Division factor M of the PLL input clock divider
        PLLM: u3 = 0x0,
        reserved8: u1 = 0,
        /// PLL frequency multiplication factor N
        PLLN: u7 = 0x10,
        reserved16: u1 = 0,
        /// PLLPCLK clock output enable
        PLLPEN: u1 = 0x0,
        /// PLL VCO division factor P for PLLPCLK clock output
        PLLP: u5 = 0x0,
        reserved24: u2 = 0,
        /// PLLQCLK clock output enable
        PLLQEN: u1 = 0x0,
        /// PLL VCO division factor Q for PLLQCLK clock output
        PLLQ: u3 = 0x0,
        /// PLLRCLK clock output enable
        PLLREN: u1 = 0x0,
        /// PLL VCO division factor R for PLLRCLK clock output
        PLLR: u3 = 0x0,
    }),
    /// offset: 0x10
    reserved16: [8]u8,
    /// Clock interrupt enable register
    /// offset: 0x18
    CIER: mmio.Mmio(packed struct(u32) {
        /// LSI ready interrupt enable
        LSIRDYIE: u1 = 0x0,
        /// LSE ready interrupt enable
        LSERDYIE: u1 = 0x0,
        reserved3: u1 = 0,
        /// HSI ready interrupt enable
        HSIRDYIE: u1 = 0x0,
        /// HSE ready interrupt enable
        HSERDYIE: u1 = 0x0,
        /// PLL ready interrupt enable
        PLLSYSRDYIE: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// Clock interrupt flag register
    /// offset: 0x1c
    CIFR: mmio.Mmio(packed struct(u32) {
        /// LSI ready interrupt flag
        LSIRDYF: u1 = 0x0,
        /// LSE ready interrupt flag
        LSERDYF: u1 = 0x0,
        reserved3: u1 = 0,
        /// HSI ready interrupt flag
        HSIRDYF: u1 = 0x0,
        /// HSE ready interrupt flag
        HSERDYF: u1 = 0x0,
        /// PLL ready interrupt flag
        PLLSYSRDYF: u1 = 0x0,
        reserved8: u2 = 0,
        /// Clock security system interrupt flag
        CSSF: u1 = 0x0,
        /// LSE Clock security system interrupt flag
        LSECSSF: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// Clock interrupt clear register
    /// offset: 0x20
    CICR: mmio.Mmio(packed struct(u32) {
        /// LSI ready interrupt clear
        LSIRDYC: u1 = 0x0,
        /// LSE ready interrupt clear
        LSERDYC: u1 = 0x0,
        reserved3: u1 = 0,
        /// HSI ready interrupt clear
        HSIRDYC: u1 = 0x0,
        /// HSE ready interrupt clear
        HSERDYC: u1 = 0x0,
        /// PLL ready interrupt clear
        PLLSYSRDYC: u1 = 0x0,
        reserved8: u2 = 0,
        /// Clock security system interrupt clear
        CSSC: u1 = 0x0,
        /// LSE Clock security system interrupt clear
        LSECSSC: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// GPIO reset register
    /// offset: 0x24
    IOPRSTR: mmio.Mmio(packed struct(u32) {
        /// I/O port A reset
        IOPARST: u1 = 0x0,
        /// I/O port B reset
        IOPBRST: u1 = 0x0,
        /// I/O port C reset
        IOPCRST: u1 = 0x0,
        /// I/O port D reset
        IOPDRST: u1 = 0x0,
        reserved5: u1 = 0,
        /// I/O port F reset
        IOPFRST: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// AHB peripheral reset register
    /// offset: 0x28
    AHBRSTR: mmio.Mmio(packed struct(u32) {
        /// DMA1 reset
        DMARST: u1 = 0x0,
        reserved8: u7 = 0,
        /// FLITF reset
        FLASHRST: u1 = 0x0,
        reserved12: u3 = 0,
        /// CRC reset
        CRCRST: u1 = 0x0,
        reserved16: u3 = 0,
        /// AES hardware accelerator reset
        AESRST: u1 = 0x0,
        reserved18: u1 = 0,
        /// Random number generator reset
        RNGRST: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// APB peripheral reset register 1
    /// offset: 0x2c
    APBRSTR1: mmio.Mmio(packed struct(u32) {
        /// TIM2 timer reset
        TIM2RST: u1 = 0x0,
        /// TIM3 timer reset
        TIM3RST: u1 = 0x0,
        reserved4: u2 = 0,
        /// TIM6 timer reset
        TIM6RST: u1 = 0x0,
        /// TIM7 timer reset
        TIM7RST: u1 = 0x0,
        reserved14: u8 = 0,
        /// SPI2 reset
        SPI2RST: u1 = 0x0,
        reserved17: u2 = 0,
        /// USART2 reset
        USART2RST: u1 = 0x0,
        /// USART3 reset
        USART3RST: u1 = 0x0,
        /// USART4 reset
        USART4RST: u1 = 0x0,
        /// LPUART1 reset
        LPUART1RST: u1 = 0x0,
        /// I2C1 reset
        I2C1RST: u1 = 0x0,
        /// I2C2 reset
        I2C2RST: u1 = 0x0,
        reserved24: u1 = 0,
        /// HDMI CEC reset
        CECRST: u1 = 0x0,
        /// UCPD1 reset
        UCPD1RST: u1 = 0x0,
        /// UCPD2 reset
        UCPD2RST: u1 = 0x0,
        /// Debug support reset
        DBGRST: u1 = 0x0,
        /// Power interface reset
        PWRRST: u1 = 0x0,
        /// DAC1 interface reset
        DAC1RST: u1 = 0x0,
        /// Low Power Timer 2 reset
        LPTIM2RST: u1 = 0x0,
        /// Low Power Timer 1 reset
        LPTIM1RST: u1 = 0x0,
    }),
    /// APB peripheral reset register 2
    /// offset: 0x30
    APBRSTR2: mmio.Mmio(packed struct(u32) {
        /// SYSCFG, COMP and VREFBUF reset
        SYSCFGRST: u1 = 0x0,
        reserved11: u10 = 0,
        /// TIM1 timer reset
        TIM1RST: u1 = 0x0,
        /// SPI1 reset
        SPI1RST: u1 = 0x0,
        reserved14: u1 = 0,
        /// USART1 reset
        USART1RST: u1 = 0x0,
        /// TIM14 timer reset
        TIM14RST: u1 = 0x0,
        /// TIM15 timer reset
        TIM15RST: u1 = 0x0,
        /// TIM16 timer reset
        TIM16RST: u1 = 0x0,
        /// TIM17 timer reset
        TIM17RST: u1 = 0x0,
        reserved20: u1 = 0,
        /// ADC reset
        ADCRST: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// GPIO clock enable register
    /// offset: 0x34
    IOPENR: mmio.Mmio(packed struct(u32) {
        /// I/O port A clock enable
        IOPAEN: u1 = 0x0,
        /// I/O port B clock enable
        IOPBEN: u1 = 0x0,
        /// I/O port C clock enable
        IOPCEN: u1 = 0x0,
        /// I/O port D clock enable
        IOPDEN: u1 = 0x0,
        reserved5: u1 = 0,
        /// I/O port F clock enable
        IOPFEN: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// AHB peripheral clock enable register
    /// offset: 0x38
    AHBENR: mmio.Mmio(packed struct(u32) {
        /// DMA clock enable
        DMAEN: u1 = 0x0,
        reserved8: u7 = 0,
        /// Flash memory interface clock enable
        FLASHEN: u1 = 0x0,
        reserved12: u3 = 0,
        /// CRC clock enable
        CRCEN: u1 = 0x0,
        reserved16: u3 = 0,
        /// AES hardware accelerator
        AESEN: u1 = 0x0,
        reserved18: u1 = 0,
        /// Random number generator clock enable
        RNGEN: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// APB peripheral clock enable register 1
    /// offset: 0x3c
    APBENR1: mmio.Mmio(packed struct(u32) {
        /// TIM2 timer clock enable
        TIM2EN: u1 = 0x0,
        /// TIM3 timer clock enable
        TIM3EN: u1 = 0x0,
        reserved4: u2 = 0,
        /// TIM6 timer clock enable
        TIM6EN: u1 = 0x0,
        /// TIM7 timer clock enable
        TIM7EN: u1 = 0x0,
        reserved10: u4 = 0,
        /// RTC APB clock enable
        RTCAPBEN: u1 = 0x0,
        /// WWDG clock enable
        WWDGEN: u1 = 0x0,
        reserved14: u2 = 0,
        /// SPI2 clock enable
        SPI2EN: u1 = 0x0,
        reserved17: u2 = 0,
        /// USART2 clock enable
        USART2EN: u1 = 0x0,
        /// USART3 clock enable
        USART3EN: u1 = 0x0,
        /// USART4 clock enable
        USART4EN: u1 = 0x0,
        /// LPUART1 clock enable
        LPUART1EN: u1 = 0x0,
        /// I2C1 clock enable
        I2C1EN: u1 = 0x0,
        /// I2C2 clock enable
        I2C2EN: u1 = 0x0,
        reserved24: u1 = 0,
        /// HDMI CEC clock enable
        CECEN: u1 = 0x0,
        /// UCPD1 clock enable
        UCPD1EN: u1 = 0x0,
        /// UCPD2 clock enable
        UCPD2EN: u1 = 0x0,
        /// Debug support clock enable
        DBGEN: u1 = 0x0,
        /// Power interface clock enable
        PWREN: u1 = 0x0,
        /// DAC1 interface clock enable
        DAC1EN: u1 = 0x0,
        /// LPTIM2 clock enable
        LPTIM2EN: u1 = 0x0,
        /// LPTIM1 clock enable
        LPTIM1EN: u1 = 0x0,
    }),
    /// APB peripheral clock enable register 2
    /// offset: 0x40
    APBENR2: mmio.Mmio(packed struct(u32) {
        /// SYSCFG, COMP and VREFBUF clock enable
        SYSCFGEN: u1 = 0x0,
        reserved11: u10 = 0,
        /// TIM1 timer clock enable
        TIM1EN: u1 = 0x0,
        /// SPI1 clock enable
        SPI1EN: u1 = 0x0,
        reserved14: u1 = 0,
        /// USART1 clock enable
        USART1EN: u1 = 0x0,
        /// TIM14 timer clock enable
        TIM14EN: u1 = 0x0,
        /// TIM15 timer clock enable
        TIM15EN: u1 = 0x0,
        /// TIM16 timer clock enable
        TIM16EN: u1 = 0x0,
        /// TIM16 timer clock enable
        TIM17EN: u1 = 0x0,
        reserved20: u1 = 0,
        /// ADC clock enable
        ADCEN: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// GPIO in Sleep mode clock enable register
    /// offset: 0x44
    IOPSMENR: mmio.Mmio(packed struct(u32) {
        /// I/O port A clock enable during Sleep mode
        IOPASMEN: u1 = 0x0,
        /// I/O port B clock enable during Sleep mode
        IOPBSMEN: u1 = 0x0,
        /// I/O port C clock enable during Sleep mode
        IOPCSMEN: u1 = 0x0,
        /// I/O port D clock enable during Sleep mode
        IOPDSMEN: u1 = 0x0,
        reserved5: u1 = 0,
        /// I/O port F clock enable during Sleep mode
        IOPFSMEN: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// AHB peripheral clock enable in Sleep mode register
    /// offset: 0x48
    AHBSMENR: mmio.Mmio(packed struct(u32) {
        /// DMA clock enable during Sleep mode
        DMASMEN: u1 = 0x0,
        reserved8: u7 = 0,
        /// Flash memory interface clock enable during Sleep mode
        FLASHSMEN: u1 = 0x0,
        /// SRAM clock enable during Sleep mode
        SRAMSMEN: u1 = 0x0,
        reserved12: u2 = 0,
        /// CRC clock enable during Sleep mode
        CRCSMEN: u1 = 0x0,
        reserved16: u3 = 0,
        /// AES hardware accelerator clock enable during Sleep mode
        AESSMEN: u1 = 0x0,
        reserved18: u1 = 0,
        /// Random number generator clock enable during Sleep mode
        RNGSMEN: u1 = 0x0,
        padding: u13 = 0,
    }),
    /// APB peripheral clock enable in Sleep mode register 1
    /// offset: 0x4c
    APBSMENR1: mmio.Mmio(packed struct(u32) {
        /// TIM2 timer clock enable during Sleep mode
        TIM2SMEN: u1 = 0x0,
        /// TIM3 timer clock enable during Sleep mode
        TIM3SMEN: u1 = 0x0,
        reserved4: u2 = 0,
        /// TIM6 timer clock enable during Sleep mode
        TIM6SMEN: u1 = 0x0,
        /// TIM7 timer clock enable during Sleep mode
        TIM7SMEN: u1 = 0x0,
        reserved10: u4 = 0,
        /// RTC APB clock enable during Sleep mode
        RTCAPBSMEN: u1 = 0x0,
        /// WWDG clock enable during Sleep mode
        WWDGSMEN: u1 = 0x0,
        reserved14: u2 = 0,
        /// SPI2 clock enable during Sleep mode
        SPI2SMEN: u1 = 0x0,
        reserved17: u2 = 0,
        /// USART2 clock enable during Sleep mode
        USART2SMEN: u1 = 0x0,
        /// USART3 clock enable during Sleep mode
        USART3SMEN: u1 = 0x0,
        /// USART4 clock enable during Sleep mode
        USART4SMEN: u1 = 0x0,
        /// LPUART1 clock enable during Sleep mode
        LPUART1SMEN: u1 = 0x0,
        /// I2C1 clock enable during Sleep mode
        I2C1SMEN: u1 = 0x0,
        /// I2C2 clock enable during Sleep mode
        I2C2SMEN: u1 = 0x0,
        reserved24: u1 = 0,
        /// HDMI CEC clock enable during Sleep mode
        CECSMEN: u1 = 0x0,
        /// UCPD1 clock enable during Sleep mode
        UCPD1SMEN: u1 = 0x0,
        /// UCPD2 clock enable during Sleep mode
        UCPD2SMEN: u1 = 0x0,
        /// Debug support clock enable during Sleep mode
        DBGSMEN: u1 = 0x0,
        /// Power interface clock enable during Sleep mode
        PWRSMEN: u1 = 0x0,
        /// DAC1 interface clock enable during Sleep mode
        DAC1SMEN: u1 = 0x0,
        /// Low Power Timer 2 clock enable during Sleep mode
        LPTIM2SMEN: u1 = 0x0,
        /// Low Power Timer 1 clock enable during Sleep mode
        LPTIM1SMEN: u1 = 0x0,
    }),
    /// APB peripheral clock enable in Sleep mode register 2
    /// offset: 0x50
    APBSMENR2: mmio.Mmio(packed struct(u32) {
        /// SYSCFG, COMP and VREFBUF clock enable during Sleep mode
        SYSCFGSMEN: u1 = 0x0,
        reserved11: u10 = 0,
        /// TIM1 timer clock enable during Sleep mode
        TIM1SMEN: u1 = 0x0,
        /// SPI1 clock enable during Sleep mode
        SPI1SMEN: u1 = 0x0,
        reserved14: u1 = 0,
        /// USART1 clock enable during Sleep mode
        USART1SMEN: u1 = 0x0,
        /// TIM14 timer clock enable during Sleep mode
        TIM14SMEN: u1 = 0x0,
        /// TIM15 timer clock enable during Sleep mode
        TIM15SMEN: u1 = 0x0,
        /// TIM16 timer clock enable during Sleep mode
        TIM16SMEN: u1 = 0x0,
        /// TIM16 timer clock enable during Sleep mode
        TIM17SMEN: u1 = 0x0,
        reserved20: u1 = 0,
        /// ADC clock enable during Sleep mode
        ADCSMEN: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// Peripherals independent clock configuration register
    /// offset: 0x54
    CCIPR: mmio.Mmio(packed struct(u32) {
        /// USART1 clock source selection
        USART1SEL: u2 = 0x0,
        /// USART2 clock source selection
        USART2SEL: u2 = 0x0,
        reserved6: u2 = 0,
        /// HDMI CEC clock source selection
        CECSEL: u1 = 0x0,
        reserved10: u3 = 0,
        /// LPUART1 clock source selection
        LPUART1SEL: u2 = 0x0,
        /// I2C1 clock source selection
        I2C1SEL: u2 = 0x0,
        /// I2S1 clock source selection
        I2S2SEL: u2 = 0x0,
        reserved18: u2 = 0,
        /// LPTIM1 clock source selection
        LPTIM1SEL: u2 = 0x0,
        /// LPTIM2 clock source selection
        LPTIM2SEL: u2 = 0x0,
        /// TIM1 clock source selection
        TIM1SEL: u1 = 0x0,
        reserved24: u1 = 0,
        /// TIM15 clock source selection
        TIM15SEL: u1 = 0x0,
        reserved26: u1 = 0,
        /// RNG clock source selection
        RNGSEL: u2 = 0x0,
        /// Division factor of RNG clock divider
        RNGDIV: u2 = 0x0,
        /// ADCs clock source selection
        ADCSEL: u2 = 0x0,
    }),
    /// offset: 0x58
    reserved88: [4]u8,
    /// RTC domain control register
    /// offset: 0x5c
    BDCR: mmio.Mmio(packed struct(u32) {
        /// LSE oscillator enable
        LSEON: u1 = 0x0,
        /// LSE oscillator ready
        LSERDY: u1 = 0x0,
        /// LSE oscillator bypass
        LSEBYP: u1 = 0x0,
        /// LSE oscillator drive capability
        LSEDRV: u2 = 0x0,
        /// CSS on LSE enable
        LSECSSON: u1 = 0x0,
        /// CSS on LSE failure Detection
        LSECSSD: u1 = 0x0,
        reserved8: u1 = 0,
        /// RTC clock source selection
        RTCSEL: u2 = 0x0,
        reserved15: u5 = 0,
        /// RTC clock enable
        RTCEN: u1 = 0x0,
        /// RTC domain software reset
        BDRST: u1 = 0x0,
        reserved24: u7 = 0,
        /// Low-speed clock output (LSCO) enable
        LSCOEN: u1 = 0x0,
        /// Low-speed clock output selection
        LSCOSEL: u1 = 0x0,
        padding: u6 = 0,
    }),
    /// Control/status register
    /// offset: 0x60
    CSR: mmio.Mmio(packed struct(u32) {
        /// LSI oscillator enable
        LSION: u1 = 0x0,
        /// LSI oscillator ready
        LSIRDY: u1 = 0x0,
        reserved23: u21 = 0,
        /// Remove reset flags
        RMVF: u1 = 0x0,
        reserved25: u1 = 0,
        /// Option byte loader reset flag
        OBLRSTF: u1 = 0x0,
        /// Pin reset flag
        PINRSTF: u1 = 0x0,
        /// BOR or POR/PDR flag
        PWRRSTF: u1 = 0x0,
        /// Software reset flag
        SFTRSTF: u1 = 0x0,
        /// Independent window watchdog reset flag
        IWDGRSTF: u1 = 0x0,
        /// Window watchdog reset flag
        WWDGRSTF: u1 = 0x0,
        /// Low-power reset flag
        LPWRRSTF: u1 = 0x0,
    }),
};
