// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Random number generator
pub const RNG = extern struct {
    /// control register
    /// offset: 0x00
    CR: mmio.Mmio(packed struct(u32) {
        reserved2: u2 = 0,
        /// Random number generator enable
        RNGEN: u1 = 0x0,
        /// Interrupt enable
        IE: u1 = 0x0,
        reserved5: u1 = 0,
        /// Clock error detection
        CED: u1 = 0x0,
        /// Bypass mode enable
        BYP: u1 = 0x0,
        padding: u25 = 0,
    }),
    /// status register
    /// offset: 0x04
    SR: mmio.Mmio(packed struct(u32) {
        /// Data ready
        DRDY: u1 = 0x0,
        /// Clock error current status
        CECS: u1 = 0x0,
        /// Seed error current status
        SECS: u1 = 0x0,
        reserved5: u2 = 0,
        /// Clock error interrupt status
        CEIS: u1 = 0x0,
        /// Seed error interrupt status
        SEIS: u1 = 0x0,
        padding: u25 = 0,
    }),
    /// data register
    /// offset: 0x08
    DR: mmio.Mmio(packed struct(u32) {
        /// Random data
        RNDATA: u32 = 0x0,
    }),
};
