// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Real-time clock
pub const RTC = extern struct {
    /// time register
    /// offset: 0x00
    TR: mmio.Mmio(packed struct(u32) {
        /// Second units in BCD format
        SU: u4 = 0x0,
        /// Second tens in BCD format
        ST: u3 = 0x0,
        reserved8: u1 = 0,
        /// Minute units in BCD format
        MNU: u4 = 0x0,
        /// Minute tens in BCD format
        MNT: u3 = 0x0,
        reserved16: u1 = 0,
        /// Hour units in BCD format
        HU: u4 = 0x0,
        /// Hour tens in BCD format
        HT: u2 = 0x0,
        /// AM/PM notation
        PM: u1 = 0x0,
        padding: u9 = 0,
    }),
    /// date register
    /// offset: 0x04
    DR: mmio.Mmio(packed struct(u32) {
        /// Date units in BCD format
        DU: u4 = 0x1,
        /// Date tens in BCD format
        DT: u2 = 0x0,
        reserved8: u2 = 0,
        /// Month units in BCD format
        MU: u4 = 0x1,
        /// Month tens in BCD format
        MT: u1 = 0x0,
        /// Week day units
        WDU: u3 = 0x1,
        /// Year units in BCD format
        YU: u4 = 0x0,
        /// Year tens in BCD format
        YT: u4 = 0x0,
        padding: u8 = 0,
    }),
    /// sub second register
    /// offset: 0x08
    SSR: mmio.Mmio(packed struct(u32) {
        /// Sub second value
        SS: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// initialization and status register
    /// offset: 0x0c
    ICSR: mmio.Mmio(packed struct(u32) {
        /// Alarm A write flag
        ALRAWF: u1 = 0x1,
        /// Alarm B write flag
        ALRBWF: u1 = 0x1,
        /// Wakeup timer write flag
        WUTWF: u1 = 0x1,
        /// Shift operation pending
        SHPF: u1 = 0x0,
        /// Initialization status flag
        INITS: u1 = 0x0,
        /// Registers synchronization flag
        RSF: u1 = 0x0,
        /// Initialization flag
        INITF: u1 = 0x0,
        /// Initialization mode
        INIT: u1 = 0x0,
        reserved16: u8 = 0,
        /// Recalibration pending Flag
        RECALPF: u1 = 0x0,
        padding: u15 = 0,
    }),
    /// prescaler register
    /// offset: 0x10
    PRER: mmio.Mmio(packed struct(u32) {
        /// Synchronous prescaler factor
        PREDIV_S: u15 = 0xFF,
        reserved16: u1 = 0,
        /// Asynchronous prescaler factor
        PREDIV_A: u7 = 0x7F,
        padding: u9 = 0,
    }),
    /// wakeup timer register
    /// offset: 0x14
    WUTR: mmio.Mmio(packed struct(u32) {
        /// Wakeup auto-reload value bits
        WUT: u16 = 0xFFFF,
        padding: u16 = 0,
    }),
    /// control register
    /// offset: 0x18
    CR: mmio.Mmio(packed struct(u32) {
        /// WUCKSEL
        WUCKSEL: u3 = 0x0,
        /// TSEDGE
        TSEDGE: u1 = 0x0,
        /// REFCKON
        REFCKON: u1 = 0x0,
        /// BYPSHAD
        BYPSHAD: u1 = 0x0,
        /// FMT
        FMT: u1 = 0x0,
        reserved8: u1 = 0,
        /// ALRAE
        ALRAE: u1 = 0x0,
        /// ALRBE
        ALRBE: u1 = 0x0,
        /// WUTE
        WUTE: u1 = 0x0,
        /// TSE
        TSE: u1 = 0x0,
        /// ALRAIE
        ALRAIE: u1 = 0x0,
        /// ALRBIE
        ALRBIE: u1 = 0x0,
        /// WUTIE
        WUTIE: u1 = 0x0,
        /// TSIE
        TSIE: u1 = 0x0,
        /// ADD1H
        ADD1H: u1 = 0x0,
        /// SUB1H
        SUB1H: u1 = 0x0,
        /// BKP
        BKP: u1 = 0x0,
        /// COSEL
        COSEL: u1 = 0x0,
        /// POL
        POL: u1 = 0x0,
        /// OSEL
        OSEL: u2 = 0x0,
        /// COE
        COE: u1 = 0x0,
        /// ITSE
        ITSE: u1 = 0x0,
        /// TAMPTS
        TAMPTS: u1 = 0x0,
        /// TAMPOE
        TAMPOE: u1 = 0x0,
        reserved29: u2 = 0,
        /// TAMPALRM_PU
        TAMPALRM_PU: u1 = 0x0,
        /// TAMPALRM_TYPE
        TAMPALRM_TYPE: u1 = 0x0,
        /// OUT2EN
        OUT2EN: u1 = 0x0,
    }),
    /// offset: 0x1c
    reserved28: [8]u8,
    /// write protection register
    /// offset: 0x24
    WPR: mmio.Mmio(packed struct(u32) {
        /// Write protection key
        KEY: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// calibration register
    /// offset: 0x28
    CALR: mmio.Mmio(packed struct(u32) {
        /// Calibration minus
        CALM: u9 = 0x0,
        reserved13: u4 = 0,
        /// Use a 16-second calibration cycle period
        CALW16: u1 = 0x0,
        /// Use an 8-second calibration cycle period
        CALW8: u1 = 0x0,
        /// Increase frequency of RTC by 488.5 ppm
        CALP: u1 = 0x0,
        padding: u16 = 0,
    }),
    /// shift control register
    /// offset: 0x2c
    SHIFTR: mmio.Mmio(packed struct(u32) {
        /// Subtract a fraction of a second
        SUBFS: u15 = 0x0,
        reserved31: u16 = 0,
        /// Add one second
        ADD1S: u1 = 0x0,
    }),
    /// time stamp time register
    /// offset: 0x30
    TSTR: mmio.Mmio(packed struct(u32) {
        /// Second units in BCD format
        SU: u4 = 0x0,
        /// Second tens in BCD format
        ST: u3 = 0x0,
        reserved8: u1 = 0,
        /// Minute units in BCD format
        MNU: u4 = 0x0,
        /// Minute tens in BCD format
        MNT: u3 = 0x0,
        reserved16: u1 = 0,
        /// Hour units in BCD format
        HU: u4 = 0x0,
        /// Hour tens in BCD format
        HT: u2 = 0x0,
        /// AM/PM notation
        PM: u1 = 0x0,
        padding: u9 = 0,
    }),
    /// time stamp date register
    /// offset: 0x34
    TSDR: mmio.Mmio(packed struct(u32) {
        /// Date units in BCD format
        DU: u4 = 0x0,
        /// Date tens in BCD format
        DT: u2 = 0x0,
        reserved8: u2 = 0,
        /// Month units in BCD format
        MU: u4 = 0x0,
        /// Month tens in BCD format
        MT: u1 = 0x0,
        /// Week day units
        WDU: u3 = 0x0,
        padding: u16 = 0,
    }),
    /// timestamp sub second register
    /// offset: 0x38
    TSSSR: mmio.Mmio(packed struct(u32) {
        /// Sub second value
        SS: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x3c
    reserved60: [4]u8,
    /// alarm A register
    /// offset: 0x40
    ALRMAR: mmio.Mmio(packed struct(u32) {
        /// Second units in BCD format
        SU: u4 = 0x0,
        /// Second tens in BCD format
        ST: u3 = 0x0,
        /// Alarm A seconds mask
        MSK1: u1 = 0x0,
        /// Minute units in BCD format
        MNU: u4 = 0x0,
        /// Minute tens in BCD format
        MNT: u3 = 0x0,
        /// Alarm A minutes mask
        MSK2: u1 = 0x0,
        /// Hour units in BCD format
        HU: u4 = 0x0,
        /// Hour tens in BCD format
        HT: u2 = 0x0,
        /// AM/PM notation
        PM: u1 = 0x0,
        /// Alarm A hours mask
        MSK3: u1 = 0x0,
        /// Date units or day in BCD format
        DU: u4 = 0x0,
        /// Date tens in BCD format
        DT: u2 = 0x0,
        /// Week day selection
        WDSEL: u1 = 0x0,
        /// Alarm A date mask
        MSK4: u1 = 0x0,
    }),
    /// alarm A sub second register
    /// offset: 0x44
    ALRMASSR: mmio.Mmio(packed struct(u32) {
        /// Sub seconds value
        SS: u15 = 0x0,
        reserved24: u9 = 0,
        /// Mask the most-significant bits starting at this bit
        MASKSS: u4 = 0x0,
        padding: u4 = 0,
    }),
    /// alarm B register
    /// offset: 0x48
    ALRMBR: mmio.Mmio(packed struct(u32) {
        /// Second units in BCD format
        SU: u4 = 0x0,
        /// Second tens in BCD format
        ST: u3 = 0x0,
        /// Alarm B seconds mask
        MSK1: u1 = 0x0,
        /// Minute units in BCD format
        MNU: u4 = 0x0,
        /// Minute tens in BCD format
        MNT: u3 = 0x0,
        /// Alarm B minutes mask
        MSK2: u1 = 0x0,
        /// Hour units in BCD format
        HU: u4 = 0x0,
        /// Hour tens in BCD format
        HT: u2 = 0x0,
        /// AM/PM notation
        PM: u1 = 0x0,
        /// Alarm B hours mask
        MSK3: u1 = 0x0,
        /// Date units or day in BCD format
        DU: u4 = 0x0,
        /// Date tens in BCD format
        DT: u2 = 0x0,
        /// Week day selection
        WDSEL: u1 = 0x0,
        /// Alarm B date mask
        MSK4: u1 = 0x0,
    }),
    /// alarm B sub second register
    /// offset: 0x4c
    ALRMBSSR: mmio.Mmio(packed struct(u32) {
        /// Sub seconds value
        SS: u15 = 0x0,
        reserved24: u9 = 0,
        /// Mask the most-significant bits starting at this bit
        MASKSS: u4 = 0x0,
        padding: u4 = 0,
    }),
    /// status register
    /// offset: 0x50
    SR: mmio.Mmio(packed struct(u32) {
        /// ALRAF
        ALRAF: u1 = 0x0,
        /// ALRBF
        ALRBF: u1 = 0x0,
        /// WUTF
        WUTF: u1 = 0x0,
        /// TSF
        TSF: u1 = 0x0,
        /// TSOVF
        TSOVF: u1 = 0x0,
        /// ITSF
        ITSF: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// masked interrupt status register
    /// offset: 0x54
    MISR: mmio.Mmio(packed struct(u32) {
        /// ALRAMF
        ALRAMF: u1 = 0x0,
        /// ALRBMF
        ALRBMF: u1 = 0x0,
        /// WUTMF
        WUTMF: u1 = 0x0,
        /// TSMF
        TSMF: u1 = 0x0,
        /// TSOVMF
        TSOVMF: u1 = 0x0,
        /// ITSMF
        ITSMF: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// offset: 0x58
    reserved88: [4]u8,
    /// status clear register
    /// offset: 0x5c
    SCR: mmio.Mmio(packed struct(u32) {
        /// CALRAF
        CALRAF: u1 = 0x0,
        /// CALRBF
        CALRBF: u1 = 0x0,
        /// CWUTF
        CWUTF: u1 = 0x0,
        /// CTSF
        CTSF: u1 = 0x0,
        /// CTSOVF
        CTSOVF: u1 = 0x0,
        /// CITSF
        CITSF: u1 = 0x0,
        padding: u26 = 0,
    }),
    /// offset: 0x60
    reserved96: [912]u8,
    /// hardware configuration register
    /// offset: 0x3f0
    HWCFGR: mmio.Mmio(packed struct(u32) {
        /// ALARMB
        ALARMB: u4 = 0x0,
        /// WAKEUP
        WAKEUP: u4 = 0x0,
        /// SMOOTH_CALIB
        SMOOTH_CALIB: u4 = 0x0,
        /// TIMESTAMP
        TIMESTAMP: u4 = 0x0,
        /// OPTIONREG_OUT
        OPTIONREG_OUT: u8 = 0x0,
        /// TRUST_ZONE
        TRUST_ZONE: u4 = 0x0,
        padding: u4 = 0,
    }),
    /// EXTI IP Version register
    /// offset: 0x3f4
    VERR: mmio.Mmio(packed struct(u32) {
        /// Minor Revision number
        MINREV: u4 = 0x0,
        /// Major Revision number
        MAJREV: u4 = 0x1,
        padding: u24 = 0,
    }),
    /// EXTI Identification register
    /// offset: 0x3f8
    IPIDR: mmio.Mmio(packed struct(u32) {
        /// IP Identification
        IPID: u32 = 0x120033,
    }),
    /// EXTI Size ID register
    /// offset: 0x3fc
    SIDR: mmio.Mmio(packed struct(u32) {
        /// Size Identification
        SID: u32 = 0xA3C5DD01,
    }),
};
