// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Tamper and backup registers
pub const TAMP = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// TAMP1E
        TAMP1E: u1 = 0x0,
        /// TAMP2E
        TAMP2E: u1 = 0x0,
        reserved16: u14 = 0,
        /// ITAMP1E
        ITAMP1E: u1 = 0x1,
        reserved18: u1 = 0,
        /// ITAMP3E
        ITAMP3E: u1 = 0x1,
        /// ITAMP4E
        ITAMP4E: u1 = 0x1,
        /// ITAMP5E
        ITAMP5E: u1 = 0x1,
        /// ITAMP6E
        ITAMP6E: u1 = 0x1,
        padding: u10 = 0,
    }),
    /// control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// TAMP1NOER
        TAMP1NOER: u1 = 0x0,
        /// TAMP2NOER
        TAMP2NOER: u1 = 0x0,
        reserved16: u14 = 0,
        /// TAMP1MSK
        TAMP1MSK: u1 = 0x0,
        /// TAMP2MSK
        TAMP2MSK: u1 = 0x0,
        reserved24: u6 = 0,
        /// TAMP1TRG
        TAMP1TRG: u1 = 0x0,
        /// TAMP2TRG
        TAMP2TRG: u1 = 0x0,
        padding: u6 = 0,
    }),
    /// offset: 0x08
    reserved8: [4]u8,
    /// TAMP filter control register
    /// offset: 0x0c
    FLTCR: mmio.Mmio(packed struct(u32) {
        /// TAMPFREQ
        TAMPFREQ: u3 = 0x0,
        /// TAMPFLT
        TAMPFLT: u2 = 0x0,
        /// TAMPPRCH
        TAMPPRCH: u2 = 0x0,
        /// TAMPPUDIS
        TAMPPUDIS: u1 = 0x0,
        padding: u24 = 0,
    }),
    /// offset: 0x10
    reserved16: [28]u8,
    /// TAMP interrupt enable register
    /// offset: 0x2c
    IER: mmio.Mmio(packed struct(u32) {
        /// TAMP1IE
        TAMP1IE: u1 = 0x0,
        /// TAMP2IE
        TAMP2IE: u1 = 0x0,
        reserved16: u14 = 0,
        /// ITAMP1IE
        ITAMP1IE: u1 = 0x0,
        reserved18: u1 = 0,
        /// ITAMP3IE
        ITAMP3IE: u1 = 0x0,
        /// ITAMP4IE
        ITAMP4IE: u1 = 0x0,
        /// ITAMP5IE
        ITAMP5IE: u1 = 0x0,
        /// ITAMP6IE
        ITAMP6IE: u1 = 0x0,
        padding: u10 = 0,
    }),
    /// TAMP status register
    /// offset: 0x30
    SR: mmio.Mmio(packed struct(u32) {
        /// TAMP1F
        TAMP1F: u1 = 0x0,
        /// TAMP2F
        TAMP2F: u1 = 0x0,
        reserved16: u14 = 0,
        /// ITAMP1F
        ITAMP1F: u1 = 0x0,
        reserved18: u1 = 0,
        /// ITAMP3F
        ITAMP3F: u1 = 0x0,
        /// ITAMP4F
        ITAMP4F: u1 = 0x0,
        /// ITAMP5F
        ITAMP5F: u1 = 0x0,
        /// ITAMP6F
        ITAMP6F: u1 = 0x0,
        /// ITAMP7F
        ITAMP7F: u1 = 0x0,
        padding: u9 = 0,
    }),
    /// TAMP masked interrupt status register
    /// offset: 0x34
    MISR: mmio.Mmio(packed struct(u32) {
        /// TAMP1MF:
        TAMP1MF: u1 = 0x0,
        /// TAMP2MF
        TAMP2MF: u1 = 0x0,
        reserved16: u14 = 0,
        /// ITAMP1MF
        ITAMP1MF: u1 = 0x0,
        reserved18: u1 = 0,
        /// ITAMP3MF
        ITAMP3MF: u1 = 0x0,
        /// ITAMP4MF
        ITAMP4MF: u1 = 0x0,
        /// ITAMP5MF
        ITAMP5MF: u1 = 0x0,
        /// ITAMP6MF
        ITAMP6MF: u1 = 0x0,
        padding: u10 = 0,
    }),
    /// offset: 0x38
    reserved56: [4]u8,
    /// TAMP status clear register
    /// offset: 0x3c
    SCR: mmio.Mmio(packed struct(u32) {
        /// CTAMP1F
        CTAMP1F: u1 = 0x0,
        /// CTAMP2F
        CTAMP2F: u1 = 0x0,
        reserved16: u14 = 0,
        /// CITAMP1F
        CITAMP1F: u1 = 0x0,
        reserved18: u1 = 0,
        /// CITAMP3F
        CITAMP3F: u1 = 0x0,
        /// CITAMP4F
        CITAMP4F: u1 = 0x0,
        /// CITAMP5F
        CITAMP5F: u1 = 0x0,
        /// CITAMP6F
        CITAMP6F: u1 = 0x0,
        /// CITAMP7F
        CITAMP7F: u1 = 0x0,
        padding: u9 = 0,
    }),
    /// offset: 0x40
    reserved64: [192]u8,
    /// TAMP backup register
    /// offset: 0x100
    BKP0R: mmio.Mmio(packed struct(u32) {
        /// BKP
        BKP: u32 = 0x0,
    }),
    /// TAMP backup register
    /// offset: 0x104
    BKP1R: mmio.Mmio(packed struct(u32) {
        /// BKP
        BKP: u32 = 0x0,
    }),
    /// TAMP backup register
    /// offset: 0x108
    BKP2R: mmio.Mmio(packed struct(u32) {
        /// BKP
        BKP: u32 = 0x0,
    }),
    /// TAMP backup register
    /// offset: 0x10c
    BKP3R: mmio.Mmio(packed struct(u32) {
        /// BKP
        BKP: u32 = 0x0,
    }),
    /// TAMP backup register
    /// offset: 0x110
    BKP4R: mmio.Mmio(packed struct(u32) {
        /// BKP
        BKP: u32 = 0x0,
    }),
    /// offset: 0x114
    reserved276: [728]u8,
    /// TAMP hardware configuration register 2
    /// offset: 0x3ec
    HWCFGR2: mmio.Mmio(packed struct(u32) {
        /// PTIONREG_OUT
        PTIONREG_OUT: u8 = 0x0,
        /// TRUST_ZONE
        TRUST_ZONE: u4 = 0x0,
        padding: u20 = 0,
    }),
    /// TAMP hardware configuration register 1
    /// offset: 0x3f0
    HWCFGR1: mmio.Mmio(packed struct(u32) {
        /// BACKUP_REGS
        BACKUP_REGS: u8 = 0x0,
        /// TAMPER
        TAMPER: u4 = 0x0,
        /// ACTIVE_TAMPER
        ACTIVE_TAMPER: u4 = 0x0,
        /// INT_TAMPER
        INT_TAMPER: u16 = 0x0,
    }),
    /// EXTI IP Version register
    /// offset: 0x3f4
    VERR: mmio.Mmio(packed struct(u32) {
        /// Minor Revision number
        MINREV: u4 = 0x0,
        /// Major Revision number
        MAJREV: u4 = 0x0,
        padding: u24 = 0,
    }),
    /// EXTI Identification register
    /// offset: 0x3f8
    IPIDR: mmio.Mmio(packed struct(u32) {
        /// IP Identification
        IPID: u32 = 0x0,
    }),
    /// EXTI Size ID register
    /// offset: 0x3fc
    SIDR: mmio.Mmio(packed struct(u32) {
        /// Size Identification
        SID: u32 = 0x0,
    }),
};
