// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// General purpose timers
pub const TIM14 = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Counter enable
        CEN: u1 = 0x0,
        /// Update disable
        UDIS: u1 = 0x0,
        /// Update request source
        URS: u1 = 0x0,
        /// One-pulse mode
        OPM: u1 = 0x0,
        reserved7: u3 = 0,
        /// Auto-reload preload enable
        ARPE: u1 = 0x0,
        /// Clock division
        CKD: u2 = 0x0,
        reserved11: u1 = 0,
        /// UIF status bit remapping
        UIFREMAP: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// offset: 0x04
    reserved4: [8]u8,
    /// DMA/Interrupt enable register
    /// offset: 0x0c
    DIER: mmio.Mmio(packed struct(u32) {
        /// Update interrupt enable
        UIE: u1 = 0x0,
        /// Capture/Compare 1 interrupt enable
        CC1IE: u1 = 0x0,
        padding: u30 = 0,
    }),
    /// status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// Update interrupt flag
        UIF: u1 = 0x0,
        /// Capture/compare 1 interrupt flag
        CC1IF: u1 = 0x0,
        reserved9: u7 = 0,
        /// Capture/Compare 1 overcapture flag
        CC1OF: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// event generation register
    /// offset: 0x14
    EGR: mmio.Mmio(packed struct(u32) {
        /// Update generation
        UG: u1 = 0x0,
        /// Capture/compare 1 generation
        CC1G: u1 = 0x0,
        padding: u30 = 0,
    }),
    /// capture/compare mode register 1 (output mode)
    /// offset: 0x18
    CCMR1_Output: mmio.Mmio(packed struct(u32) {
        /// CC1S
        CC1S: u2 = 0x0,
        /// OC1FE
        OC1FE: u1 = 0x0,
        /// OC1PE
        OC1PE: u1 = 0x0,
        /// OC1M
        OC1M: u3 = 0x0,
        /// OC1CE
        OC1CE: u1 = 0x0,
        reserved16: u8 = 0,
        /// Output Compare 1 mode - bit 3
        OC1M_3: u1 = 0x0,
        padding: u15 = 0,
    }),
    /// offset: 0x1c
    reserved28: [4]u8,
    /// capture/compare enable register
    /// offset: 0x20
    CCER: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 output enable
        CC1E: u1 = 0x0,
        /// Capture/Compare 1 output Polarity
        CC1P: u1 = 0x0,
        reserved3: u1 = 0,
        /// Capture/Compare 1 output Polarity
        CC1NP: u1 = 0x0,
        padding: u28 = 0,
    }),
    /// counter
    /// offset: 0x24
    CNT: mmio.Mmio(packed struct(u32) {
        /// low counter value
        CNT: u16 = 0x0,
        reserved31: u15 = 0,
        /// UIF Copy
        UIFCPY: u1 = 0x0,
    }),
    /// prescaler
    /// offset: 0x28
    PSC: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// auto-reload register
    /// offset: 0x2c
    ARR: mmio.Mmio(packed struct(u32) {
        /// Low Auto-reload value
        ARR: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x30
    reserved48: [4]u8,
    /// capture/compare register 1
    /// offset: 0x34
    CCR1: mmio.Mmio(packed struct(u32) {
        /// Low Capture/Compare 1 value
        CCR1: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x38
    reserved56: [48]u8,
    /// TIM timer input selection register
    /// offset: 0x68
    TISEL: mmio.Mmio(packed struct(u32) {
        /// TI1[0] to TI1[15] input selection
        TISEL: u4 = 0x0,
        padding: u28 = 0,
    }),
};
