// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// General purpose timers
pub const TIM16 = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Counter enable
        CEN: u1 = 0x0,
        /// Update disable
        UDIS: u1 = 0x0,
        /// Update request source
        URS: u1 = 0x0,
        /// One-pulse mode
        OPM: u1 = 0x0,
        reserved7: u3 = 0,
        /// Auto-reload preload enable
        ARPE: u1 = 0x0,
        /// Clock division
        CKD: u2 = 0x0,
        reserved11: u1 = 0,
        /// UIF status bit remapping
        UIFREMAP: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Capture/compare preloaded control
        CCPC: u1 = 0x0,
        reserved2: u1 = 0,
        /// Capture/compare control update selection
        CCUS: u1 = 0x0,
        /// Capture/compare DMA selection
        CCDS: u1 = 0x0,
        reserved8: u4 = 0,
        /// Output Idle state 1
        OIS1: u1 = 0x0,
        /// Output Idle state 1
        OIS1N: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// offset: 0x08
    reserved8: [4]u8,
    /// DMA/Interrupt enable register
    /// offset: 0x0c
    DIER: mmio.Mmio(packed struct(u32) {
        /// Update interrupt enable
        UIE: u1 = 0x0,
        /// Capture/Compare 1 interrupt enable
        CC1IE: u1 = 0x0,
        reserved5: u3 = 0,
        /// COM interrupt enable
        COMIE: u1 = 0x0,
        reserved7: u1 = 0,
        /// Break interrupt enable
        BIE: u1 = 0x0,
        /// Update DMA request enable
        UDE: u1 = 0x0,
        /// Capture/Compare 1 DMA request enable
        CC1DE: u1 = 0x0,
        reserved13: u3 = 0,
        /// COM DMA request enable
        COMDE: u1 = 0x0,
        padding: u18 = 0,
    }),
    /// status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// Update interrupt flag
        UIF: u1 = 0x0,
        /// Capture/compare 1 interrupt flag
        CC1IF: u1 = 0x0,
        reserved5: u3 = 0,
        /// COM interrupt flag
        COMIF: u1 = 0x0,
        reserved7: u1 = 0,
        /// Break interrupt flag
        BIF: u1 = 0x0,
        reserved9: u1 = 0,
        /// Capture/Compare 1 overcapture flag
        CC1OF: u1 = 0x0,
        padding: u22 = 0,
    }),
    /// event generation register
    /// offset: 0x14
    EGR: mmio.Mmio(packed struct(u32) {
        /// Update generation
        UG: u1 = 0x0,
        /// Capture/compare 1 generation
        CC1G: u1 = 0x0,
        reserved5: u3 = 0,
        /// Capture/Compare control update generation
        COMG: u1 = 0x0,
        reserved7: u1 = 0,
        /// Break generation
        BG: u1 = 0x0,
        padding: u24 = 0,
    }),
    /// capture/compare mode register (output mode)
    /// offset: 0x18
    CCMR1_Output: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 selection
        CC1S: u2 = 0x0,
        /// Output Compare 1 fast enable
        OC1FE: u1 = 0x0,
        /// Output Compare 1 preload enable
        OC1PE: u1 = 0x0,
        /// Output Compare 1 mode
        OC1M: u3 = 0x0,
        reserved16: u9 = 0,
        /// Output Compare 1 mode
        OC1M_2: u1 = 0x0,
        padding: u15 = 0,
    }),
    /// offset: 0x1c
    reserved28: [4]u8,
    /// capture/compare enable register
    /// offset: 0x20
    CCER: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 output enable
        CC1E: u1 = 0x0,
        /// Capture/Compare 1 output Polarity
        CC1P: u1 = 0x0,
        /// Capture/Compare 1 complementary output enable
        CC1NE: u1 = 0x0,
        /// Capture/Compare 1 output Polarity
        CC1NP: u1 = 0x0,
        padding: u28 = 0,
    }),
    /// counter
    /// offset: 0x24
    CNT: mmio.Mmio(packed struct(u32) {
        /// counter value
        CNT: u16 = 0x0,
        reserved31: u15 = 0,
        /// UIF Copy
        UIFCPY: u1 = 0x0,
    }),
    /// prescaler
    /// offset: 0x28
    PSC: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// auto-reload register
    /// offset: 0x2c
    ARR: mmio.Mmio(packed struct(u32) {
        /// Auto-reload value
        ARR: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// repetition counter register
    /// offset: 0x30
    RCR: mmio.Mmio(packed struct(u32) {
        /// Repetition counter value
        REP: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// capture/compare register 1
    /// offset: 0x34
    CCR1: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 value
        CCR1: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x38
    reserved56: [12]u8,
    /// break and dead-time register
    /// offset: 0x44
    BDTR: mmio.Mmio(packed struct(u32) {
        /// Dead-time generator setup
        DTG: u8 = 0x0,
        /// Lock configuration
        LOCK: u2 = 0x0,
        /// Off-state selection for Idle mode
        OSSI: u1 = 0x0,
        /// Off-state selection for Run mode
        OSSR: u1 = 0x0,
        /// Break enable
        BKE: u1 = 0x0,
        /// Break polarity
        BKP: u1 = 0x0,
        /// Automatic output enable
        AOE: u1 = 0x0,
        /// Main output enable
        MOE: u1 = 0x0,
        /// Break filter
        BKF: u4 = 0x0,
        reserved26: u6 = 0,
        /// Break Disarm
        BKDSRM: u1 = 0x0,
        reserved28: u1 = 0,
        /// Break Bidirectional
        BKBID: u1 = 0x0,
        padding: u3 = 0,
    }),
    /// DMA control register
    /// offset: 0x48
    DCR: mmio.Mmio(packed struct(u32) {
        /// DMA base address
        DBA: u5 = 0x0,
        reserved8: u3 = 0,
        /// DMA burst length
        DBL: u5 = 0x0,
        padding: u19 = 0,
    }),
    /// DMA address for full transfer
    /// offset: 0x4c
    DMAR: mmio.Mmio(packed struct(u32) {
        /// DMA register for burst accesses
        DMAB: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x50
    reserved80: [16]u8,
    /// TIM17 option register 1
    /// offset: 0x60
    AF1: mmio.Mmio(packed struct(u32) {
        /// BRK BKIN input enable
        BKINE: u1 = 0x0,
        /// BRK COMP1 enable
        BKCMP1E: u1 = 0x0,
        /// BRK COMP2 enable
        BKCMP2E: u1 = 0x0,
        reserved8: u5 = 0,
        /// BRK DFSDM_BREAK1 enable
        BKDFBK1E: u1 = 0x0,
        /// BRK BKIN input polarity
        BKINP: u1 = 0x0,
        /// BRK COMP1 input polarity
        BKCMP1P: u1 = 0x0,
        /// BRK COMP2 input polarit
        BKCMP2P: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// offset: 0x64
    reserved100: [4]u8,
    /// input selection register
    /// offset: 0x68
    TISEL: mmio.Mmio(packed struct(u32) {
        /// selects input
        TI1SEL: u4 = 0x0,
        reserved8: u4 = 0,
        /// selects input
        TI2SEL: u4 = 0x0,
        padding: u20 = 0,
    }),
};
