// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Advanced-timers
pub const TIM1 = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Counter enable
        CEN: u1 = 0x0,
        /// Update disable
        UDIS: u1 = 0x0,
        /// Update request source
        URS: u1 = 0x0,
        /// One-pulse mode
        OPM: u1 = 0x0,
        /// Direction
        DIR: u1 = 0x0,
        /// Center-aligned mode selection
        CMS: u2 = 0x0,
        /// Auto-reload preload enable
        ARPE: u1 = 0x0,
        /// Clock division
        CKD: u2 = 0x0,
        reserved11: u1 = 0,
        /// UIF status bit remapping
        UIFREMAP: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Capture/compare preloaded control
        CCPC: u1 = 0x0,
        reserved2: u1 = 0,
        /// Capture/compare control update selection
        CCUS: u1 = 0x0,
        /// Capture/compare DMA selection
        CCDS: u1 = 0x0,
        /// Master mode selection
        MMS: u3 = 0x0,
        /// TI1 selection
        TI1S: u1 = 0x0,
        /// Output Idle state 1
        OIS1: u1 = 0x0,
        /// Output Idle state 1
        OIS1N: u1 = 0x0,
        /// Output Idle state 2
        OIS2: u1 = 0x0,
        /// Output Idle state 2
        OIS2N: u1 = 0x0,
        /// Output Idle state 3
        OIS3: u1 = 0x0,
        /// Output Idle state 3
        OIS3N: u1 = 0x0,
        /// Output Idle state 4
        OIS4: u1 = 0x0,
        reserved16: u1 = 0,
        /// Output Idle state 5 (OC5 output)
        OIS5: u1 = 0x0,
        reserved18: u1 = 0,
        /// Output Idle state 6 (OC6 output)
        OIS6: u1 = 0x0,
        reserved20: u1 = 0,
        /// Master mode selection 2
        MMS2: u4 = 0x0,
        padding: u8 = 0,
    }),
    /// slave mode control register
    /// offset: 0x08
    SMCR: mmio.Mmio(packed struct(u32) {
        /// Slave mode selection
        SMS: u3 = 0x0,
        /// OCREF clear selection
        OCCS: u1 = 0x0,
        /// Trigger selection
        TS_4: u3 = 0x0,
        /// Master/Slave mode
        MSM: u1 = 0x0,
        /// External trigger filter
        ETF: u4 = 0x0,
        /// External trigger prescaler
        ETPS: u2 = 0x0,
        /// External clock enable
        ECE: u1 = 0x0,
        /// External trigger polarity
        ETP: u1 = 0x0,
        /// Slave mode selection - bit 3
        SMS_3: u1 = 0x0,
        reserved20: u3 = 0,
        /// Trigger selection
        TS: u2 = 0x0,
        padding: u10 = 0,
    }),
    /// DMA/Interrupt enable register
    /// offset: 0x0c
    DIER: mmio.Mmio(packed struct(u32) {
        /// Update interrupt enable
        UIE: u1 = 0x0,
        /// Capture/Compare 1 interrupt enable
        CC1IE: u1 = 0x0,
        /// Capture/Compare 2 interrupt enable
        CC2IE: u1 = 0x0,
        /// Capture/Compare 3 interrupt enable
        CC3IE: u1 = 0x0,
        /// Capture/Compare 4 interrupt enable
        CC4IE: u1 = 0x0,
        /// COM interrupt enable
        COMIE: u1 = 0x0,
        /// Trigger interrupt enable
        TIE: u1 = 0x0,
        /// Break interrupt enable
        BIE: u1 = 0x0,
        /// Update DMA request enable
        UDE: u1 = 0x0,
        /// Capture/Compare 1 DMA request enable
        CC1DE: u1 = 0x0,
        /// Capture/Compare 2 DMA request enable
        CC2DE: u1 = 0x0,
        /// Capture/Compare 3 DMA request enable
        CC3DE: u1 = 0x0,
        /// Capture/Compare 4 DMA request enable
        CC4DE: u1 = 0x0,
        /// COM DMA request enable
        COMDE: u1 = 0x0,
        /// Trigger DMA request enable
        TDE: u1 = 0x0,
        padding: u17 = 0,
    }),
    /// status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// Update interrupt flag
        UIF: u1 = 0x0,
        /// Capture/compare 1 interrupt flag
        CC1IF: u1 = 0x0,
        /// Capture/Compare 2 interrupt flag
        CC2IF: u1 = 0x0,
        /// Capture/Compare 3 interrupt flag
        CC3IF: u1 = 0x0,
        /// Capture/Compare 4 interrupt flag
        CC4IF: u1 = 0x0,
        /// COM interrupt flag
        COMIF: u1 = 0x0,
        /// Trigger interrupt flag
        TIF: u1 = 0x0,
        /// Break interrupt flag
        BIF: u1 = 0x0,
        /// Break 2 interrupt flag
        B2IF: u1 = 0x0,
        /// Capture/Compare 1 overcapture flag
        CC1OF: u1 = 0x0,
        /// Capture/compare 2 overcapture flag
        CC2OF: u1 = 0x0,
        /// Capture/Compare 3 overcapture flag
        CC3OF: u1 = 0x0,
        /// Capture/Compare 4 overcapture flag
        CC4OF: u1 = 0x0,
        /// System Break interrupt flag
        SBIF: u1 = 0x0,
        reserved16: u2 = 0,
        /// Compare 5 interrupt flag
        CC5IF: u1 = 0x0,
        /// Compare 6 interrupt flag
        CC6IF: u1 = 0x0,
        padding: u14 = 0,
    }),
    /// event generation register
    /// offset: 0x14
    EGR: mmio.Mmio(packed struct(u32) {
        /// Update generation
        UG: u1 = 0x0,
        /// Capture/compare 1 generation
        CC1G: u1 = 0x0,
        /// Capture/compare 2 generation
        CC2G: u1 = 0x0,
        /// Capture/compare 3 generation
        CC3G: u1 = 0x0,
        /// Capture/compare 4 generation
        CC4G: u1 = 0x0,
        /// Capture/Compare control update generation
        COMG: u1 = 0x0,
        /// Trigger generation
        TG: u1 = 0x0,
        /// Break generation
        BG: u1 = 0x0,
        /// Break 2 generation
        B2G: u1 = 0x0,
        padding: u23 = 0,
    }),
    /// capture/compare mode register 1 (output mode)
    /// offset: 0x18
    CCMR1_Output: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 selection
        CC1S: u2 = 0x0,
        /// Output Compare 1 fast enable
        OC1FE: u1 = 0x0,
        /// Output Compare 1 preload enable
        OC1PE: u1 = 0x0,
        /// Output Compare 1 mode
        OC1M: u3 = 0x0,
        /// Output Compare 1 clear enable
        OC1CE: u1 = 0x0,
        /// Capture/Compare 2 selection
        CC2S: u2 = 0x0,
        /// Output Compare 2 fast enable
        OC2FE: u1 = 0x0,
        /// Output Compare 2 preload enable
        OC2PE: u1 = 0x0,
        /// Output Compare 2 mode
        OC2M: u3 = 0x0,
        /// Output Compare 2 clear enable
        OC2CE: u1 = 0x0,
        /// Output Compare 1 mode - bit 3
        OC1M_3: u1 = 0x0,
        reserved24: u7 = 0,
        /// Output Compare 2 mode - bit 3
        OC2M_3: u1 = 0x0,
        padding: u7 = 0,
    }),
    /// capture/compare mode register 2 (output mode)
    /// offset: 0x1c
    CCMR2_Output: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 3 selection
        CC3S: u2 = 0x0,
        /// Output compare 3 fast enable
        OC3FE: u1 = 0x0,
        /// Output compare 3 preload enable
        OC3PE: u1 = 0x0,
        /// Output compare 3 mode
        OC3M: u3 = 0x0,
        /// Output compare 3 clear enable
        OC3CE: u1 = 0x0,
        /// Capture/Compare 4 selection
        CC4S: u2 = 0x0,
        /// Output compare 4 fast enable
        OC4FE: u1 = 0x0,
        /// Output compare 4 preload enable
        OC4PE: u1 = 0x0,
        /// Output compare 4 mode
        OC4M: u3 = 0x0,
        /// Output compare 4 clear enable
        OC4CE: u1 = 0x0,
        /// Output Compare 3 mode - bit 3
        OC3M_3: u1 = 0x0,
        reserved24: u7 = 0,
        /// Output Compare 4 mode - bit 3
        OC4M_3: u1 = 0x0,
        padding: u7 = 0,
    }),
    /// capture/compare enable register
    /// offset: 0x20
    CCER: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 output enable
        CC1E: u1 = 0x0,
        /// Capture/Compare 1 output Polarity
        CC1P: u1 = 0x0,
        /// Capture/Compare 1 complementary output enable
        CC1NE: u1 = 0x0,
        /// Capture/Compare 1 output Polarity
        CC1NP: u1 = 0x0,
        /// Capture/Compare 2 output enable
        CC2E: u1 = 0x0,
        /// Capture/Compare 2 output Polarity
        CC2P: u1 = 0x0,
        /// Capture/Compare 2 complementary output enable
        CC2NE: u1 = 0x0,
        /// Capture/Compare 2 output Polarity
        CC2NP: u1 = 0x0,
        /// Capture/Compare 3 output enable
        CC3E: u1 = 0x0,
        /// Capture/Compare 3 output Polarity
        CC3P: u1 = 0x0,
        /// Capture/Compare 3 complementary output enable
        CC3NE: u1 = 0x0,
        /// Capture/Compare 3 output Polarity
        CC3NP: u1 = 0x0,
        /// Capture/Compare 4 output enable
        CC4E: u1 = 0x0,
        /// Capture/Compare 3 output Polarity
        CC4P: u1 = 0x0,
        reserved15: u1 = 0,
        /// Capture/Compare 4 complementary output polarity
        CC4NP: u1 = 0x0,
        /// Capture/Compare 5 output enable
        CC5E: u1 = 0x0,
        /// Capture/Compare 5 output polarity
        CC5P: u1 = 0x0,
        reserved20: u2 = 0,
        /// Capture/Compare 6 output enable
        CC6E: u1 = 0x0,
        /// Capture/Compare 6 output polarity
        CC6P: u1 = 0x0,
        padding: u10 = 0,
    }),
    /// counter
    /// offset: 0x24
    CNT: mmio.Mmio(packed struct(u32) {
        /// counter value
        CNT: u16 = 0x0,
        reserved31: u15 = 0,
        /// UIF copy
        UIFCPY: u1 = 0x0,
    }),
    /// prescaler
    /// offset: 0x28
    PSC: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// auto-reload register
    /// offset: 0x2c
    ARR: mmio.Mmio(packed struct(u32) {
        /// Auto-reload value
        ARR: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// repetition counter register
    /// offset: 0x30
    RCR: mmio.Mmio(packed struct(u32) {
        /// Repetition counter value
        REP: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// capture/compare register 1
    /// offset: 0x34
    CCR1: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 value
        CCR1: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// capture/compare register 2
    /// offset: 0x38
    CCR2: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 2 value
        CCR2: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// capture/compare register 3
    /// offset: 0x3c
    CCR3: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare value
        CCR3: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// capture/compare register 4
    /// offset: 0x40
    CCR4: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare value
        CCR4: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// break and dead-time register
    /// offset: 0x44
    BDTR: mmio.Mmio(packed struct(u32) {
        /// Dead-time generator setup
        DTG: u8 = 0x0,
        /// Lock configuration
        LOCK: u2 = 0x0,
        /// Off-state selection for Idle mode
        OSSI: u1 = 0x0,
        /// Off-state selection for Run mode
        OSSR: u1 = 0x0,
        /// Break enable
        BKE: u1 = 0x0,
        /// Break polarity
        BKP: u1 = 0x0,
        /// Automatic output enable
        AOE: u1 = 0x0,
        /// Main output enable
        MOE: u1 = 0x0,
        /// Break filter
        BKF: u4 = 0x0,
        /// Break 2 filter
        BK2F: u4 = 0x0,
        /// Break 2 enable
        BK2E: u1 = 0x0,
        /// Break 2 polarity
        BK2P: u1 = 0x0,
        /// Break Disarm
        BKDSRM: u1 = 0x0,
        /// Break2 Disarm
        BK2DSRM: u1 = 0x0,
        /// Break Bidirectional
        BKBID: u1 = 0x0,
        /// Break2 bidirectional
        BK2ID: u1 = 0x0,
        padding: u2 = 0,
    }),
    /// DMA control register
    /// offset: 0x48
    DCR: mmio.Mmio(packed struct(u32) {
        /// DMA base address
        DBA: u5 = 0x0,
        reserved8: u3 = 0,
        /// DMA burst length
        DBL: u5 = 0x0,
        padding: u19 = 0,
    }),
    /// DMA address for full transfer
    /// offset: 0x4c
    DMAR: mmio.Mmio(packed struct(u32) {
        /// DMA register for burst accesses
        DMAB: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// option register 1
    /// offset: 0x50
    OR1: mmio.Mmio(packed struct(u32) {
        /// Ocref_clr source selection
        OCREF_CLR: u1 = 0x0,
        padding: u31 = 0,
    }),
    /// capture/compare mode register 2 (output mode)
    /// offset: 0x54
    CCMR3_Output: mmio.Mmio(packed struct(u32) {
        reserved2: u2 = 0,
        /// Output compare 5 fast enable
        OC5FE: u1 = 0x0,
        /// Output compare 5 preload enable
        OC5PE: u1 = 0x0,
        /// Output compare 5 mode
        OC5M: u3 = 0x0,
        /// Output compare 5 clear enable
        OC5CE: u1 = 0x0,
        reserved10: u2 = 0,
        /// Output compare 6 fast enable
        OC6FE: u1 = 0x0,
        /// Output compare 6 preload enable
        OC6PE: u1 = 0x0,
        /// Output compare 6 mode
        OC6M: u3 = 0x0,
        /// Output compare 6 clear enable
        OC6CE: u1 = 0x0,
        /// Output Compare 5 mode bit 3
        OC5M_bit3: u1 = 0x0,
        reserved24: u7 = 0,
        /// Output Compare 6 mode bit 3
        OC6M_bit3: u1 = 0x0,
        padding: u7 = 0,
    }),
    /// capture/compare register 4
    /// offset: 0x58
    CCR5: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare value
        CCR5: u16 = 0x0,
        reserved29: u13 = 0,
        /// Group Channel 5 and Channel 1
        GC5C1: u1 = 0x0,
        /// Group Channel 5 and Channel 2
        GC5C2: u1 = 0x0,
        /// Group Channel 5 and Channel 3
        GC5C3: u1 = 0x0,
    }),
    /// capture/compare register 4
    /// offset: 0x5c
    CCR6: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare value
        CCR6: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// DMA address for full transfer
    /// offset: 0x60
    AF1: mmio.Mmio(packed struct(u32) {
        /// BRK BKIN input enable
        BKINE: u1 = 0x1,
        /// BRK COMP1 enable
        BKCMP1E: u1 = 0x0,
        /// BRK COMP2 enable
        BKCMP2E: u1 = 0x0,
        reserved9: u6 = 0,
        /// BRK BKIN input polarity
        BKINP: u1 = 0x0,
        /// BRK COMP1 input polarity
        BKCMP1P: u1 = 0x0,
        /// BRK COMP2 input polarity
        BKCMP2P: u1 = 0x0,
        reserved14: u2 = 0,
        /// ETR source selection
        ETRSEL: u3 = 0x0,
        padding: u15 = 0,
    }),
    /// DMA address for full transfer
    /// offset: 0x64
    AF2: mmio.Mmio(packed struct(u32) {
        /// BRK2 BKIN input enable
        BK2INE: u1 = 0x1,
        /// BRK2 COMP1 enable
        BK2CMP1E: u1 = 0x0,
        /// BRK2 COMP2 enable
        BK2CMP2E: u1 = 0x0,
        reserved8: u5 = 0,
        /// BRK2 DFSDM_BREAK0 enable
        BK2DFBK0E: u1 = 0x0,
        /// BRK2 BKIN input polarity
        BK2INP: u1 = 0x0,
        /// BRK2 COMP1 input polarity
        BK2CMP1P: u1 = 0x0,
        /// BRK2 COMP2 input polarity
        BK2CMP2P: u1 = 0x0,
        padding: u20 = 0,
    }),
};
