// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// General purpose timers
pub const TIM15 = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Counter enable Note: External clock and gated mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.
        CEN: enum(u1) {
            /// Counter disabled
            B_0x0 = 0x0,
            /// Counter enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.
        UDIS: enum(u1) {
            /// UEV enabled. The Update (UEV) event is generated by one of the following events:
            B_0x0 = 0x0,
            /// UEV disabled. The Update event is not generated, shadow registers keep their value (ARR, PSC, CCRx). However the counter and the prescaler are reinitialized if the UG bit is set or if a hardware reset is received from the slave mode controller.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller
        URS: enum(u1) {
            /// Any of the following events generate an update interrupt if enabled. These events can be:
            B_0x0 = 0x0,
            /// Only counter overflow/underflow generates an update interrupt if enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// One-pulse mode
        OPM: enum(u1) {
            /// Counter is not stopped at update event
            B_0x0 = 0x0,
            /// Counter stops counting at the next update event (clearing the bit CEN)
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved7: u3 = 0,
        /// Auto-reload preload enable
        ARPE: enum(u1) {
            /// TIMx_ARR register is not buffered
            B_0x0 = 0x0,
            /// TIMx_ARR register is buffered
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Clock division This bitfield indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (tDTS) used by the dead-time generators and the digital filters (TIx)
        CKD: enum(u2) {
            /// tDTS = tCK_INT
            B_0x0 = 0x0,
            /// tDTS = 2*tCK_INT
            B_0x1 = 0x1,
            /// tDTS = 4*tCK_INT
            B_0x2 = 0x2,
            /// Reserved, do not program this value
            B_0x3 = 0x3,
        } = .B_0x0,
        reserved11: u1 = 0,
        /// UIF status bit remapping
        UIFREMAP: enum(u1) {
            /// No remapping. UIF status bit is not copied to TIMx_CNT register bit 31.
            B_0x0 = 0x0,
            /// Remapping enabled. UIF status bit is copied to TIMx_CNT register bit 31.
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u20 = 0,
    }),
    /// control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Capture/compare preloaded control Note: This bit acts only on channels that have a complementary output.
        CCPC: enum(u1) {
            /// CCxE, CCxNE and OCxM bits are not preloaded
            B_0x0 = 0x0,
            /// CCxE, CCxNE and OCxM bits are preloaded, after having been written, they are updated only when a commutation event (COM) occurs (COMG bit set or rising edge detected on TRGI, depending on the CCUS bit).
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved2: u1 = 0,
        /// Capture/compare control update selection Note: This bit acts only on channels that have a complementary output.
        CCUS: enum(u1) {
            /// When capture/compare control bits are preloaded (CCPC=1), they are updated by setting the COMG bit only.
            B_0x0 = 0x0,
            /// When capture/compare control bits are preloaded (CCPC=1), they are updated by setting the COMG bit or when an rising edge occurs on TRGI.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/compare DMA selection
        CCDS: enum(u1) {
            /// CCx DMA request sent when CCx event occurs
            B_0x0 = 0x0,
            /// CCx DMA requests sent when update event occurs
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Master mode selection These bits allow to select the information to be sent in master mode to slave timers for synchronization (TRGO). The combination is as follows:
        MMS: enum(u3) {
            /// Reset - the UG bit from the TIMx_EGR register is used as trigger output (TRGO). If the reset is generated by the trigger input (slave mode controller configured in reset mode) then the signal on TRGO is delayed compared to the actual reset.
            B_0x0 = 0x0,
            /// Enable - the Counter Enable signal CNT_EN is used as trigger output (TRGO). It is useful to start several timers at the same time or to control a window in which a slave timer is enable. The Counter Enable signal is generated by a logic AND between CEN control bit and the trigger input when configured in gated mode. When the Counter Enable signal is controlled by the trigger input, there is a delay on TRGO, except if the master/slave mode is selected (see the MSM bit description in TIMx_SMCR register).
            B_0x1 = 0x1,
            /// Update - The update event is selected as trigger output (TRGO). For instance a master timer can then be used as a prescaler for a slave timer.
            B_0x2 = 0x2,
            /// Compare Pulse - The trigger output send a positive pulse when the CC1IF flag is to be set (even if it was already high), as soon as a capture or a compare match occurred. (TRGO).
            B_0x3 = 0x3,
            /// Compare - OC1REFC signal is used as trigger output (TRGO).
            B_0x4 = 0x4,
            /// Compare - OC2REFC signal is used as trigger output (TRGO).
            B_0x5 = 0x5,
            _,
        } = .B_0x0,
        /// TI1 selection
        TI1S: enum(u1) {
            /// The TIMx_CH1 pin is connected to TI1 input
            B_0x0 = 0x0,
            /// The TIMx_CH1, CH2 pins are connected to the TI1 input (XOR combination)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Output Idle state 1 (OC1 output) Note: This bit can not be modified as long as LOCK level 1, 2 or 3 has been programmed (LOCK bits in TIM15_BDTR register).
        OIS1: enum(u1) {
            /// OC1=0 (after a dead-time if OC1N is implemented) when MOE=0
            B_0x0 = 0x0,
            /// OC1=1 (after a dead-time if OC1N is implemented) when MOE=0
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Output Idle state 1 (OC1N output) Note: This bit can not be modified as long as LOCK level 1, 2 or 3 has been programmed (LOCK bits in TIM15_BDTR register).
        OIS1N: enum(u1) {
            /// OC1N=0 after a dead-time when MOE=0
            B_0x0 = 0x0,
            /// OC1N=1 after a dead-time when MOE=0
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Output idle state 2 (OC2 output) Note: This bit cannot be modified as long as LOCK level 1, 2 or 3 has been programmed (LOCK bits in the TIM15_BDTR register).
        OIS2: enum(u1) {
            /// OC2=0 when MOE=0
            B_0x0 = 0x0,
            /// OC2=1 when MOE=0
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u21 = 0,
    }),
    /// slave mode control register
    /// offset: 0x08
    SMCR: mmio.Mmio(packed struct(u32) {
        /// Slave mode selection When external signals are selected the active edge of the trigger signal (TRGI) is linked to the polarity selected on the external input (see Input Control register and Control Register description. Other codes: reserved. Note: The gated mode must not be used if TI1F_ED is selected as the trigger input (TS=â00100â). Indeed, TI1F_ED outputs 1 pulse for each transition on TI1F, whereas the gated mode checks the level of the trigger signal. Note: The clock of the slave peripherals (timer, ADC, ...) receiving the TRGO or the TRGO2 signals must be enabled prior to receive events from the master timer, and the clock frequency (prescaler) must not be changed on-the-fly while triggers are received from the master timer.
        SMS1: enum(u3) {
            /// Slave mode disabled - if CEN = '1â then the prescaler is clocked directly by the internal clock.
            B_0x0 = 0x0,
            /// Reset Mode - Rising edge of the selected trigger input (TRGI) reinitializes the counter and generates an update of the registers.
            B_0x4 = 0x4,
            /// Gated Mode - The counter clock is enabled when the trigger input (TRGI) is high. The counter stops (but is not reset) as soon as the trigger becomes low. Both start and stop of the counter are controlled.
            B_0x5 = 0x5,
            /// Trigger Mode - The counter starts at a rising edge of the trigger TRGI (but it is not reset). Only the start of the counter is controlled.
            B_0x6 = 0x6,
            /// External Clock Mode 1 - Rising edges of the selected trigger (TRGI) clock the counter.
            B_0x7 = 0x7,
            /// Combined reset + trigger mode - Rising edge of the selected trigger input (TRGI) reinitializes the counter, generates an update of the registers and starts the counter.
            B_0x8 = 0x8,
            _,
        } = .B_0x0,
        reserved4: u1 = 0,
        /// Trigger selection This bit field selects the trigger input to be used to synchronize the counter. Other: Reserved See for more details on ITRx meaning for each Timer. Note: These bits must be changed only when they are not used (e.g. when SMS=000) to avoid wrong edge detections at the transition.
        TS1: enum(u3) {
            /// Internal Trigger 0 (ITR0)
            B_0x0 = 0x0,
            /// Internal Trigger 1 (ITR1)
            B_0x1 = 0x1,
            /// Internal Trigger 2 (ITR2)
            B_0x2 = 0x2,
            /// Internal Trigger 3 (ITR3)
            B_0x3 = 0x3,
            /// TI1 Edge Detector (TI1F_ED)
            B_0x4 = 0x4,
            /// Filtered Timer Input 1 (TI1FP1)
            B_0x5 = 0x5,
            /// Filtered Timer Input 2 (TI2FP2)
            B_0x6 = 0x6,
            _,
        } = .B_0x0,
        /// Master/slave mode
        MSM: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// The effect of an event on the trigger input (TRGI) is delayed to allow a perfect synchronization between the current timer and its slaves (through TRGO). It is useful if we want to synchronize several timers on a single external event.
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved16: u8 = 0,
        /// Slave mode selection When external signals are selected the active edge of the trigger signal (TRGI) is linked to the polarity selected on the external input (see Input Control register and Control Register description. Other codes: reserved. Note: The gated mode must not be used if TI1F_ED is selected as the trigger input (TS=â00100â). Indeed, TI1F_ED outputs 1 pulse for each transition on TI1F, whereas the gated mode checks the level of the trigger signal. Note: The clock of the slave peripherals (timer, ADC, ...) receiving the TRGO or the TRGO2 signals must be enabled prior to receive events from the master timer, and the clock frequency (prescaler) must not be changed on-the-fly while triggers are received from the master timer.
        SMS2: enum(u1) {
            /// Slave mode disabled - if CEN = '1â then the prescaler is clocked directly by the internal clock.
            B_0x0 = 0x0,
            /// Reset Mode - Rising edge of the selected trigger input (TRGI) reinitializes the counter and generates an update of the registers.
            B_0x4 = 0x4,
            /// Gated Mode - The counter clock is enabled when the trigger input (TRGI) is high. The counter stops (but is not reset) as soon as the trigger becomes low. Both start and stop of the counter are controlled.
            B_0x5 = 0x5,
            /// Trigger Mode - The counter starts at a rising edge of the trigger TRGI (but it is not reset). Only the start of the counter is controlled.
            B_0x6 = 0x6,
            /// External Clock Mode 1 - Rising edges of the selected trigger (TRGI) clock the counter.
            B_0x7 = 0x7,
            /// Combined reset + trigger mode - Rising edge of the selected trigger input (TRGI) reinitializes the counter, generates an update of the registers and starts the counter.
            B_0x8 = 0x8,
        } = .B_0x0,
        reserved20: u3 = 0,
        /// Trigger selection This bit field selects the trigger input to be used to synchronize the counter. Other: Reserved See for more details on ITRx meaning for each Timer. Note: These bits must be changed only when they are not used (e.g. when SMS=000) to avoid wrong edge detections at the transition.
        TS2: enum(u2) {
            /// Internal Trigger 0 (ITR0)
            B_0x0 = 0x0,
            /// Internal Trigger 1 (ITR1)
            B_0x1 = 0x1,
            /// Internal Trigger 2 (ITR2)
            B_0x2 = 0x2,
            /// Internal Trigger 3 (ITR3)
            B_0x3 = 0x3,
            /// TI1 Edge Detector (TI1F_ED)
            B_0x4 = 0x4,
            /// Filtered Timer Input 1 (TI1FP1)
            B_0x5 = 0x5,
            /// Filtered Timer Input 2 (TI2FP2)
            B_0x6 = 0x6,
        } = .B_0x0,
        padding: u10 = 0,
    }),
    /// DMA/Interrupt enable register
    /// offset: 0x0c
    DIER: mmio.Mmio(packed struct(u32) {
        /// Update interrupt enable
        UIE: enum(u1) {
            /// Update interrupt disabled
            B_0x0 = 0x0,
            /// Update interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 interrupt enable
        CC1IE: enum(u1) {
            /// CC1 interrupt disabled
            B_0x0 = 0x0,
            /// CC1 interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 interrupt enable
        CC2IE: enum(u1) {
            /// CC2 interrupt disabled
            B_0x0 = 0x0,
            /// CC2 interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved5: u2 = 0,
        /// COM interrupt enable
        COMIE: enum(u1) {
            /// COM interrupt disabled
            B_0x0 = 0x0,
            /// COM interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Trigger interrupt enable
        TIE: enum(u1) {
            /// Trigger interrupt disabled
            B_0x0 = 0x0,
            /// Trigger interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Break interrupt enable
        BIE: enum(u1) {
            /// Break interrupt disabled
            B_0x0 = 0x0,
            /// Break interrupt enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Update DMA request enable
        UDE: enum(u1) {
            /// Update DMA request disabled
            B_0x0 = 0x0,
            /// Update DMA request enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 DMA request enable
        CC1DE: enum(u1) {
            /// CC1 DMA request disabled
            B_0x0 = 0x0,
            /// CC1 DMA request enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 DMA request enable
        CC2DE: enum(u1) {
            /// CC2 DMA request disabled
            B_0x0 = 0x0,
            /// CC2 DMA request enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved13: u2 = 0,
        /// COM DMA request enable
        COMDE: enum(u1) {
            /// COM DMA request disabled
            B_0x0 = 0x0,
            /// COM DMA request enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Trigger DMA request enable
        TDE: enum(u1) {
            /// Trigger DMA request disabled
            B_0x0 = 0x0,
            /// Trigger DMA request enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u17 = 0,
    }),
    /// status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// Update interrupt flag This bit is set by hardware on an update event. It is cleared by software. At overflow regarding the repetition counter value (update if repetition counter = 0) and if the UDIS=0 in the TIMx_CR1 register. When CNT is reinitialized by software using the UG bit in TIMx_EGR register, if URS=0 and UDIS=0 in the TIMx_CR1 register. When CNT is reinitialized by a trigger event (refer to control register (TIM15_SMCR)), if URS=0 and UDIS=0 in the TIMx_CR1 register.
        UIF: enum(u1) {
            /// No update occurred.
            B_0x0 = 0x0,
            /// Update interrupt pending. This bit is set by hardware when the registers are updated:
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 interrupt flag This flag is set by hardware. It is cleared by software (input capture or output compare mode) or by reading the TIMx_CCR1 register (input capture mode only). If channel CC1 is configured as output: this flag is set when the content of the counter TIMx_CNT matches the content of the TIMx_CCR1 register. When the content of TIMx_CCR1 is greater than the content of TIMx_ARR, the CC1IF bit goes high on the counter overflow (in up-counting and up/down-counting modes) or underflow (in down-counting mode). There are 3 possible options for flag setting in center-aligned mode, refer to the CMS bits in the TIMx_CR1 register for the full description. If channel CC1 is configured as input: this bit is set when counter value has been captured in TIMx_CCR1 register (an edge has been detected on IC1, as per the edge sensitivity defined with the CC1P and CC1NP bits setting, in TIMx_CCER).
        CC1IF: enum(u1) {
            /// No compare match / No input capture occurred
            B_0x0 = 0x0,
            /// A compare match or an input capture occurred
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 interrupt flag refer to CC1IF description
        CC2IF: u1 = 0x0,
        reserved5: u2 = 0,
        /// COM interrupt flag This flag is set by hardware on a COM event (once the capture/compare control bits âCCxE, CCxNE, OCxMâ have been updated). It is cleared by software.
        COMIF: enum(u1) {
            /// No COM event occurred
            B_0x0 = 0x0,
            /// COM interrupt pending
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Trigger interrupt flag This flag is set by hardware on the TRG trigger event (active edge detected on TRGI input when the slave mode controller is enabled in all modes but gated mode, both edges in case gated mode is selected). It is set when the counter starts or stops when gated mode is selected. It is cleared by software.
        TIF: enum(u1) {
            /// No trigger event occurred
            B_0x0 = 0x0,
            /// Trigger interrupt pending
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Break interrupt flag This flag is set by hardware as soon as the break input goes active. It can be cleared by software if the break input is not active.
        BIF: enum(u1) {
            /// No break event occurred
            B_0x0 = 0x0,
            /// An active level has been detected on the break input
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved9: u1 = 0,
        /// Capture/Compare 1 overcapture flag This flag is set by hardware only when the corresponding channel is configured in input capture mode. It is cleared by software by writing it to '0â.
        CC1OF: enum(u1) {
            /// No overcapture has been detected
            B_0x0 = 0x0,
            /// The counter value has been captured in TIMx_CCR1 register while CC1IF flag was already set
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 overcapture flag Refer to CC1OF description
        CC2OF: u1 = 0x0,
        padding: u21 = 0,
    }),
    /// event generation register
    /// offset: 0x14
    EGR: mmio.Mmio(packed struct(u32) {
        /// Update generation This bit can be set by software, it is automatically cleared by hardware.
        UG: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// Reinitialize the counter and generates an update of the registers. Note that the prescaler counter is cleared too (anyway the prescaler ratio is not affected).
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 generation This bit is set by software in order to generate an event, it is automatically cleared by hardware. If channel CC1 is configured as output: CC1IF flag is set, Corresponding interrupt or DMA request is sent if enabled. If channel CC1 is configured as input: The current value of the counter is captured in TIMx_CCR1 register. The CC1IF flag is set, the corresponding interrupt or DMA request is sent if enabled. The CC1OF flag is set if the CC1IF flag was already high.
        CC1G: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// A capture/compare event is generated on channel 1:
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 generation Refer to CC1G description
        CC2G: u1 = 0x0,
        reserved5: u2 = 0,
        /// Capture/Compare control update generation This bit can be set by software, it is automatically cleared by hardware. Note: This bit acts only on channels that have a complementary output.
        COMG: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// When the CCPC bit is set, it is possible to update the CCxE, CCxNE and OCxM bits
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Trigger generation This bit is set by software in order to generate an event, it is automatically cleared by hardware.
        TG: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// The TIF flag is set in TIMx_SR register. Related interrupt or DMA transfer can occur if enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Break generation This bit is set by software in order to generate an event, it is automatically cleared by hardware.
        BG: enum(u1) {
            /// No action
            B_0x0 = 0x0,
            /// A break event is generated. MOE bit is cleared and BIF flag is set. Related interrupt or DMA transfer can occur if enabled.
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u24 = 0,
    }),
    /// capture/compare mode register (output mode)
    /// offset: 0x18
    CCMR1_Output: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 selection This bit-field defines the direction of the channel (input/output) as well as the used input. Note: CC1S bits are writable only when the channel is OFF (CC1E = '0â in TIMx_CCER).
        CC1S: enum(u2) {
            /// CC1 channel is configured as output.
            B_0x0 = 0x0,
            /// CC1 channel is configured as input, IC1 is mapped on TI1.
            B_0x1 = 0x1,
            /// CC1 channel is configured as input, IC1 is mapped on TI2.
            B_0x2 = 0x2,
            /// CC1 channel is configured as input, IC1 is mapped on TRC. This mode is working only if an internal trigger input is selected through TS bit (TIMx_SMCR register)
            B_0x3 = 0x3,
        } = .B_0x0,
        /// Output Compare 1 fast enable This bit decreases the latency between a trigger event and a transition on the timer output. It must be used in one-pulse mode (OPM bit set in TIMx_CR1 register), to have the output pulse starting as soon as possible after the starting trigger.
        OC1FE: enum(u1) {
            /// CC1 behaves normally depending on counter and CCR1 values even when the trigger is ON. The minimum delay to activate CC1 output when an edge occurs on the trigger input is 5 clock cycles.
            B_0x0 = 0x0,
            /// An active edge on the trigger input acts like a compare match on CC1 output. Then, OC is set to the compare level independently of the result of the comparison. Delay to sample the trigger input and to activate CC1 output is reduced to 3 clock cycles. OCFE acts only if the channel is configured in PWM1 or PWM2 mode.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Output Compare 1 preload enable Note: These bits can not be modified as long as LOCK level 3 has been programmed (LOCK bits in TIMx_BDTR register) and CC1S=â00â (the channel is configured in output). The PWM mode can be used without validating the preload register only in one pulse mode (OPM bit set in TIMx_CR1 register). Else the behavior is not guaranteed.
        OC1PE: enum(u1) {
            /// Preload register on TIMx_CCR1 disabled. TIMx_CCR1 can be written at anytime, the new value is taken in account immediately.
            B_0x0 = 0x0,
            /// Preload register on TIMx_CCR1 enabled. Read/Write operations access the preload register. TIMx_CCR1 preload value is loaded in the active register at each update event.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Output Compare 1 mode These bits define the behavior of the output reference signal OC1REF from which OC1 and OC1N are derived. OC1REF is active high whereas OC1 and OC1N active level depends on CC1P and CC1NP bits. Note: These bits can not be modified as long as LOCK level 3 has been programmed (LOCK bits in TIMx_BDTR register) and CC1S=â00â (the channel is configured in output). In PWM mode, the OCREF level changes only when the result of the comparison changes or when the output compare mode switches from âfrozenâ mode to âPWMâ mode. On channels that have a complementary output, this bit field is preloaded. If the CCPC bit is set in the TIMx_CR2 register then the OC1M active bits take the new value from the preloaded bits only when a COM event is generated. The OC1M[3] bit is not contiguous, located in bit 16.
        OC1M1: enum(u3) {
            /// Frozen - The comparison between the output compare register TIMx_CCR1 and the counter TIMx_CNT has no effect on the outputs.
            B_0x0 = 0x0,
            /// Set channel 1 to active level on match. OC1REF signal is forced high when the counter TIMx_CNT matches the capture/compare register 1 (TIMx_CCR1).
            B_0x1 = 0x1,
            /// Set channel 1 to inactive level on match. OC1REF signal is forced low when the counter TIMx_CNT matches the capture/compare register 1 (TIMx_CCR1).
            B_0x2 = 0x2,
            /// Toggle - OC1REF toggles when TIMx_CNT=TIMx_CCR1.
            B_0x3 = 0x3,
            /// Force inactive level - OC1REF is forced low.
            B_0x4 = 0x4,
            /// Force active level - OC1REF is forced high.
            B_0x5 = 0x5,
            /// PWM mode 1 - Channel 1 is active as long as TIMx_CNT<TIMx_CCR1 else inactive.
            B_0x6 = 0x6,
            /// PWM mode 2 - Channel 1 is inactive as long as TIMx_CNT<TIMx_CCR1 else active.
            B_0x7 = 0x7,
            /// Retrigerrable OPM mode 1 - In up-counting mode, the channel is active until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes active again at the next update. In down-counting mode, the channel is inactive until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes inactive again at the next update.
            B_0x8 = 0x8,
            /// Retrigerrable OPM mode 2 - In up-counting mode, the channel is inactive until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 2 and the channels becomes inactive again at the next update. In down-counting mode, the channel is active until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes active again at the next update.
            B_0x9 = 0x9,
            /// Combined PWM mode 1 - OC1REF has the same behavior as in PWM mode 1. OC1REFC is the logical OR between OC1REF and OC2REF.
            B_0xC = 0xc,
            /// Combined PWM mode 2 - OC1REF has the same behavior as in PWM mode 2. OC1REFC is the logical AND between OC1REF and OC2REF.
            B_0xD = 0xd,
        } = .B_0x0,
        reserved8: u1 = 0,
        /// Capture/Compare 2 selection This bit-field defines the direction of the channel (input/output) as well as the used input. Note: CC2S bits are writable only when the channel is OFF (CC2E = '0â in TIMx_CCER).
        CC2S: enum(u2) {
            /// CC2 channel is configured as output.
            B_0x0 = 0x0,
            /// CC2 channel is configured as input, IC2 is mapped on TI2.
            B_0x1 = 0x1,
            /// CC2 channel is configured as input, IC2 is mapped on TI1.
            B_0x2 = 0x2,
            /// CC2 channel is configured as input, IC2 is mapped on TRC. This mode is working only if an internal trigger input is selected through the TS bit (TIMx_SMCR register)
            B_0x3 = 0x3,
        } = .B_0x0,
        /// Output Compare 2 fast enable
        OC2FE: u1 = 0x0,
        /// Output Compare 2 preload enable
        OC2PE: u1 = 0x0,
        /// Output Compare 2 mode
        OC2M1: u3 = 0x0,
        reserved16: u1 = 0,
        /// Output Compare 1 mode These bits define the behavior of the output reference signal OC1REF from which OC1 and OC1N are derived. OC1REF is active high whereas OC1 and OC1N active level depends on CC1P and CC1NP bits. Note: These bits can not be modified as long as LOCK level 3 has been programmed (LOCK bits in TIMx_BDTR register) and CC1S=â00â (the channel is configured in output). In PWM mode, the OCREF level changes only when the result of the comparison changes or when the output compare mode switches from âfrozenâ mode to âPWMâ mode. On channels that have a complementary output, this bit field is preloaded. If the CCPC bit is set in the TIMx_CR2 register then the OC1M active bits take the new value from the preloaded bits only when a COM event is generated. The OC1M[3] bit is not contiguous, located in bit 16.
        OC1M2: enum(u1) {
            /// Frozen - The comparison between the output compare register TIMx_CCR1 and the counter TIMx_CNT has no effect on the outputs.
            B_0x0 = 0x0,
            /// Set channel 1 to active level on match. OC1REF signal is forced high when the counter TIMx_CNT matches the capture/compare register 1 (TIMx_CCR1).
            B_0x1 = 0x1,
            /// Set channel 1 to inactive level on match. OC1REF signal is forced low when the counter TIMx_CNT matches the capture/compare register 1 (TIMx_CCR1).
            B_0x2 = 0x2,
            /// Toggle - OC1REF toggles when TIMx_CNT=TIMx_CCR1.
            B_0x3 = 0x3,
            /// Force inactive level - OC1REF is forced low.
            B_0x4 = 0x4,
            /// Force active level - OC1REF is forced high.
            B_0x5 = 0x5,
            /// PWM mode 1 - Channel 1 is active as long as TIMx_CNT<TIMx_CCR1 else inactive.
            B_0x6 = 0x6,
            /// PWM mode 2 - Channel 1 is inactive as long as TIMx_CNT<TIMx_CCR1 else active.
            B_0x7 = 0x7,
            /// Retrigerrable OPM mode 1 - In up-counting mode, the channel is active until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes active again at the next update. In down-counting mode, the channel is inactive until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes inactive again at the next update.
            B_0x8 = 0x8,
            /// Retrigerrable OPM mode 2 - In up-counting mode, the channel is inactive until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 2 and the channels becomes inactive again at the next update. In down-counting mode, the channel is active until a trigger event is detected (on TRGI signal). Then, a comparison is performed as in PWM mode 1 and the channels becomes active again at the next update.
            B_0x9 = 0x9,
            /// Combined PWM mode 1 - OC1REF has the same behavior as in PWM mode 1. OC1REFC is the logical OR between OC1REF and OC2REF.
            B_0xC = 0xc,
            /// Combined PWM mode 2 - OC1REF has the same behavior as in PWM mode 2. OC1REFC is the logical AND between OC1REF and OC2REF.
            B_0xD = 0xd,
        } = .B_0x0,
        reserved24: u7 = 0,
        /// Output Compare 2 mode
        OC2M2: u1 = 0x0,
        padding: u7 = 0,
    }),
    /// offset: 0x1c
    reserved28: [4]u8,
    /// capture/compare enable register
    /// offset: 0x20
    CCER: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 output enable When CC1 channel is configured as output, the OC1 level depends on MOE, OSSI, OSSR, OIS1, OIS1N and CC1NE bits, regardless of the CC1E bits state. Refer to for details.
        CC1E: enum(u1) {
            /// Capture mode disabled / OC1 is not active (see below)
            B_0x0 = 0x0,
            /// Capture mode enabled / OC1 signal is output on the corresponding output pin
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 output polarity When CC1 channel is configured as input, both CC1NP/CC1P bits select the active polarity of TI1FP1 and TI2FP1 for trigger or capture operations. CC1NP=0, CC1P=0: non-inverted/rising edge. The circuit is sensitive to TIxFP1 rising edge (capture or trigger operations in reset, external clock or trigger mode), TIxFP1 is not inverted (trigger operation in gated mode or encoder mode). CC1NP=0, CC1P=1: inverted/falling edge. The circuit is sensitive to TIxFP1 falling edge (capture or trigger operations in reset, external clock or trigger mode), TIxFP1 is inverted (trigger operation in gated mode or encoder mode). CC1NP=1, CC1P=1: non-inverted/both edges/ The circuit is sensitive to both TIxFP1 rising and falling edges (capture or trigger operations in reset, external clock or trigger mode), TIxFP1is not inverted (trigger operation in gated mode). This configuration must not be used in encoder mode. CC1NP=1, CC1P=0: this configuration is reserved, it must not be used. Note: This bit is not writable as soon as LOCK level 2 or 3 has been programmed (LOCK bits in TIMx_BDTR register). On channels that have a complementary output, this bit is preloaded. If the CCPC bit is set in the TIMx_CR2 register then the CC1P active bit takes the new value from the preloaded bit only when a Commutation event is generated.
        CC1P: enum(u1) {
            /// OC1 active high (output mode) / Edge sensitivity selection (input mode, see below)
            B_0x0 = 0x0,
            /// OC1 active low (output mode) / Edge sensitivity selection (input mode, see below)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 complementary output enable
        CC1NE: enum(u1) {
            /// Off - OC1N is not active. OC1N level is then function of MOE, OSSI, OSSR, OIS1, OIS1N and CC1E bits.
            B_0x0 = 0x0,
            /// On - OC1N signal is output on the corresponding output pin depending on MOE, OSSI, OSSR, OIS1, OIS1N and CC1E bits.
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 1 complementary output polarity CC1 channel configured as output: CC1 channel configured as input: This bit is used in conjunction with CC1P to define the polarity of TI1FP1 and TI2FP1. Refer to CC1P description. Note: This bit is not writable as soon as LOCK level 2 or 3 has been programmed (LOCK bits in TIMx_BDTR register) and CC1S=â00â (the channel is configured in output). On channels that have a complementary output, this bit is preloaded. If the CCPC bit is set in the TIMx_CR2 register then the CC1NP active bit takes the new value from the preloaded bit only when a Commutation event is generated.
        CC1NP: enum(u1) {
            /// OC1N active high
            B_0x0 = 0x0,
            /// OC1N active low
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Capture/Compare 2 output enable Refer to CC1E description
        CC2E: u1 = 0x0,
        /// Capture/Compare 2 output polarity Refer to CC1P description
        CC2P: u1 = 0x0,
        reserved7: u1 = 0,
        /// Capture/Compare 2 complementary output polarity Refer to CC1NP description
        CC2NP: u1 = 0x0,
        padding: u24 = 0,
    }),
    /// counter
    /// offset: 0x24
    CNT: mmio.Mmio(packed struct(u32) {
        /// counter value
        CNT: u16 = 0x0,
        reserved31: u15 = 0,
        /// UIF Copy
        UIFCPY: u1 = 0x0,
    }),
    /// prescaler
    /// offset: 0x28
    PSC: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// auto-reload register
    /// offset: 0x2c
    ARR: mmio.Mmio(packed struct(u32) {
        /// Auto-reload value
        ARR: u16 = 0xFFFF,
        padding: u16 = 0,
    }),
    /// repetition counter register
    /// offset: 0x30
    RCR: mmio.Mmio(packed struct(u32) {
        /// Repetition counter value
        REP: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// capture/compare register 1
    /// offset: 0x34
    CCR1: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 1 value
        CCR1: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// capture/compare register 2
    /// offset: 0x38
    CCR2: mmio.Mmio(packed struct(u32) {
        /// Capture/Compare 2 value
        CCR2: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x3c
    reserved60: [8]u8,
    /// break and dead-time register
    /// offset: 0x44
    BDTR: mmio.Mmio(packed struct(u32) {
        /// Dead-time generator setup This bit-field defines the duration of the dead-time inserted between the complementary outputs. DT correspond to this duration. DTG[7:5]=0xx => DT=DTG[7:0]x tdtg with tdtg=tDTS DTG[7:5]=10x => DT=(64+DTG[5:0])xtdtg with Tdtg=2xtDTS DTG[7:5]=110 => DT=(32+DTG[4:0])xtdtg with Tdtg=8xtDTS DTG[7:5]=111 => DT=(32+DTG[4:0])xtdtg with Tdtg=16xtDTS Example if TDTS=125ns (8MHz), dead-time possible values are: 0 to 15875 ns by 125 ns steps, 16 Âµs to 31750 ns by 250 ns steps, 32 Âµs to 63 Âµs by 1 Âµs steps, 64 Âµs to 126 Âµs by 2 Âµs steps Note: This bit-field can not be modified as long as LOCK level 1, 2 or 3 has been programmed (LOCK bits in TIMx_BDTR register).
        DTG: u8 = 0x0,
        /// Lock configuration These bits offer a write protection against software errors. Note: The LOCK bits can be written only once after the reset. Once the TIMx_BDTR register has been written, their content is frozen until the next reset.
        LOCK: enum(u2) {
            /// LOCK OFF - No bit is write protected
            B_0x0 = 0x0,
            /// LOCK Level 1 = DTG bits in TIMx_BDTR register, OISx and OISxN bits in TIMx_CR2 register and BKE/BKP/AOE bits in TIMx_BDTR register can no longer be written
            B_0x1 = 0x1,
            /// LOCK Level 2 = LOCK Level 1 + CC Polarity bits (CCxP/CCxNP bits in TIMx_CCER register, as long as the related channel is configured in output through the CCxS bits) as well as OSSR and OSSI bits can no longer be written.
            B_0x2 = 0x2,
            /// LOCK Level 3 = LOCK Level 2 + CC Control bits (OCxM and OCxPE bits in TIMx_CCMRx registers, as long as the related channel is configured in output through the CCxS bits) can no longer be written.
            B_0x3 = 0x3,
        } = .B_0x0,
        /// Off-state selection for Idle mode This bit is used when MOE=0 on channels configured as outputs. See OC/OCN enable description for more details (enable register (TIM15_CCER) on pageÂ 818). Note: This bit can not be modified as soon as the LOCK level 2 has been programmed (LOCK bits in TIMx_BDTR register).
        OSSI: enum(u1) {
            /// When inactive, OC/OCN outputs are disabled (OC/OCN enable output signal=0)
            B_0x0 = 0x0,
            /// When inactive, OC/OCN outputs are forced first with their idle level as soon as CCxE=1 or CCxNE=1. OC/OCN enable output signal=1)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Off-state selection for Run mode This bit is used when MOE=1 on channels that have a complementary output which are configured as outputs. OSSR is not implemented if no complementary output is implemented in the timer. See OC/OCN enable description for more details (enable register (TIM15_CCER) on pageÂ 818). Note: This bit can not be modified as soon as the LOCK level 2 has been programmed (LOCK bits in TIMx_BDTR register).
        OSSR: enum(u1) {
            /// When inactive, OC/OCN outputs are disabled (the timer releases the output control which is taken over by the AFIO logic, which forces a Hi-Z state)
            B_0x0 = 0x0,
            /// When inactive, OC/OCN outputs are enabled with their inactive level as soon as CCxE=1 or CCxNE=1 (the output is still controlled by the timer).
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Break enable 1; Break inputs (BRK and CCS clock failure event) enabled This bit cannot be modified when LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register). Note: Any write operation to this bit takes a delay of 1 APB clock cycle to become effective.
        BKE: enum(u1) {
            /// Break inputs (BRK and CCS clock failure event) disabled
            B_0x0 = 0x0,
            _,
        } = .B_0x0,
        /// Break polarity Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register). Any write operation to this bit takes a delay of 1 APB clock cycle to become effective.
        BKP: enum(u1) {
            /// Break input BRK is active low
            B_0x0 = 0x0,
            /// Break input BRK is active high
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Automatic output enable Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        AOE: enum(u1) {
            /// MOE can be set only by software
            B_0x0 = 0x0,
            /// MOE can be set by software or automatically at the next update event (if the break input is not be active)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Main output enable This bit is cleared asynchronously by hardware as soon as the break input is active. It is set by software or automatically depending on the AOE bit. It is acting only on the channels which are configured in output. See OC/OCN enable description for more details (enable register (TIM15_CCER) on pageÂ 818).
        MOE: enum(u1) {
            /// OC and OCN outputs are disabled or forced to idle state depending on the OSSI bit.
            B_0x0 = 0x0,
            /// OC and OCN outputs are enabled if their respective enable bits are set (CCxE, CCxNE in TIMx_CCER register)
            B_0x1 = 0x1,
        } = .B_0x0,
        /// Break filter This bit-field defines the frequency used to sample the BRK input signal and the length of the digital filter applied to BRK. The digital filter is made of an event counter in which N events are needed to validate a transition on the output: Note: This bit cannot be modified when LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKF: enum(u4) {
            /// No filter, BRK acts asynchronously
            B_0x0 = 0x0,
            /// fSAMPLING=fCK_INT, N=2
            B_0x1 = 0x1,
            /// fSAMPLING=fCK_INT, N=4
            B_0x2 = 0x2,
            /// fSAMPLING=fCK_INT, N=8
            B_0x3 = 0x3,
            /// fSAMPLING=fDTS/2, N=6
            B_0x4 = 0x4,
            /// fSAMPLING=fDTS/2, N=8
            B_0x5 = 0x5,
            /// fSAMPLING=fDTS/4, N=6
            B_0x6 = 0x6,
            /// fSAMPLING=fDTS/4, N=8
            B_0x7 = 0x7,
            /// fSAMPLING=fDTS/8, N=6
            B_0x8 = 0x8,
            /// fSAMPLING=fDTS/8, N=8
            B_0x9 = 0x9,
            /// fSAMPLING=fDTS/16, N=5
            B_0xA = 0xa,
            /// fSAMPLING=fDTS/16, N=6
            B_0xB = 0xb,
            /// fSAMPLING=fDTS/16, N=8
            B_0xC = 0xc,
            /// fSAMPLING=fDTS/32, N=5
            B_0xD = 0xd,
            /// fSAMPLING=fDTS/32, N=6
            B_0xE = 0xe,
            /// fSAMPLING=fDTS/32, N=8
            B_0xF = 0xf,
        } = .B_0x0,
        reserved26: u6 = 0,
        /// Break Disarm This bit is cleared by hardware when no break source is active. The BKDSRM bit must be set by software to release the bidirectional output control (open-drain output in Hi-Z state) and then be polled it until it is reset by hardware, indicating that the fault condition has disappeared. Note: Any write operation to this bit takes a delay of 1 APB clock cycle to become effective.
        BKDSRM: enum(u1) {
            /// Break input BRK is armed
            B_0x0 = 0x0,
            /// Break input BRK is disarmed
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved28: u1 = 0,
        /// Break Bidirectional In the bidirectional mode (BKBID bit set to 1), the break input is configured both in input mode and in open drain output mode. Any active break event asserts a low logic level on the Break input to indicate an internal break event to external devices. Note: This bit cannot be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register). Note: Any write operation to this bit takes a delay of 1 APB clock cycle to become effective.
        BKBID: enum(u1) {
            /// Break input BRK in input mode
            B_0x0 = 0x0,
            /// Break input BRK in bidirectional mode
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u3 = 0,
    }),
    /// DMA control register
    /// offset: 0x48
    DCR: mmio.Mmio(packed struct(u32) {
        /// DMA base address This 5-bit field defines the base-address for DMA transfers (when read/write access are done through the TIMx_DMAR address). DBA is defined as an offset starting from the address of the TIMx_CR1 register. Example: ...
        DBA: enum(u5) {
            /// TIMx_CR1,
            B_0x0 = 0x0,
            /// TIMx_CR2,
            B_0x1 = 0x1,
            /// TIMx_SMCR,
            B_0x2 = 0x2,
            _,
        } = .B_0x0,
        reserved8: u3 = 0,
        /// DMA burst length This 5-bit field defines the length of DMA transfers (the timer recognizes a burst transfer when a read or a write access is done to the TIMx_DMAR address). ...
        DBL: enum(u5) {
            /// 1 transfer,
            B_0x0 = 0x0,
            /// 2 transfers,
            B_0x1 = 0x1,
            /// 3 transfers,
            B_0x2 = 0x2,
            /// 18 transfers.
            B_0x11 = 0x11,
            _,
        } = .B_0x0,
        padding: u19 = 0,
    }),
    /// DMA address for full transfer
    /// offset: 0x4c
    DMAR: mmio.Mmio(packed struct(u32) {
        /// DMA register for burst accesses
        DMAB: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// offset: 0x50
    reserved80: [16]u8,
    /// TIM15 alternate register 1
    /// offset: 0x60
    AF1: mmio.Mmio(packed struct(u32) {
        /// BRK BKIN input enable This bit enables the BKIN alternate function input for the timerâs BRK input. BKIN input is 'ORedâ with the other BRK sources. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKINE: enum(u1) {
            /// BKIN input disabled
            B_0x0 = 0x0,
            /// BKIN input enabled
            B_0x1 = 0x1,
        } = .B_0x1,
        /// BRK COMP1 enable This bit enables the COMP1 for the timerâs BRK input. COMP1 output is 'ORedâ with the other BRK sources. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP1E: enum(u1) {
            /// COMP1 input disabled
            B_0x0 = 0x0,
            /// COMP1 input enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// BRK COMP2 enable This bit enables the COMP2 for the timerâs BRK input. COMP2 output is 'ORedâ with the other BRK sources. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP2E: enum(u1) {
            /// COMP2 input disabled
            B_0x0 = 0x0,
            /// COMP2 input enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        /// BRK COMP3 enable This bit enables the COMP3 for the timerâs BRK input. COMP3 output is 'ORedâ with the other BRK sources. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP3E: enum(u1) {
            /// COMP3 input disabled
            B_0x0 = 0x0,
            /// COMP3 input enabled
            B_0x1 = 0x1,
        } = .B_0x0,
        reserved9: u5 = 0,
        /// BRK BKIN input polarity This bit selects the BKIN alternate function input sensitivity. It must be programmed together with the BKP polarity bit. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKINP: enum(u1) {
            /// BKIN input is active low
            B_0x0 = 0x0,
            /// BKIN input is active high
            B_0x1 = 0x1,
        } = .B_0x0,
        /// BRK COMP1 input polarity This bit selects the COMP1 input sensitivity. It must be programmed together with the BKP polarity bit. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP1P: enum(u1) {
            /// COMP1 input is active low
            B_0x0 = 0x0,
            /// COMP1 input is active high
            B_0x1 = 0x1,
        } = .B_0x0,
        /// BRK COMP2 input polarity This bit selects the COMP2 input sensitivity. It must be programmed together with the BKP polarity bit. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP2P: enum(u1) {
            /// COMP2 input is active low
            B_0x0 = 0x0,
            /// COMP2 input is active high
            B_0x1 = 0x1,
        } = .B_0x0,
        /// BRK COMP3 input polarity This bit selects the COMP3 input sensitivity. It must be programmed together with the BKP polarity bit. Note: This bit can not be modified as long as LOCK level 1 has been programmed (LOCK bits in TIMx_BDTR register).
        BKCMP3P: enum(u1) {
            /// COMP3 input is active low
            B_0x0 = 0x0,
            /// COMP3 input is active high
            B_0x1 = 0x1,
        } = .B_0x0,
        padding: u19 = 0,
    }),
    /// offset: 0x64
    reserved100: [4]u8,
    /// input selection register
    /// offset: 0x68
    TISEL: mmio.Mmio(packed struct(u32) {
        /// selects TI1[0] to TI1[15] input Others: Reserved
        TI1SEL: enum(u4) {
            /// TIM15_CH1 input
            B_0x0 = 0x0,
            /// TIM2_IC1
            B_0x1 = 0x1,
            /// TIM3_IC1
            B_0x2 = 0x2,
            _,
        } = .B_0x0,
        reserved8: u4 = 0,
        /// selects TI2[0] to TI2[15] input Others: Reserved
        TI2SEL: enum(u4) {
            /// TIM15_CH2 input
            B_0x0 = 0x0,
            /// TIM2_IC2
            B_0x1 = 0x1,
            /// TIM3_IC2
            B_0x2 = 0x2,
            _,
        } = .B_0x0,
        padding: u20 = 0,
    }),
};
