// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Basic timers
pub const TIM6 = extern struct {
    /// control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// Counter enable
        CEN: u1 = 0x0,
        /// Update disable
        UDIS: u1 = 0x0,
        /// Update request source
        URS: u1 = 0x0,
        /// One-pulse mode
        OPM: u1 = 0x0,
        reserved7: u3 = 0,
        /// Auto-reload preload enable
        ARPE: u1 = 0x0,
        reserved11: u3 = 0,
        /// UIF status bit remapping
        UIFREMAP: u1 = 0x0,
        padding: u20 = 0,
    }),
    /// control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        reserved4: u4 = 0,
        /// Master mode selection
        MMS: u3 = 0x0,
        padding: u25 = 0,
    }),
    /// offset: 0x08
    reserved8: [4]u8,
    /// DMA/Interrupt enable register
    /// offset: 0x0c
    DIER: mmio.Mmio(packed struct(u32) {
        /// Update interrupt enable
        UIE: u1 = 0x0,
        reserved8: u7 = 0,
        /// Update DMA request enable
        UDE: u1 = 0x0,
        padding: u23 = 0,
    }),
    /// status register
    /// offset: 0x10
    SR: mmio.Mmio(packed struct(u32) {
        /// Update interrupt flag
        UIF: u1 = 0x0,
        padding: u31 = 0,
    }),
    /// event generation register
    /// offset: 0x14
    EGR: mmio.Mmio(packed struct(u32) {
        /// Update generation
        UG: u1 = 0x0,
        padding: u31 = 0,
    }),
    /// offset: 0x18
    reserved24: [12]u8,
    /// counter
    /// offset: 0x24
    CNT: mmio.Mmio(packed struct(u32) {
        /// Low counter value
        CNT: u16 = 0x0,
        reserved31: u15 = 0,
        /// UIF Copy
        UIFCPY: u1 = 0x0,
    }),
    /// prescaler
    /// offset: 0x28
    PSC: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u16 = 0x0,
        padding: u16 = 0,
    }),
    /// auto-reload register
    /// offset: 0x2c
    ARR: mmio.Mmio(packed struct(u32) {
        /// Low Auto-reload value
        ARR: u16 = 0x0,
        padding: u16 = 0,
    }),
};
