// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// USB Power Delivery interface
pub const UCPD1 = extern struct {
    /// UCPD configuration register
    /// offset: 0x00
    CFG1: mmio.Mmio(packed struct(u32) {
        /// HBITCLKDIV
        HBITCLKDIV: u6 = 0x0,
        /// IFRGAP
        IFRGAP: u5 = 0x0,
        /// TRANSWIN
        TRANSWIN: u5 = 0x0,
        reserved17: u1 = 0,
        /// PSC_USBPDCLK
        PSC_USBPDCLK: u3 = 0x0,
        /// RXORDSETEN
        RXORDSETEN: u9 = 0x0,
        /// TXDMAEN
        TXDMAEN: u1 = 0x0,
        /// RXDMAEN:
        RXDMAEN: u1 = 0x0,
        /// UCPDEN
        UCPDEN: u1 = 0x0,
    }),
    /// UCPD configuration register 2
    /// offset: 0x04
    CFG2: mmio.Mmio(packed struct(u32) {
        /// RXFILTDIS
        RXFILTDIS: u1 = 0x0,
        /// RXFILT2N3
        RXFILT2N3: u1 = 0x0,
        /// FORCECLK
        FORCECLK: u1 = 0x0,
        /// WUPEN
        WUPEN: u1 = 0x0,
        padding: u28 = 0,
    }),
    /// UCPD configuration register 3
    /// offset: 0x08
    CFG3: mmio.Mmio(packed struct(u32) {
        /// TRIM1_NG_CCRPD
        TRIM1_NG_CCRPD: u4 = 0x0,
        /// TRIM1_NG_CC1A5
        TRIM1_NG_CC1A5: u5 = 0x0,
        /// TRIM1_NG_CC3A0
        TRIM1_NG_CC3A0: u4 = 0x0,
        reserved16: u3 = 0,
        /// TRIM2_NG_CCRPD
        TRIM2_NG_CCRPD: u4 = 0x0,
        /// TRIM2_NG_CC1A5
        TRIM2_NG_CC1A5: u5 = 0x0,
        /// TRIM2_NG_CC3A0
        TRIM2_NG_CC3A0: u4 = 0x0,
        padding: u3 = 0,
    }),
    /// UCPD control register
    /// offset: 0x0c
    CR: mmio.Mmio(packed struct(u32) {
        /// TXMODE
        TXMODE: u2 = 0x0,
        /// TXSEND
        TXSEND: u1 = 0x0,
        /// TXHRST
        TXHRST: u1 = 0x0,
        /// RXMODE
        RXMODE: u1 = 0x0,
        /// PHYRXEN
        PHYRXEN: u1 = 0x0,
        /// PHYCCSEL
        PHYCCSEL: u1 = 0x0,
        /// ANASUBMODE
        ANASUBMODE: u2 = 0x0,
        /// ANAMODE
        ANAMODE: u1 = 0x0,
        /// CCENABLE
        CCENABLE: u2 = 0x0,
        reserved15: u3 = 0,
        /// DBATTEN
        DBATTEN: u1 = 0x0,
        /// FRSRXEN
        FRSRXEN: u1 = 0x0,
        /// FRSTX
        FRSTX: u1 = 0x0,
        /// RDCH
        RDCH: u1 = 0x0,
        reserved20: u1 = 0,
        /// CC1TCDIS
        CC1TCDIS: u1 = 0x0,
        /// CC2TCDIS
        CC2TCDIS: u1 = 0x0,
        padding: u10 = 0,
    }),
    /// UCPD Interrupt Mask Register
    /// offset: 0x10
    IMR: mmio.Mmio(packed struct(u32) {
        /// TXISIE
        TXISIE: u1 = 0x0,
        /// TXMSGDISCIE
        TXMSGDISCIE: u1 = 0x0,
        /// TXMSGSENTIE
        TXMSGSENTIE: u1 = 0x0,
        /// TXMSGABTIE
        TXMSGABTIE: u1 = 0x0,
        /// HRSTDISCIE
        HRSTDISCIE: u1 = 0x0,
        /// HRSTSENTIE
        HRSTSENTIE: u1 = 0x0,
        /// TXUNDIE
        TXUNDIE: u1 = 0x0,
        reserved8: u1 = 0,
        /// RXNEIE
        RXNEIE: u1 = 0x0,
        /// RXORDDETIE
        RXORDDETIE: u1 = 0x0,
        /// RXHRSTDETIE
        RXHRSTDETIE: u1 = 0x0,
        /// RXOVRIE
        RXOVRIE: u1 = 0x0,
        /// RXMSGENDIE
        RXMSGENDIE: u1 = 0x0,
        reserved14: u1 = 0,
        /// TYPECEVT1IE
        TYPECEVT1IE: u1 = 0x0,
        /// TYPECEVT2IE
        TYPECEVT2IE: u1 = 0x0,
        reserved20: u4 = 0,
        /// FRSEVTIE
        FRSEVTIE: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// UCPD Status Register
    /// offset: 0x14
    SR: mmio.Mmio(packed struct(u32) {
        /// TXIS
        TXIS: u1 = 0x0,
        /// TXMSGDISC
        TXMSGDISC: u1 = 0x0,
        /// TXMSGSENT
        TXMSGSENT: u1 = 0x0,
        /// TXMSGABT
        TXMSGABT: u1 = 0x0,
        /// HRSTDISC
        HRSTDISC: u1 = 0x0,
        /// HRSTSENT
        HRSTSENT: u1 = 0x0,
        /// TXUND
        TXUND: u1 = 0x0,
        reserved8: u1 = 0,
        /// RXNE
        RXNE: u1 = 0x0,
        /// RXORDDET
        RXORDDET: u1 = 0x0,
        /// RXHRSTDET
        RXHRSTDET: u1 = 0x0,
        /// RXOVR
        RXOVR: u1 = 0x0,
        /// RXMSGEND
        RXMSGEND: u1 = 0x0,
        /// RXERR
        RXERR: u1 = 0x0,
        /// TYPECEVT1
        TYPECEVT1: u1 = 0x0,
        /// TYPECEVT2
        TYPECEVT2: u1 = 0x0,
        /// TYPEC_VSTATE_CC1
        TYPEC_VSTATE_CC1: u2 = 0x0,
        /// TYPEC_VSTATE_CC2
        TYPEC_VSTATE_CC2: u2 = 0x0,
        /// FRSEVT
        FRSEVT: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// UCPD Interrupt Clear Register
    /// offset: 0x18
    ICR: mmio.Mmio(packed struct(u32) {
        reserved1: u1 = 0,
        /// TXMSGDISCCF
        TXMSGDISCCF: u1 = 0x0,
        /// TXMSGSENTCF
        TXMSGSENTCF: u1 = 0x0,
        /// TXMSGABTCF
        TXMSGABTCF: u1 = 0x0,
        /// HRSTDISCCF
        HRSTDISCCF: u1 = 0x0,
        /// HRSTSENTCF
        HRSTSENTCF: u1 = 0x0,
        /// TXUNDCF
        TXUNDCF: u1 = 0x0,
        reserved9: u2 = 0,
        /// RXORDDETCF
        RXORDDETCF: u1 = 0x0,
        /// RXHRSTDETCF
        RXHRSTDETCF: u1 = 0x0,
        /// RXOVRCF
        RXOVRCF: u1 = 0x0,
        /// RXMSGENDCF
        RXMSGENDCF: u1 = 0x0,
        reserved14: u1 = 0,
        /// TYPECEVT1CF
        TYPECEVT1CF: u1 = 0x0,
        /// TYPECEVT2CF
        TYPECEVT2CF: u1 = 0x0,
        reserved20: u4 = 0,
        /// FRSEVTCF
        FRSEVTCF: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// UCPD Tx Ordered Set Type Register
    /// offset: 0x1c
    TX_ORDSET: mmio.Mmio(packed struct(u32) {
        /// TXORDSET
        TXORDSET: u20 = 0x0,
        padding: u12 = 0,
    }),
    /// UCPD Tx Paysize Register
    /// offset: 0x20
    TX_PAYSZ: mmio.Mmio(packed struct(u32) {
        /// TXPAYSZ
        TXPAYSZ: u10 = 0x0,
        padding: u22 = 0,
    }),
    /// UCPD Tx Data Register
    /// offset: 0x24
    TXDR: mmio.Mmio(packed struct(u32) {
        /// TXDATA
        TXDATA: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// UCPD Rx Ordered Set Register
    /// offset: 0x28
    RX_ORDSET: mmio.Mmio(packed struct(u32) {
        /// RXORDSET
        RXORDSET: u3 = 0x0,
        /// RXSOP3OF4
        RXSOP3OF4: u1 = 0x0,
        /// RXSOPKINVALID
        RXSOPKINVALID: u3 = 0x0,
        padding: u25 = 0,
    }),
    /// UCPD Rx Paysize Register
    /// offset: 0x2c
    RX_PAYSZ: mmio.Mmio(packed struct(u32) {
        /// RXPAYSZ
        RXPAYSZ: u10 = 0x0,
        padding: u22 = 0,
    }),
    /// UCPD Receive Data Register
    /// offset: 0x30
    RXDR: mmio.Mmio(packed struct(u32) {
        /// RXDATA
        RXDATA: u8 = 0x0,
        padding: u24 = 0,
    }),
    /// UCPD Rx Ordered Set Extension Register
    /// offset: 0x34
    RX_ORDEXT1: mmio.Mmio(packed struct(u32) {
        /// RXSOPX1
        RXSOPX1: u20 = 0x0,
        padding: u12 = 0,
    }),
    /// UCPD Rx Ordered Set Extension Register
    /// offset: 0x38
    RX_ORDEXT2: mmio.Mmio(packed struct(u32) {
        /// RXSOPX2
        RXSOPX2: u20 = 0x0,
        padding: u12 = 0,
    }),
    /// offset: 0x3c
    reserved60: [952]u8,
    /// UCPD IP ID register
    /// offset: 0x3f4
    IPVER: mmio.Mmio(packed struct(u32) {
        /// IPVER
        IPVER: u32 = 0x10,
    }),
    /// UCPD IP ID register
    /// offset: 0x3f8
    IPID: mmio.Mmio(packed struct(u32) {
        /// IPID
        IPID: u32 = 0x150021,
    }),
    /// UCPD IP ID register
    /// offset: 0x3fc
    MID: mmio.Mmio(packed struct(u32) {
        /// IPID
        IPID: u32 = 0xA3C5DD01,
    }),
};
