// register types generated by regz from STM32G071.svd
const mmio = @import("../../../mmio.zig");

const types = @import("../../types.zig");

/// Universal synchronous asynchronous receiver transmitter
pub const USART1 = extern struct {
    /// Control register 1
    /// offset: 0x00
    CR1: mmio.Mmio(packed struct(u32) {
        /// USART enable
        UE: u1 = 0x0,
        /// USART enable in Stop mode
        UESM: u1 = 0x0,
        /// Receiver enable
        RE: u1 = 0x0,
        /// Transmitter enable
        TE: u1 = 0x0,
        /// IDLE interrupt enable
        IDLEIE: u1 = 0x0,
        /// RXNE interrupt enable
        RXNEIE: u1 = 0x0,
        /// Transmission complete interrupt enable
        TCIE: u1 = 0x0,
        /// interrupt enable
        TXEIE: u1 = 0x0,
        /// PE interrupt enable
        PEIE: u1 = 0x0,
        /// Parity selection
        PS: u1 = 0x0,
        /// Parity control enable
        PCE: u1 = 0x0,
        /// Receiver wakeup method
        WAKE: u1 = 0x0,
        /// Word length
        M0: u1 = 0x0,
        /// Mute mode enable
        MME: u1 = 0x0,
        /// Character match interrupt enable
        CMIE: u1 = 0x0,
        /// Oversampling mode
        OVER8: u1 = 0x0,
        /// DEDT
        DEDT: u5 = 0x0,
        /// DEAT
        DEAT: u5 = 0x0,
        /// Receiver timeout interrupt enable
        RTOIE: u1 = 0x0,
        /// End of Block interrupt enable
        EOBIE: u1 = 0x0,
        /// Word length
        M1: u1 = 0x0,
        /// FIFO mode enable
        FIFOEN: u1 = 0x0,
        /// TXFIFO empty interrupt enable
        TXFEIE: u1 = 0x0,
        /// RXFIFO Full interrupt enable
        RXFFIE: u1 = 0x0,
    }),
    /// Control register 2
    /// offset: 0x04
    CR2: mmio.Mmio(packed struct(u32) {
        /// Synchronous Slave mode enable
        SLVEN: u1 = 0x0,
        reserved3: u2 = 0,
        /// When the DSI_NSS bit is set, the NSS pin input will be ignored
        DIS_NSS: u1 = 0x0,
        /// 7-bit Address Detection/4-bit Address Detection
        ADDM7: u1 = 0x0,
        /// LIN break detection length
        LBDL: u1 = 0x0,
        /// LIN break detection interrupt enable
        LBDIE: u1 = 0x0,
        reserved8: u1 = 0,
        /// Last bit clock pulse
        LBCL: u1 = 0x0,
        /// Clock phase
        CPHA: u1 = 0x0,
        /// Clock polarity
        CPOL: u1 = 0x0,
        /// Clock enable
        CLKEN: u1 = 0x0,
        /// STOP bits
        STOP: u2 = 0x0,
        /// LIN mode enable
        LINEN: u1 = 0x0,
        /// Swap TX/RX pins
        SWAP: u1 = 0x0,
        /// RX pin active level inversion
        RXINV: u1 = 0x0,
        /// TX pin active level inversion
        TXINV: u1 = 0x0,
        /// Binary data inversion
        TAINV: u1 = 0x0,
        /// Most significant bit first
        MSBFIRST: u1 = 0x0,
        /// Auto baud rate enable
        ABREN: u1 = 0x0,
        /// Auto baud rate mode
        ABRMOD: u2 = 0x0,
        /// Receiver timeout enable
        RTOEN: u1 = 0x0,
        /// Address of the USART node
        ADD0_3: u4 = 0x0,
        /// Address of the USART node
        ADD4_7: u4 = 0x0,
    }),
    /// Control register 3
    /// offset: 0x08
    CR3: mmio.Mmio(packed struct(u32) {
        /// Error interrupt enable
        EIE: u1 = 0x0,
        /// Ir mode enable
        IREN: u1 = 0x0,
        /// Ir low-power
        IRLP: u1 = 0x0,
        /// Half-duplex selection
        HDSEL: u1 = 0x0,
        /// Smartcard NACK enable
        NACK: u1 = 0x0,
        /// Smartcard mode enable
        SCEN: u1 = 0x0,
        /// DMA enable receiver
        DMAR: u1 = 0x0,
        /// DMA enable transmitter
        DMAT: u1 = 0x0,
        /// RTS enable
        RTSE: u1 = 0x0,
        /// CTS enable
        CTSE: u1 = 0x0,
        /// CTS interrupt enable
        CTSIE: u1 = 0x0,
        /// One sample bit method enable
        ONEBIT: u1 = 0x0,
        /// Overrun Disable
        OVRDIS: u1 = 0x0,
        /// DMA Disable on Reception Error
        DDRE: u1 = 0x0,
        /// Driver enable mode
        DEM: u1 = 0x0,
        /// Driver enable polarity selection
        DEP: u1 = 0x0,
        reserved17: u1 = 0,
        /// Smartcard auto-retry count
        SCARCNT: u3 = 0x0,
        /// Wakeup from Stop mode interrupt flag selection
        WUS: u2 = 0x0,
        /// Wakeup from Stop mode interrupt enable
        WUFIE: u1 = 0x0,
        /// threshold interrupt enable
        TXFTIE: u1 = 0x0,
        /// Tr Complete before guard time, interrupt enable
        TCBGTIE: u1 = 0x0,
        /// Receive FIFO threshold configuration
        RXFTCFG: u3 = 0x0,
        /// RXFIFO threshold interrupt enable
        RXFTIE: u1 = 0x0,
        /// TXFIFO threshold configuration
        TXFTCFG: u3 = 0x0,
    }),
    /// Baud rate register
    /// offset: 0x0c
    BRR: mmio.Mmio(packed struct(u32) {
        /// BRR_0_3
        BRR_0_3: u4 = 0x0,
        /// BRR_4_15
        BRR_4_15: u12 = 0x0,
        padding: u16 = 0,
    }),
    /// Guard time and prescaler register
    /// offset: 0x10
    GTPR: mmio.Mmio(packed struct(u32) {
        /// Prescaler value
        PSC: u8 = 0x0,
        /// Guard time value
        GT: u8 = 0x0,
        padding: u16 = 0,
    }),
    /// Receiver timeout register
    /// offset: 0x14
    RTOR: mmio.Mmio(packed struct(u32) {
        /// Receiver timeout value
        RTO: u24 = 0x0,
        /// Block Length
        BLEN: u8 = 0x0,
    }),
    /// Request register
    /// offset: 0x18
    RQR: mmio.Mmio(packed struct(u32) {
        /// Auto baud rate request
        ABRRQ: u1 = 0x0,
        /// Send break request
        SBKRQ: u1 = 0x0,
        /// Mute mode request
        MMRQ: u1 = 0x0,
        /// Receive data flush request
        RXFRQ: u1 = 0x0,
        /// Transmit data flush request
        TXFRQ: u1 = 0x0,
        padding: u27 = 0,
    }),
    /// Interrupt & status register
    /// offset: 0x1c
    ISR: mmio.Mmio(packed struct(u32) {
        /// PE
        PE: u1 = 0x0,
        /// FE
        FE: u1 = 0x0,
        /// NF
        NF: u1 = 0x0,
        /// ORE
        ORE: u1 = 0x0,
        /// IDLE
        IDLE: u1 = 0x0,
        /// RXNE
        RXNE: u1 = 0x0,
        /// TC
        TC: u1 = 0x1,
        /// TXE
        TXE: u1 = 0x1,
        /// LBDF
        LBDF: u1 = 0x0,
        /// CTSIF
        CTSIF: u1 = 0x0,
        /// CTS
        CTS: u1 = 0x0,
        /// RTOF
        RTOF: u1 = 0x0,
        /// EOBF
        EOBF: u1 = 0x0,
        /// SPI slave underrun error flag
        UDR: u1 = 0x0,
        /// ABRE
        ABRE: u1 = 0x0,
        /// ABRF
        ABRF: u1 = 0x0,
        /// BUSY
        BUSY: u1 = 0x0,
        /// CMF
        CMF: u1 = 0x0,
        /// SBKF
        SBKF: u1 = 0x0,
        /// RWU
        RWU: u1 = 0x0,
        /// WUF
        WUF: u1 = 0x0,
        /// TEACK
        TEACK: u1 = 0x0,
        /// REACK
        REACK: u1 = 0x0,
        /// TXFIFO Empty
        TXFE: u1 = 0x0,
        /// RXFIFO Full
        RXFF: u1 = 0x0,
        /// Transmission complete before guard time flag
        TCBGT: u1 = 0x0,
        /// RXFIFO threshold flag
        RXFT: u1 = 0x0,
        /// TXFIFO threshold flag
        TXFT: u1 = 0x0,
        padding: u4 = 0,
    }),
    /// Interrupt flag clear register
    /// offset: 0x20
    ICR: mmio.Mmio(packed struct(u32) {
        /// Parity error clear flag
        PECF: u1 = 0x0,
        /// Framing error clear flag
        FECF: u1 = 0x0,
        /// Noise detected clear flag
        NCF: u1 = 0x0,
        /// Overrun error clear flag
        ORECF: u1 = 0x0,
        /// Idle line detected clear flag
        IDLECF: u1 = 0x0,
        /// TXFIFO empty clear flag
        TXFECF: u1 = 0x0,
        /// Transmission complete clear flag
        TCCF: u1 = 0x0,
        /// Transmission complete before Guard time clear flag
        TCBGTCF: u1 = 0x0,
        /// LIN break detection clear flag
        LBDCF: u1 = 0x0,
        /// CTS clear flag
        CTSCF: u1 = 0x0,
        reserved11: u1 = 0,
        /// Receiver timeout clear flag
        RTOCF: u1 = 0x0,
        /// End of block clear flag
        EOBCF: u1 = 0x0,
        /// SPI slave underrun clear flag
        UDRCF: u1 = 0x0,
        reserved17: u3 = 0,
        /// Character match clear flag
        CMCF: u1 = 0x0,
        reserved20: u2 = 0,
        /// Wakeup from Stop mode clear flag
        WUCF: u1 = 0x0,
        padding: u11 = 0,
    }),
    /// Receive data register
    /// offset: 0x24
    RDR: mmio.Mmio(packed struct(u32) {
        /// Receive data value
        RDR: u9 = 0x0,
        padding: u23 = 0,
    }),
    /// Transmit data register
    /// offset: 0x28
    TDR: mmio.Mmio(packed struct(u32) {
        /// Transmit data value
        TDR: u9 = 0x0,
        padding: u23 = 0,
    }),
    /// Prescaler register
    /// offset: 0x2c
    PRESC: mmio.Mmio(packed struct(u32) {
        /// Clock prescaler
        PRESCALER: u4 = 0x0,
        padding: u28 = 0,
    }),
};
