//! STM32G071 - register definitions generated by regz from STM32G071.svd
const mmio = @import("../mmio.zig");

pub const types = @import("types.zig");

pub const Properties = struct {
    has_vtor: ?bool = null,
    has_mpu: ?bool = null,
    has_fpu: ?bool = null,
    interrupt_priority_bits: ?u8 = null,
    dma_channel_count: ?u32 = null,
};

pub const Interrupt = struct {
    name: [:0]const u8,
    index: i16,
    description: ?[:0]const u8,
};

pub const properties: Properties = .{
    .has_vtor = null,
    .has_mpu = true,
    .has_fpu = false,
    .interrupt_priority_bits = 4,
    .dma_channel_count = null,
};

pub const raw_properties = struct {
    pub const @"cpu.endian" = "little";
    pub const @"cpu.fpuPresent" = "false";
    pub const @"cpu.mpuPresent" = "true";
    pub const @"cpu.name" = "CM0";
    pub const @"cpu.nvicPrioBits" = "4";
    pub const @"cpu.revision" = "r0p1";
    pub const @"cpu.vendorSystickConfig" = "false";
};

pub const interrupts: []const Interrupt = &.{
    .{ .name = "NMI", .index = -14, .description = null },
    .{ .name = "HardFault", .index = -13, .description = null },
    .{ .name = "SVCall", .index = -5, .description = null },
    .{ .name = "PendSV", .index = -2, .description = null },
    .{ .name = "SysTick", .index = -1, .description = null },
    .{ .name = "WWDG", .index = 0, .description = "Window watchdog interrupt" },
    .{ .name = "PVD", .index = 1, .description = "Power voltage detector interrupt" },
    .{ .name = "RTC_STAMP", .index = 2, .description = "RTC and TAMP interrupts" },
    .{ .name = "FLASH", .index = 3, .description = "Flash global interrupt" },
    .{ .name = "RCC", .index = 4, .description = "RCC global interrupt" },
    .{ .name = "EXTI0_1", .index = 5, .description = "EXTI line 0 & 1 interrupt" },
    .{ .name = "EXTI2_3", .index = 6, .description = "EXTI line 2 & 3 interrupt" },
    .{ .name = "EXTI4_15", .index = 7, .description = "EXTI line 4 to 15 interrupt" },
    .{ .name = "UCPD1_UCPD2", .index = 8, .description = "UCPD global interrupt" },
    .{ .name = "DMA_Channel1", .index = 9, .description = "DMA channel 1 interrupt" },
    .{ .name = "DMA_Channel2_3", .index = 10, .description = "DMA channel 2 & 3 interrupts" },
    .{ .name = "DMA_Channel4_5_6_7", .index = 11, .description = "DMA channel 4, 5, 6 & 7 and DMAMUX" },
    .{ .name = "ADC_COMP", .index = 12, .description = "ADC and COMP interrupts" },
    .{ .name = "TIM1_BRK_UP_TRG_COMP", .index = 13, .description = "TIM1 break, update, trigger" },
    .{ .name = "TIM1_CC", .index = 14, .description = "TIM1 Capture Compare interrupt" },
    .{ .name = "TIM2", .index = 15, .description = "TIM2 global interrupt" },
    .{ .name = "TIM3", .index = 16, .description = "TIM3 global interrupt" },
    .{ .name = "TIM6_DAC_LPTIM1", .index = 17, .description = "TIM6 + LPTIM1 and DAC global interrupt" },
    .{ .name = "TIM7_LPTIM2", .index = 18, .description = "TIM7 + LPTIM2 global interrupt" },
    .{ .name = "TIM14", .index = 19, .description = "TIM14 global interrupt" },
    .{ .name = "TIM15", .index = 20, .description = "Timer 15 global interrupt" },
    .{ .name = "TIM16", .index = 21, .description = "TIM16 global interrupt" },
    .{ .name = "TIM17", .index = 22, .description = "TIM17 global interrupt" },
    .{ .name = "I2C1", .index = 23, .description = "I2C1 global interrupt" },
    .{ .name = "I2C2", .index = 24, .description = "I2C2 global interrupt" },
    .{ .name = "SPI1", .index = 25, .description = "SPI1 global interrupt" },
    .{ .name = "SPI2", .index = 26, .description = "SPI2 global interrupt" },
    .{ .name = "USART1", .index = 27, .description = "USART1 global interrupt" },
    .{ .name = "USART2", .index = 28, .description = "USART2 global interrupt" },
    .{ .name = "USART3_USART4_LPUART1", .index = 29, .description = "USART3 + USART4 + LPUART1" },
    .{ .name = "CEC", .index = 30, .description = "CEC global interrupt" },
    .{ .name = "RNG", .index = 31, .description = "RNG global interrupts" },
};

pub fn irqIndex(comptime name: [:0]const u8) comptime_int {
    for (interrupts) |entry| {
        if (entry.name.len != name.len) continue;
        var match = true;
        for (entry.name, name) |a, b| {
            if (a != b) {
                match = false;
                break;
            }
        }
        if (match) return entry.index;
    }
    @compileError("unknown interrupt: " ++ name);
}

const std = @import("std");
pub const cc: std.builtin.CallingConvention = .{ .arm_aapcs = .{} };
pub const Handler = *const fn () callconv(cc) void;
pub const unhandled: Handler = &defaultHandler;
fn defaultHandler() callconv(cc) void {
    while (true) {}
}

pub const VectorTable = extern struct {
    initial_stack_pointer: *const anyopaque,
    Reset: Handler,
    NMI: Handler = unhandled,
    HardFault: Handler = unhandled,
    reserved2: [7]u32 = undefined,
    SVCall: Handler = unhandled,
    reserved10: [2]u32 = undefined,
    PendSV: Handler = unhandled,
    SysTick: Handler = unhandled,
    /// Window watchdog interrupt
    WWDG: Handler = unhandled,
    /// Power voltage detector interrupt
    PVD: Handler = unhandled,
    /// RTC and TAMP interrupts
    RTC_STAMP: Handler = unhandled,
    /// Flash global interrupt
    FLASH: Handler = unhandled,
    /// RCC global interrupt
    RCC: Handler = unhandled,
    /// EXTI line 0 & 1 interrupt
    EXTI0_1: Handler = unhandled,
    /// EXTI line 2 & 3 interrupt
    EXTI2_3: Handler = unhandled,
    /// EXTI line 4 to 15 interrupt
    EXTI4_15: Handler = unhandled,
    /// UCPD global interrupt
    UCPD1_UCPD2: Handler = unhandled,
    /// DMA channel 1 interrupt
    DMA_Channel1: Handler = unhandled,
    /// DMA channel 2 & 3 interrupts
    DMA_Channel2_3: Handler = unhandled,
    /// DMA channel 4, 5, 6 & 7 and DMAMUX
    DMA_Channel4_5_6_7: Handler = unhandled,
    /// ADC and COMP interrupts
    ADC_COMP: Handler = unhandled,
    /// TIM1 break, update, trigger
    TIM1_BRK_UP_TRG_COMP: Handler = unhandled,
    /// TIM1 Capture Compare interrupt
    TIM1_CC: Handler = unhandled,
    /// TIM2 global interrupt
    TIM2: Handler = unhandled,
    /// TIM3 global interrupt
    TIM3: Handler = unhandled,
    /// TIM6 + LPTIM1 and DAC global interrupt
    TIM6_DAC_LPTIM1: Handler = unhandled,
    /// TIM7 + LPTIM2 global interrupt
    TIM7_LPTIM2: Handler = unhandled,
    /// TIM14 global interrupt
    TIM14: Handler = unhandled,
    /// Timer 15 global interrupt
    TIM15: Handler = unhandled,
    /// TIM16 global interrupt
    TIM16: Handler = unhandled,
    /// TIM17 global interrupt
    TIM17: Handler = unhandled,
    /// I2C1 global interrupt
    I2C1: Handler = unhandled,
    /// I2C2 global interrupt
    I2C2: Handler = unhandled,
    /// SPI1 global interrupt
    SPI1: Handler = unhandled,
    /// SPI2 global interrupt
    SPI2: Handler = unhandled,
    /// USART1 global interrupt
    USART1: Handler = unhandled,
    /// USART2 global interrupt
    USART2: Handler = unhandled,
    /// USART3 + USART4 + LPUART1
    USART3_USART4_LPUART1: Handler = unhandled,
    /// CEC global interrupt
    CEC: Handler = unhandled,
    /// RNG global interrupts
    RNG: Handler = unhandled,
};

pub const peripherals = struct {
    /// General-purpose-timers
    pub const TIM2: *volatile types.peripherals.TIM2 = @ptrFromInt(0x40000000);
    /// General-purpose-timers
    pub const TIM3: *volatile types.peripherals.TIM2 = @ptrFromInt(0x40000400);
    /// Basic timers
    pub const TIM6: *volatile types.peripherals.TIM6 = @ptrFromInt(0x40001000);
    /// Basic timers
    pub const TIM7: *volatile types.peripherals.TIM6 = @ptrFromInt(0x40001400);
    /// General purpose timers
    pub const TIM14: *volatile types.peripherals.TIM14 = @ptrFromInt(0x40002000);
    /// Real-time clock
    pub const RTC: *volatile types.peripherals.RTC = @ptrFromInt(0x40002800);
    /// System window watchdog
    pub const WWDG: *volatile types.peripherals.WWDG = @ptrFromInt(0x40002c00);
    /// Independent watchdog
    pub const IWDG: *volatile types.peripherals.IWDG = @ptrFromInt(0x40003000);
    /// Serial peripheral interface/Inter-IC sound
    pub const SPI2: *volatile types.peripherals.SPI1 = @ptrFromInt(0x40003800);
    /// Universal synchronous asynchronous receiver transmitter
    pub const USART2: *volatile types.peripherals.USART1 = @ptrFromInt(0x40004400);
    /// Universal synchronous asynchronous receiver transmitter
    pub const USART3: *volatile types.peripherals.USART1 = @ptrFromInt(0x40004800);
    /// Universal synchronous asynchronous receiver transmitter
    pub const USART4: *volatile types.peripherals.USART1 = @ptrFromInt(0x40004c00);
    /// Inter-integrated circuit
    pub const I2C1: *volatile types.peripherals.I2C1 = @ptrFromInt(0x40005400);
    /// Inter-integrated circuit
    pub const I2C2: *volatile types.peripherals.I2C1 = @ptrFromInt(0x40005800);
    /// Power control
    pub const PWR: *volatile types.peripherals.PWR = @ptrFromInt(0x40007000);
    /// DAC
    pub const DAC: *volatile types.peripherals.DAC = @ptrFromInt(0x40007400);
    /// HDMI-CEC
    pub const HDMI_CEC: *volatile types.peripherals.HDMI_CEC = @ptrFromInt(0x40007800);
    /// Low power timer
    pub const LPTIM1: *volatile types.peripherals.LPTIM1 = @ptrFromInt(0x40007c00);
    /// Universal synchronous asynchronous receiver transmitter
    pub const LPUART: *volatile types.peripherals.LPUART = @ptrFromInt(0x40008000);
    /// Low power timer
    pub const LPTIM2: *volatile types.peripherals.LPTIM1 = @ptrFromInt(0x40009400);
    /// USB Power Delivery interface
    pub const UCPD1: *volatile types.peripherals.UCPD1 = @ptrFromInt(0x4000a000);
    /// USB Power Delivery interface
    pub const UCPD2: *volatile types.peripherals.UCPD1 = @ptrFromInt(0x4000a400);
    /// Tamper and backup registers
    pub const TAMP: *volatile types.peripherals.TAMP = @ptrFromInt(0x4000b000);
    /// System configuration controller
    pub const SYSCFG_VREFBUF: *volatile types.peripherals.SYSCFG_VREFBUF = @ptrFromInt(0x40010000);
    /// COMP1
    pub const COMP: *volatile types.peripherals.COMP = @ptrFromInt(0x40010200);
    /// Analog to Digital Converter instance 1
    pub const ADC: *volatile types.peripherals.ADC = @ptrFromInt(0x40012400);
    /// Advanced-timers
    pub const TIM1: *volatile types.peripherals.TIM1 = @ptrFromInt(0x40012c00);
    /// Serial peripheral interface/Inter-IC sound
    pub const SPI1: *volatile types.peripherals.SPI1 = @ptrFromInt(0x40013000);
    /// Universal synchronous asynchronous receiver transmitter
    pub const USART1: *volatile types.peripherals.USART1 = @ptrFromInt(0x40013800);
    /// General purpose timers
    pub const TIM15: *volatile types.peripherals.TIM15 = @ptrFromInt(0x40014000);
    /// General purpose timers
    pub const TIM16: *volatile types.peripherals.TIM16 = @ptrFromInt(0x40014400);
    /// General purpose timers
    pub const TIM17: *volatile types.peripherals.TIM16 = @ptrFromInt(0x40014800);
    /// Debug support
    pub const DBG: *volatile types.peripherals.DBG = @ptrFromInt(0x40015800);
    /// DMA controller
    pub const DMA: *volatile types.peripherals.DMA = @ptrFromInt(0x40020000);
    /// DMAMUX
    pub const DMAMUX: *volatile types.peripherals.DMAMUX = @ptrFromInt(0x40020800);
    /// Reset and clock control
    pub const RCC: *volatile types.peripherals.RCC = @ptrFromInt(0x40021000);
    /// External interrupt/event controller
    pub const EXTI: *volatile types.peripherals.EXTI = @ptrFromInt(0x40021800);
    /// Flash
    pub const FLASH: *volatile types.peripherals.FLASH = @ptrFromInt(0x40022000);
    /// Cyclic redundancy check calculation unit
    pub const CRC: *volatile types.peripherals.CRC = @ptrFromInt(0x40023000);
    /// Random number generator
    pub const RNG: *volatile types.peripherals.RNG = @ptrFromInt(0x40025000);
    /// Nested Vectored Interrupt Controller (ARM core peripheral)
    pub const NVIC: *volatile types.peripherals.NVIC = @ptrFromInt(0xE000E100);
    /// SysTick Timer (ARM core peripheral)
    pub const SysTick: *volatile types.peripherals.SysTick = @ptrFromInt(0xE000E010);
    /// General-purpose I/Os
    pub const GPIOA: *volatile types.peripherals.GPIOA = @ptrFromInt(0x50000000);
    /// General-purpose I/Os
    pub const GPIOB: *volatile types.peripherals.GPIOB = @ptrFromInt(0x50000400);
    /// General-purpose I/Os
    pub const GPIOC: *volatile types.peripherals.GPIOB = @ptrFromInt(0x50000800);
    /// General-purpose I/Os
    pub const GPIOD: *volatile types.peripherals.GPIOB = @ptrFromInt(0x50000c00);
    /// General-purpose I/Os
    pub const GPIOF: *volatile types.peripherals.GPIOB = @ptrFromInt(0x50001400);
};
