/// NUCLEO-G071RB Board Support Package.
///
/// Provides drivers and board configuration for the STM32G071RB on the
/// ST NUCLEO-64 board. Register definitions are generated by regz from
/// the STM32G071 SVD file.
///
/// Board features:
///   - STM32G071RB: Cortex-M0+, 128KB flash, 36KB RAM
///   - SYSCLK selectable per lab (HSI16 reset default, or PLL → 32 MHz)
///   - User LED (LD4) on PA5
///   - USART2 on PA2/PA3 (AF1) routed to ST-Link Virtual COM Port
///   - ST-Link V2-1 onboard debug probe (SWD + VCP over USB)
///
/// Usage from a lab application:
///
///   const board = @import("board");
///
///   board.Hardware.init(.{ .systick_tick = &myTickFn });
///   board.Hardware.led.toggle();
///   board.Hardware.serial.puts("hello\r\n");
///
pub const Hardware = @import("hardware.zig").Hardware;
pub const clock = @import("clock.zig");
pub const gpio = @import("gpio.zig");
pub const uart = @import("uart.zig");
pub const i2c = @import("i2c.zig");
pub const startup = @import("startup.zig");
pub const chip = @import("chip/STM32G071.zig");
pub const mmio = @import("mmio.zig");
